### ISSUE TITLE
Unable to render content from nested slots in RSpec

### ISSUE THREAD

**Issue by peteryates** [github/view_component#1000]
I'm currently [upgrading the GOV.UK components](https://github.com/DFE-Digital/govuk-components/pull/158) so they're using the latest version of ViewComponent and the new slots API. It's a huge improvement so thanks for the hard work.

I've hit a snag in testing something that appears to work in practice.

For a bit of background, the GOV.UK Design System Nunjucks components have lots of settings that can be passed either a `text:` or `html:` variant. The [accordion](https://design-system.service.gov.uk/components/accordion/) is a good example. In Rails we're favouring passing a block of HTML instead of a string so we're making better use of the ViewComponent's slots.

### Steps to reproduce

Demo repo here: https://github.com/peteryates/view-component-slot-demo

1. [create a component with two levels of nested slots](https://github.com/peteryates/view-component-slot-demo/blob/master/app/components/accordion_component.rb). Note the `#heading` method will return either the `#heading_text` or `#heading_html` depending on what's set
2. [check it works in a view](https://github.com/peteryates/view-component-slot-demo/blob/master/app/views/details/index.html.erb). It looks like it does, here's the rendered output. **part two**'s heading is set via the `heading_html` block.
  
   ![Screenshot from 2021-07-03 12-31-33](https://user-images.githubusercontent.com/128088/124353134-9308c880-dbfc-11eb-8127-2b2240db7b2a.png)

3. [try to ensure the behaviour is correct in RSpec](https://github.com/peteryates/view-component-slot-demo/blob/master/spec/components/accordion_component_spec.rb#L41). I just can't get anything passed in via the block to render, `heading_html` is always `null` and the spec fails with:
   ```
   "custom heading one" expected within "h3" in following template:
   <li>
       <h3></h3>
       <div></div>
   </li>
   ```

### Expected behavior

The content passed in to `heading_html` via a block should be in the output, like in the view.

### Actual behavior

It's always empty.

It may be an error on my behalf but I couldn't work out from the docs what approach I should be taking here. If it's not a bug any guidance would be most welcome.

### System configuration

**Rails version**: `6.1.4`

**Ruby version**: `ruby 2.7.3p183`

**Gem version**:  ~~`2.34.0`~~ `2.35.0`

**Comment by boardfish** [comment]
I feel like I've tried to do something similar before in #954 - it seems that in both this instance and that one, our aim was to use the data on the component multiple times. In this example, you want to use the section heading in the list tag and div.

I haven't seen `def call; content; end` used before, and I believe it could be the source of the issue. I think `render_inline` handles content differently than the `render` helper in the view, at a lower level. I can't say I understand what it does differently fully, so perhaps one of the lead maintainers might have something to offer here. Still, I've been able to find a fix.

You'd benefit from giving `Section` its own template as I've done [here](https://github.com/peteryates/view-component-slot-demo/pull/1) and rendering it directly. Does that solve your original issue?

**Comment by peteryates** [comment]
In retrospect splitting the component out into separate files seems so obvious. Looking at it I'm confident your solution will work in the actual project - the demo one mirrored it in terms of structure but did away with all the distracting extra markup. I'd spent a few hours trying out different combinations of `render_inline`, `capture`, `safe_join` etc without any joy.

Thank you for your help, very much appreciated 👍🏽
