### ISSUE TITLE
Document that slots can be immediately rendered

### ISSUE THREAD

**Issue by willtcarey** [github/view_component#1028]
## Feature request
Would you all be open to a PR that added to the Slot documentation that they can be rendered in place (as opposed to being added to the internal buffer that can be rendered when the ViewComponent calls the slot)  with `<%= c.slot_name(foo, bar, baz) %>`?

I'm not sure if this is supposed to be a supported behavior so just wanted to check before PRing.

### Motivation

Currently all instances of using slots in the documentation show using slots by calling the slot helper and letting the component that you are calling the slot on decide where to render the slot in it's HTML.

(Notice here all slots are `<% %>` rather than `<%= %>`)
```erb
<%# index.html.erb %>
<%= render BlogComponent.new do |c| %>
  <% c.header(classes: "") do %>
    <%= link_to "My Site", root_path %>
  <% end %>

  <% c.post(title: "My blog post") do %>
    Really interesting stuff.
  <% end %>

  <% c.post(title: "Another post!") do %>
    Blog every day.
  <% end %>
<% end %>
```

I was developing a Menu builder component where I wanted to interleave item and separator slots together. In other words I wanted the slot rendering order to be determined by the call site of the component, not inside the component.

```ruby
class MenuComponent < ViewComponent::Base
  renders_many :items, MenuItemComponent
  renders_many :separators, MenuSeparatorComponent
end
```

```erb
<%# This is not possible with this syntax %>
<%= render MenuComponent.new do |c| %>
  <% c.item("First") %>
  <% c.separator %>
  <% c.item("Second") %>
  <% c.item("Third") %>
<% end %>
```

From reading the docs it didn't look like slots were able to be used this way. The rendering of the slots was always controlled by the component rather than the caller.

In my codebase I introduced `renders_child` to handle this case (which didn't wind up being necessary).

```ruby
class MenuComponent < ViewComponent::Base
  def self.renders_child(name, component)
    define_method(name) do |*args, **kwargs, &block|
      render component.new(*args, **kwargs), &block
    end
  end

  renders_child :item, MenuItemComponent
  renders_child :separators, MenuSeparatorComponent
end
```

I was looking to create an issue to check if this was good practice and if so if it should be upstreamed but while checking around to see if anyone had asked about it before I found out this behavior was actually able to be accomplished with slots and Github was using it in the Primer components [here](https://github.com/primer/view_components/blob/223aebfc97276a9489185366f96fa7dbee8dc5ec/app/components/primer/beta/avatar_stack.rb#L24).

Slots can be immediately rendered if you just prefix it with an `=` which causes `to_s` to be called on the slot and renders it. That meant my MenuComponent could be refactored to what it was initially using slots and the view just turned into this.
```erb
<%# This is not possible with this syntax %>
<%= render MenuComponent.new do |c| %>
  <%= c.item("First") %>
  <%= c.separator %>
  <%= c.item("Second") %>
  <%= c.item("Third") %>
<% end %>
```

So ultimately the question is is this intended behavior and should it be documented? Personally it does feel a bit weird that slots have these 2 alternate ways of being used with nothing at the API level to enforce that they are used one way or another. For instance if my component is expecting it's slots to be immediately rendered by using `=` in the ERB template and it's not even rendering the slots in it's own template then if the user calls the slot helper without the `=` then the slot is silently not rendered.

**Comment by joelhawksley** [comment]
@willtcarey this is an interesting use case. I can see why it would be nice to be able to build menus this way.

I will note that the Primer ViewComponents docs were incorrect. Thank you for pointing that out: https://github.com/primer/view_components/pull/731

Back to your original question about how to build this component, I think you could have an `Item` slot that accepts a `separator: true` argument.

More generally, I think we should avoid introducing this functionality to slots, at least in this form, as the API is already proving to be quite complex. 

I'm going to go ahead and close this issue ❤️

**Comment by willtcarey** [comment]
@joelhawksley Thanks for fixing up that docs inconsistency. That was the only place I had seen slots used like that so I was unsure if it was intended.

I agree that overloading the Slots API to also support this feature is a bit messy (and I'd say is out of the semantics of what a "slot" is) which is what I was mentioning at the end of the original comment. We've seen some good results from being able to build these builder type components still. In my original comment, I simplified the `MenuComponent` a bit. In reality there are actually 3 different components (regular items, separators, and section headers) that can all be rendered inside the Menu. Potentially that number would increase as we add new types of entries to our menus. That makes the solution of adding a new option for each of those different component types a little bit more difficult to add and scale up.

In its most raw form here's what we're trying to render.

```
<%= render MenuComponent.new do %>
  <%= render MenuItemComponent.new("First") %>
  <%= render MenuSeparatorComponent %>
  <%= render MenuItemSectionHeader.new("Other options") %>
  <%= render MenuItemComponent.new("Second") %>
  <%= render MenuItemComponent.new("Third") %>
<% end %>
```

What we would like is some sort of syntax sugar over the top of that so that component names aren't taking up the most real estate of the code and we can focus on what we're actually trying to render. Compare the above to the below which is where we would like to be with the API.

```
<%= render MenuComponent.new do |c| %>
  <%= c.item("First") %>
  <%= c.separator %>
  <%= c.section_header("Other options") %>
  <%= c.item("Second") %>
  <%= c.item("Third") %>
<% end %>
```

That's what my `renders_child` was attempting to do in the original comment. Would you be open to some more discussion on a new API to support this?

**Comment by joelhawksley** [comment]
@willtcarey hmm. I do see your point here. 

What's tricky for me to reconcile is that as they stand, the calling of slots is meant to be decoupled from the order they are rendered in. For example, I might call `c.footer` before `c.header`, but render the header first in the component's template.

My concern with this kind of functionality in the proposed API is that I think it would make the existing slots API confusing.

If you can think of an alternative API that clearly expresses the order-dependent nature of the calls, I'd be interested ❤️

**Comment by willtcarey** [comment]
@joelhawksley Yeah, I can see how using these side by side with slots could be confusing and it could be difficult to tell which calls to the components are slots and which are part of this new API.

I'm hesitant to recommend a new verb to encapsulate this feature but maybe that's what is needed. Let me know what you think of these ideas.

```ruby
class MenuComponent < ViewComponent::Base
  builds :items, MenuItemComponent
  builds :separators, MenuSeparatorComponent
end
```

```erb
<%= render MenuComponent.new do |c| %>
  <%= c.build :item, "First" %>
  <%= c.build :separator %>

  <%# These 2 APIs could be used interchangeably perhaps %>
  <%= c.build_section_header("Other options") %>
  <%= c.build_item("Second") %>
  <%= c.build_item("Third") %>
<% end %>
```

`build` has a lot of connotations from Rails, which could be a positive or negative depending how you look at it. People will bring their own ideas of what `build` should do because of their experience with Rails but at the same time they should know that `build` is used to new up objects. Although as I'm thinking through this maybe for that reason `create` would be better as it people will still have connotations from Rails but at least `create` gives the sense of creating something concrete and persistent.

Some other verbs that could work would be 
- `makes :item, MenuItemComponent`/`c.make_item("First")`
- `vends :item, MenuItemComponent`/`c.vend_item("First")`

What do you think of prefixing these components which are immediately rendered with a verb like one of the ones above? That should set it apart from regular slots as they will usually be nouns and not start with a verb.

**Comment by boardfish** [comment]
Not sure off the top of my head if lambda slots can render two top-level tags, so you might want to wrap the output for this in a `tag.div`, but how about declaring your slot as follows:

```rb
renders_many :items, ->(name:, with_separator: false) do
  render MenuItemComponent.new(name)
  render MenuSeparatorComponent.new if with_separator
end
```

**Comment by willtcarey** [comment]
My first approach did use lambda slots, but it was a goal of ours to only render one component per call to the slot so ours looked a bit more like this.

```ruby
renders_many :items, ->(name = nil, separator: nil, section_header: nil) do
  if name
    MenuItemComponent.new(name)
  elsif separator
    MenuSeparatorComponent.new
  elsif section_header
    MenuSectionHeaderComponent.new(section_header)
  end
end
```

```erb
<%= render MenuComponent.new do |c| %>
  <% c.item "First" %>
  <% c.item separator: true %>
  <% c.item section_header: "Other options" %>
<% end %>
```

Not perfect because you could make calls like `c.item "First", separator: true` and only the item would get rendered, not the separator.

This is also hiding things because often times it's not just the name you will want to pass the menu item, it's a link and maybe some other keyword options to control the display so those have to be sent along to component. So you have some keyword arguments that control which component is being rendered plus a hash of of options that may get sent along to the component which make it a bit confusing when you are reading at the call site.

That implementation is what led us to looking for something a bit cleaner to solve this and hopefully find an API that makes these clean to define in the component and use when calling the component.

**Comment by BlakeWilliams** [comment]
I thought about this use case a bit, I *think* this could be achievable via a passthrough slot? The problem I'm seeing is that we need an ordered array that can hold multiple types. Delegate slots don't allow that, lambda slots do allow it but it's not perfect (as mentioned in your last comment), and pass through slots allow *anything* to be passed through.

```ruby
renders_many :_items

def item(*args, &block)
  _item { MyItemComponent.new(*args, &block) }
end

def separator(*args, &block)
  _item { MySeparatorComponent.new(*args, &block) }
end

def section_header(*args, &block)
  _item { MySectionHeaderComponent.new(*args, &block) }
end
```

I haven't tested this, but it should work and provide a nice public API. You may have to call `render` on each of the components though.

Unrelated, but it would be awesome to have a view component playground site to easily test/share working examples.
