### ISSUE TITLE
Previews: Sample source code doesn't show if view used

### ISSUE THREAD

**Issue by AlecRust** [github/view_component#1029]
### Steps to reproduce

1. Set `config.view_component.show_previews_source = true`
2. Create a preview i.e.
    `test/components/previews/alert_preview.rb`
    ```ruby
    class AlertPreview < ViewComponent::Preview
      def info
        render Alert.new(type: :info, message: 'This is a info alert.')
      end
    end
    ```
3. Navigate to preview e.g. `/rails/view-components/alert/info`
4. See that sample source code is correctly shown under the component preview
5. Move the preview into an ERB file as-per [docs](https://github.com/github/view_component/blob/main/docs/guide/previews.md#preview-templates) i.e.
    `test/components/previews/alert_preview.rb`
    ```ruby
    class AlertPreview < ViewComponent::Preview
      def info; end
    end
    ```
    `test/components/previews/alert_preview/info.html.erb`
    ```erb
    <%= render Alert.new(type: :info, message: 'This is a info alert') %>
    ```
6. Navigate to preview e.g. `/rails/view-components/alert/info`
7. See that sample source code is **not** shown under the component preview

### Expected behavior

When I enable `config.view_component.show_previews_source` I expect the sample source code to show under the component preview regardless of how the preview files are structured.

### Actual behavior

**When a view file is used for the preview** if `config.view_component.show_previews_source = true` is set the sample source code is not shown under the component preview.

### Further details

**When a view file is used for the preview** this gem's `app/views/view_components/preview.html.erb` is not used to render the page, instead only the view file e.g. `test/components/previews/alert_preview/info.html.erb` is rendered that doesn't include the sample source code output: https://github.com/github/view_component/blob/fe121163f6d4d2962e6c3e16a3d83296f3ce4f77/app/views/view_components/preview.html.erb#L7-L9

I guess ideally the content of `test/components/previews/alert_preview/info.html.erb` would be loaded into `app/views/view_components/preview.html.erb` so that `app/views/view_components/preview.html.erb` can be relied upon as the template for all previews?

This issue also means I can't easily set the `<title>` of the "show preview" page as if I set this in `app/views/view_components/preview.html.erb` it will only apply if a view file isn't being used for the preview.

### System configuration
**Rails version**: 6.1.4

**Ruby version**: 2.7.4

**Gem version**: 2.36.0

**Comment by joelhawksley** [comment]
@johannesengl might you have some thoughts on this issue? I think we should have the source preview work in this case as well.

**Comment by edwinthinks** [comment]
👍 on this request. Personally, I see the benefit of being able to use the syntax highlighting of the ERB template when building out previews.

**Comment by johannesengl** [comment]
> @johannesengl might you have some thoughts on this issue? I think we should have the source preview work in this case as well.

@joelhawksley I just started a new job and don't have capacity to have a look at this for the next view weeks :(

**Comment by edwinthinks** [comment]
I'd be interested in taking a swing at this issue. I'am a little unsure about how you could reconcile a `render` statement inside the method versus the template that you provide.

I hope this isn't too out of scope but I sense using a template like shown above is more akin to how you'd use the ViewComponent library in projects (anecdotally speaking). That is you would more likely copy an ERB snippet rather than rendering it in a controller? Rather than supporting both cases, would it make sense to decide one pattern (in this case I feel like ERB makes sense)? 

@joelhawksley thoughts?

Also, congrats @johannesengl on your new job!

**Comment by joelhawksley** [comment]
@edwinthinks I'm wondering if we could use the same "layout" that includes the sample source regardless of whether the preview is rendered with a separate template or not. 

I'd be happy to pair on this if you'd like. Send me an email with some days/times that would work for you: joelhawksley@github.com

**Comment by edwinthinks** [comment]
Hey @joelhawksley! I think that might be able to work out. We'll probably need to make some choice about how we want to handle cases in which someone uses the in render in the method approach vs the template. Though I think there might be a really good sweet spot to handle them together. 

I think we can use the same 'layout' and maybe add some additional logic that will display the method + template or just the method depending on whether a template exists or not. Wondering if this is what you had in mind.

> I'd be happy to pair on this if you'd like. Send me an email with some days/times that would work for you: joelhawksley@github.com

I'll send you a message later today! Love to jump on a pairing call to brainstorm + code.

**Comment by joelhawksley** [comment]
Closed by https://github.com/github/view_component/pull/1047.
