### ISSUE TITLE
Deprecate Base#with_variant

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#1039]
### Problem

Per https://github.com/github/view_component/issues/1034 and other reports, the `with_variant` functionality meant for overriding the current Action Pack variant is regularly misused, often leading to confusion.

### Proposed solution

Given this perceived confusion and a lack of evidence for why the method should exist, deprecate the method in v3.0.0.

**Comment by joelhawksley** [comment]
See https://github.com/github/view_component/pull/429

**Comment by kieraneglin** [comment]
Late to the party, but is there an official replacement for `with_component`? I have a few ideas for how I'd refactor to support this change, but any official guidance would be appreciated

**Comment by denkozlovs** [comment]
I use this method to work with locales and switching website design

**Comment by joelhawksley** [comment]
@kieraneglin I'd love to see an example case you're trying to refactor.

@denkozlovs I believe @elia is looking into a solution for locales.

**Comment by elia** [comment]
@joelhawksley @denkozlovs [not working on it at the moment](https://github.com/github/view_component/issues/1348#issuecomment-1119494189), prioritizing #1367 for which I have a potential solution.
