### ISSUE TITLE
Include Translations support by default

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#1042]
## Feature request

Now that ViewComponent translations have been out for a while, I think we should include them by default. What do you think @elia?

### Motivation

We generally only leave features as opt-in until we're confident that they are stable.

**Comment by elia** [comment]
Sounds good, I'd just like to ensure that adding the global translation support provided by view_component-contrib still works

**Comment by joelhawksley** [comment]
@palkan might you be able to provide your perspective here given @elia's comment?

**Comment by palkan** [comment]
Seems working fine: https://github.com/palkan/view_component-contrib/commit/5b92196d1d796399a2c2f24e78e09cdaca29b1c1 🚢

**Comment by elia** [comment]
Great!
I'll prepare a PR shortly 👍

**Comment by elia** [comment]
@joelhawksley I have one locally that's half-backed, guess it's time to finish it! 😅 👍
