### ISSUE TITLE
view_component raises an error when a slot capture block returns nil (using Slim)

### ISSUE THREAD

**Issue by yjukaku** [github/view_component#1044]
### Steps to reproduce
Run the newly generated rails app here: https://github.com/yjukaku/view_component_nil_error and open localhost:3000/test

For reference, here's an example of code that triggers this issue:

```
# test_component.rb
class TestComponent < ViewComponent::Base
  renders_one :my_slot
end

# test_component.html.slim
| Hello!
= my_slot

# test.html.slim
= render TestComponent.new do |c|
  = c.my_slot do
    - something_that_returns_nil
```

### Expected behavior

The component should render, with no content in the slot.

### Actual behavior
An error is raised: `no implicit conversion of nil into String`

```
temple (0.8.2) lib/temple/utils.rb:38:in `escapeHTML'
temple (0.8.2) lib/temple/utils.rb:38:in `escape_html'
temple (0.8.2) lib/temple/utils.rb:21:in `escape_html_safe'
app/views/test/test.html.slim:4
actionview (6.1.4.1) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
actionview (6.1.4.1) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
actionview (6.1.4.1) lib/action_view/helpers/capture_helper.rb:45:in `capture'
view_component (2.38.0) lib/view_component/base.rb:247:in `content'
view_component (2.38.0) lib/view_component/slotable_v2.rb:222:in `get_slot'
view_component (2.38.0) lib/view_component/slotable_v2.rb:72:in `block in renders_one'
app/components/test_component.html.slim:3:in `call'
view_component (2.38.0) lib/view_component/compiler.rb:83:in `render_template_for'
view_component (2.38.0) lib/view_component/base.rb:102:in `render_in'
actionview (6.1.4.1) lib/action_view/helpers/rendering_helper.rb:43:in `render'
app/views/test/test.html.slim:1
actionview (6.1.4.1) lib/action_view/base.rb:247:in `public_send'
```

**Please note: The line number in the exception trace corresponding to `test.html.slim file` is off by one, for some reason, so keep that in mind while debugging.**

### System configuration
**Rails version**:
Rails 6.1.4.1

**Ruby version**:
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin19]

**Gem version**:
view_component-2.38.0

---

The example above is a bit contrived, but here's a more likely example:

```
# test.html.slim
= render TestComponent.new do |c|
  = c.my_slot
    - if user_signed_in?
       | Welcome!
```

In that case, the `if` condition evaluating to false implies a `nil` return.

**Comment by yjukaku** [comment]
After digging in to the VC code a bit, I think forcing `ViewComponent::SlotV2` to call `to_s` on whatever is returned from the capture block would solve this issue. 

I would guess the issue is that https://github.com/github/view_component/blob/main/lib/view_component/slot_v2.rb#L62 is returning `nil`. Calling `.to_s` on that return value should work to solve our issue, IMO.

**Comment by joelhawksley** [comment]
@yjukaku that sounds like a good idea. Would you like to open a PR?

**Comment by yjukaku** [comment]
@joelhawksley , yep! Here you go: https://github.com/github/view_component/pull/1046
