### ISSUE TITLE
with_collection_parameter inherit

### ISSUE THREAD

**Issue by xkraty** [github/view_component#1054]
Hello!

### Steps to reproduce

```ruby
module Datalist
  class Base < ApplicationComponent
    with_collection_parameter :record
    attr_accessor :record

    def initialize(record:)
      self.record = record
    end
  end
end

module Datalist
  class User < ::Datalist::Base
  end
end
```

### Expected behavior

By running
```ruby
= render ::Datalist::User.with_collection(@users)
```
I expect `DatalistUser` to inherit `with_collection_parameter :record` and I get this error
```ruby
The initializer for Datalist::User does not accept the parameter `user`, which is required in order to render it as a collection.
```

### Actual behavior

But I do need to specify it again
```ruby
module Datalist
  class User < ::Datalist::Base
    with_collection_parameter :record
  end
end
```

So I'm guessing the extended class override the collection parameter with the default one and I'm not sure is intended.
Thanks
Chris

### System configuration
**Rails version**: Rails 6.1.4.1

**Ruby version**: 2.7.4

**Gem version**: 2.38.0

**Comment by joelhawksley** [comment]
@xkraty thanks for the report! Would you be up for writing a PR to fix this?

**Comment by xkraty** [comment]
@joelhawksley I'm surely going to try to find out!

**Comment by xkraty** [comment]
Hi @joelhawksley I've been working on it with my mate @wdrexler on it but we got some segmentation fault on test on ruby 3 which I'm not sure we can figure out what's wrong.

We'll try to dig a little bit more but if you have any tip are welcome!
