### ISSUE TITLE
Add --parent option to component generator

### ISSUE THREAD

**Issue by Spone** [github/view_component#1067]
## Feature request

The `ComponentGenerator` implements a [`#parent_class`](https://github.com/github/view_component/blob/8ffe1d96ef52995ba0a12efff48e33b02ac5279a/lib/rails/generators/component/component_generator.rb#L34-L36) private method that picks the right parent class (whether `ApplicationComponent` is defined or not).

I'd like to be able to pass `--parent CustomBaseComponent`, so the generated component looks like that:

```rb
class ExampleComponent < CustomBaseComponent
  # ...
end
```

### Motivation

A similar `--parent` option [exists in Rails](https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/activerecord/lib/rails/generators/active_record/model/model_generator.rb#L14).

It would also be useful when implementing our component generator in [view_component-form](https://github.com/pantographe/view_component-form) :)

**Comment by joelhawksley** [comment]
Sounds good to me! I assume we'd also add a global config option as well?
