### ISSUE TITLE
Slot content not casted to string

### ISSUE THREAD

**Issue by edouard-per-angusta** [github/view_component#1128]
### Steps to reproduce

Create a `ListComponent`:

```ruby
class ListComponent < ViewComponent::Base
  renders_many :items

  def call
    tag.ul do
      items.each do |item|
        concat(tag.li(item))
      end
    end
  end
end
```

Call it with the following values:

```ruby
render ListComponent.new do |list|
  list.item { "1" }
  list.item { 2 }
  list.item { nil }
end
```

### Expected behavior

It should render:

```html
<ul><li>1</li><li>2</li><li></li></ul>
```

(passing an `Integer` or whatever works with `content` so I expect it to work in methods)

### Actual behavior

It raises an error:

```
"undefined method `empty?' for nil:NilClass"
```

due to second and third items.

### System configuration
**Rails version**: 5.2.6

**Ruby version**: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin20]

**Gem version**: 2.30.0

#### Notes

Of course we could do:

```ruby
render ListComponent.new do |list|
  list.item { "1"}
  list.item { 2.to_s }
  list.item { nil.to_s }
end
```

May be it is what's expected (like we should cast values, it's not the component business). But if that's really an issue please confirm me and I'll try to make a fix 👍

**Comment by boardfish** [comment]
I think there's potentially cause for it to be considered an issue. Let's say that for argument's sake we were doing this in ERB:

```html.erb
<%= render ListComponent.new do |list| %>
  <% list.item do %>
    <%= "1" %>
  <% end %> 
  <% list.item do %>
    <%= 2 %>
  <% end %> 
  <% list.item do %>
    <%= nil %>
  <% end %> 
end
```

The `<%=` tags would capture the return value as a string and concatenate it to the output buffer, so the above situation wouldn't cause a problem.

That'd be equivalent, in a way, to taking the return value of the block and casting it to a string before passing it to the block. If this really is the case, then I guess it makes rendering components somewhat inconsistent between situations (rendering to string in a controller, say, and rendering the component in the view).

**Comment by cpjmcquillan** [comment]
This issue was discussed in [DfE-Digital/govuk-components](https://github.com/DFE-Digital/govuk-components/issues/249) too a little while ago.

**Comment by boardfish** [comment]
> This is intended behaviour from ActionView (as #capture is only meant to deal with content coming from a templating library like ERB, which are guaranteed to be strings, not blocks returning arbitrary values). view_component has decided not to work around it: github/view_component#849

@edouard-per-angusta I think this tidbit from the issue @cpjmcquillan linked probably describes why this is the way it is. If we think about ViewComponent as an extension of ActionView (which it started out as), then to change this behavior would make ViewComponent inconsistent with ActionView, so I'm not sure we should make a change here. It's good that we've had this discussion, though, so that if folks encounter the same thing, they can understand why it's the case.

**Comment by edouard-per-angusta** [comment]
Thank you @boardfish for you answer. Indeed it makes sense to follow Rails behavior.
