### ISSUE TITLE
ViewComponent logo hard to read in dark mode

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#1134]
## Feature request

@dylanatsmith do you think we could come up with a text color that passes contrast checks in both dark and light modes on GitHub?

### Motivation

It's hard to read the ViewComponent text in the README in dark mode:

<img width="737" alt="Screen Shot 2021-11-12 at 2 40 29 PM" src="https://user-images.githubusercontent.com/1940294/141537966-17d44f98-2416-4499-a3b3-cf27addccb49.png">

**Comment by dylanatsmith** [comment]
Oof, good catch.

I know we discussed single-colour logo options (e.g. all red) and initially ruled it out because we liked the red + black and red + white combos. But that would solve for this and probably look better than red + medium grey or whatever.

From the original colour combination doc:

![image](https://user-images.githubusercontent.com/6905903/141973206-92cf4c43-d39d-46b0-841a-c3ecf96293fd.png)

**Comment by boardfish** [comment]
I'm a sucker for red background and white text, but white background, red logo, black text is a close second.

**Comment by joelhawksley** [comment]
@dylanatsmith I think the red background, white text option looks sharp. Would you mind PR'ing an update to update the README logo to use that look?

**Comment by dylanatsmith** [comment]
Here's another potential option: [one SVG with a media query inside of it](https://p-76F1Jq.t4.n0.cdn.getcloudapp.com/items/NQu7WkE1/2d0bfcd9-916a-43ad-bb05-bf694fd26ce7.gif) that dynamically changes text colour depending on OS settings.

The downside of this is that there's no guarantee the OS settings are in sync with someone's GitHub user preference.

**Comment by Spone** [comment]
> The downside of this is that there's no guarantee the OS settings are in sync with someone's GitHub user preference.

That would be awesome to encapsulate the logic in the SVG :)

Related community request: https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981 (without a working solution yet)
