### ISSUE TITLE
Docs: add a link to the Github repo

### ISSUE THREAD

**Issue by Spone** [github/view_component#1145]
## Feature request

Add a prominent link to the Github repo, on every page of the docs site.

### Motivation

I was browsing around https://viewcomponent.org and (unless I'm very tired :smile: ) I don't see an easy-to-find link to https://github.com/github/view_component

Maybe a "Github" link with special styling at the bottom of the nav, similar to this (from [Primer](https://primer.style/view-components/)):

![image](https://user-images.githubusercontent.com/38524/142273863-12f22b87-0cff-45e9-8ce9-6ce2a73775ea.png)

**Comment by Spone** [comment]
It could look like this:

![image](https://user-images.githubusercontent.com/38524/142284137-3814c357-0ecb-4e7c-935e-3032840b3158.png)

What do you think @joelhawksley?

**Comment by joelhawksley** [comment]
@Spone I think right at the top sounds good to me, especially given that ViewComponent _is_ a repository.
