### ISSUE TITLE
Versioned documentation

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#1151]
## Feature request

As a developer reading the ViewComponent documentation, it is unclear whether there are unreleased features in the docs.

### Motivation

We've seen some issues here and there of folks being mislead by our documentation when unreleased changes were described in the docs. 

### Proposed solution

I could see us solving this a couple ways. We could only publish the docs when a release is cut, we could version the docs (see https://glebbahmutov.com/blog/versioned-doc-pages/, or perhaps we could start with a disclaimer that the docs are for the `main` branch.

**Comment by Spone** [comment]
I think it makes sense to only update the docs when a new version is released.

Given that there is no major version release yet (we're still in `v0.*.*`), I would say it's not necessary to publish versioned docs.

The disclaimer could go to the top of each markdown file in the docs folder, as a comment, in case people read the docs there, but not on the docs website itself.

**Comment by joelhawksley** [comment]
> I think it makes sense to only update the docs when a new version is released.

I think that's a good place to start. Let's do that.
