### ISSUE TITLE
Slim renders passthrough slots mutiple times

### ISSUE THREAD

**Issue by boardfish** [github/view_component#1159]
### Discussed in https://github.com/github/view_component/discussions/1156

<div type='discussions-op-text'>

<sup>Originally posted by **coder2000** November 20, 2021</sup>
I am trying to use multiple `renders_one` slots but the first one always renders with the second. Is that normal?</div>

It looks like what's happening is that the declared slot's output is being added to the buffer a second time for the second slot. This appears to be a ~~HAML~~Slim-specific issue.

~~I've noticed there was a [relevant change](https://github.com/github/view_component/blob/4889318bdf4586bf102f40c66d8bbb2c988e8898/docs/CHANGELOG.md#2290) a few versions back, so I've asked @coder2000 which version they're on. @BlakeWilliams, would you happen to know any more about this?~~

**Comment by boardfish** [comment]
@coder2000 has stated on the original discussion that they're on the latest version as of right now, v2.44.0.

**Comment by Spone** [comment]
I tried to reproduce the issue, without success.

## Component

```rb
# app/components/example_component.rb
class ExampleComponent < ApplicationComponent
  renders_one :button
  renders_one :header
end
```

```slim
/ app/components/example_component/example_component.html.slim
div(class="example")
  h1 ExampleComponent
  .example-button= button
  .example-header= header
```

## Usage in view

```slim
/ app/views/pages/index.html.slim
= render(ExampleComponent.new) do |c|
  - c.button do
    p BUTTON
  - c.header do
    p HEADER
```

## Output

(formatted added for readability)

```html
<div class="example">
  <h1>ExampleComponent</h1>
  <div class="example-button"><p>BUTTON</p></div>
  <div class="example-header"><p>HEADER</p></div>
</div>
```

**Comment by coder2000** [comment]
Try with a renders_many as well. It might be a combination.

**Comment by Spone** [comment]
> Try with a renders_many as well. It might be a combination.

Still no issue when adding `renders_many`. 🤔

**Comment by coder2000** [comment]
Weird. Is it possible to do a discord call with a live share to work it out?

**Comment by joelhawksley** [comment]
@boardfish can you provide your steps for reproduction request here? I can't seem to find it think a sample Rails application is the right move here.

**Comment by boardfish** [comment]
Sure! @coder2000, could you pull together a sample Rails app for us?

1. Use `rails new --minimal view_component-1159` in the console. You might also need to provide an argument to change the template engine to Slim, so use `rails new --help` first to figure that part out. (I'd tell you, but I'm posting from my phone 😅)
2. `bundle add view_component`, then change the added line in the Gemfile to match `gem 'view_component', require: 'view_component/engine'`
3. Implement and render those components in the sample app. If you can put the code you're using straight in, even better. It should replicate your original issue.
4. Share the app with us by creating a public GitHub repo and posting the link here.

**Comment by coder2000** [comment]
So I built this example app, and it doesn't have the issue I described either. https://github.com/coder2000/view_component-1159

**Comment by coder2000** [comment]
Which makes it all the weirder

**Comment by joelhawksley** [comment]
@boardfish thanks! Now that I think about it, It might be worth adding those directions to `CONTRIBUTING.md` if you don't mind ❤️

**Comment by boardfish** [comment]
@joelhawksley I've thought about that too, but there are a couple of changes I'd make to improve the experience there. First off, I think we could provide a repo template for this purpose, and automate keeping it up to date so that all the setup is just a click away. We could probably leverage Codespaces to help with that.

Second, I'm waiting to merge a change into `bundler` that'll let you specify a `require` path, so that if folks do need to build from scratch to more easily add support for other libraries like Hotwire and Tailwind, they can `require: 'view_component/engine'` without having to update their Gemfile to do so. So the optimal solution might be a couple of hops away, but this is definitely a good thing for me to drop in before we consider those.

**Comment by coder2000** [comment]
@boardfish I really don't know what's going on now because I have another instance of the content from a renders_many appearing in each subsequent item. If that makes any sense.

**Comment by boardfish** [comment]
@coder2000 Are you happy with that as a resolution? I'll try replicating it myself once again for posterity, but the way things are going, I don't feel like there's enough evidence to categorize this and fix it.

**Comment by boardfish** [comment]
Just failed to replicate this with the code you provided in a codespace. `Page::Menu::Link` was minimally implemented to output the string `test`.

```html
<body>
    <div class="mt-3 relative" x-data="{menuOpen: false}">
        <div>
            <button @click="menuOpen = !menuOpen" aria-expanded="false" aria-haspopup="true"
                class="rounded-full flex items-center text-gray-400 hover:text-gray-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-zeiss-500"
                type="button"><span class="sr-only">Open options</span>
                <div class="h-8 w-8 rounded-full"></div>
            </button></div>
        <div @click.outside="menuOpen = false" aria-orientation="vertical"
            class="origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none"
            role="menu" tabindex="-1" x-cloak="" x-show="menuOpen" x-transition:enter="transition ease-out duration-100"
            x-transition:enter-end="transform opacity-100 scale-100"
            x-transition:enter-start="transform opacity-0 scale-95" x-transition:leave="transition ease-in duration-75"
            x-transition:leave-end="transform opacity-0 scale-95"
            x-transition:leave-start="transform opacity-100 scale-100">
            <div class="px-4 py-3 border-b border-gray-200">
                <p class="text-sm">Signed in as</p>
                <p class="text-sm font-medium text-gray-900 truncate">Simon</p>
            </div>
            <div class="py-1" role="none">testtesttesttest</div>
        </div>
    </div>


</body>
```

I think that's good enough grounds to close this, but do let me know if there's anything I can do to help you get to the bottom of this.

**Comment by coder2000** [comment]
Thinking now it may have been modifications I made to the slim gem to support another feature.
