### ISSUE TITLE
Create a separate development and production compiler mode

### ISSUE THREAD

**Issue by BlakeWilliams** [github/view_component#1177]
Context taken from: https://github.com/github/view_component/pull/1161#discussion_r755484984

> Similar to your env idea, I'm wondering if we need to go a level higher and think about introducing different modes to the compiler. A consistent compiler, for dev + test, and a fast compiler, for production. I don't think that idea should block this PR, but we do want to keep the performance benefits we see in production while also making dev+test consistent in threaded environments.

The idea is that we could have a development mode for the compiler, which adds the `Monitor.synchronize` call in the generated render methods to prevent the compiler from overwriting the call method while rendering. https://github.com/github/view_component/pull/1161#discussion_r755484984 got us very close to thread safety, but without the extra sync we're still likely susceptible to race conditions in test/dev (just much less so).

The reason behind two different modes is that production code doesn't need the synchronization since it's compiled at boot time and will not have a chance to run into issues due to a race.

**Comment by horiaradu** [comment]
Is this urgent? If not, I would like the opportunity to take a crack at it :)

**Comment by BlakeWilliams** [comment]
@horiaradu No urgency at all, feel free to assign yourself and take it on. 🙂

**Comment by horiaradu** [comment]
I can't assign myself (I think because of rights), but maybe u can? Otherwise, it's not an issue, I have the tab open :)

**Comment by BlakeWilliams** [comment]
No problem, I went ahead and assigned it to you so nobody else picks it up.
