### ISSUE TITLE
Generator failing for rails 7.0.0.rc1 + tailwind

### ISSUE THREAD

**Issue by juan-apa** [github/view_component#1190]
### Steps to reproduce
1. generate new rails 7.0.0.rc1 app using:
```bash
rails new example_app --database=postgresql --skip-javascript --css tailwind
```
2. Add ViewComponent gem
3. Create a new ViewComponent by running:
```bash
bin/rails generate component Example title
```
It displays the following error message:
![image](https://user-images.githubusercontent.com/9309458/145458202-048eea9e-f9d0-4384-a0dc-eaf0509f7220.png)

### Expected behavior
It should generate an `example_component.html.erb` file along with the `example_component.rb`.

### Actual behavior
It does not generate an `example_component.html.erb` file.

### System configuration
**Rails version**:  `7.0.0.rc1`

**Ruby version**: `3.0.2`

**Gem version**: `~> 2.46`

**Comment by Spone** [comment]
Hi @juan-apa! We're currently working on Tailwind support here: https://github.com/github/view_component/pull/1098

**Comment by Sarhm2021** [comment]
Good

**Comment by juan-apa** [comment]
Thanks, I was ready to open a new PR including this feature if it was not implemented already! Thanks for the quick response.
