### ISSUE TITLE
Error: uninitialized constant ViewComponent::Base

### ISSUE THREAD

**Issue by pboling** [github/view_component#1195]
### Steps to reproduce

1. `git clone -b view_component https://github.com/pboling/sr_mini.git`
2. `cd sr_mini`
3. `bin/rails generate component Thing name`

See the error!

```
[WARNING] Could not load generator "rails/generators/component/component_generator". Error: uninitialized constant ViewComponent::Base
```

### Expected behavior

Generator should run.

### Actual behavior

<img width="1242" alt="Screen Shot 2021-12-11 at 5 47 30 AM" src="https://user-images.githubusercontent.com/19505/145651341-c23e8a78-b3f2-49f7-9e7b-ed277a580c8b.png">

### System configuration
**Rails version**: 6.1.4.1

**Ruby version**: 3.0.2

**Gem version**: 3.2.32

**Bundler version**: 2.2.32

**Comment by joelhawksley** [comment]
@Spone might you be able to look into this generator-related issue?

**Comment by Spone** [comment]
Hi @pboling! Thanks for reporting this. I don't see `view_component` in the [gemfile](https://github.com/pboling/sr_mini/blob/main/application.rb#L3-L11). Have you tried adding it?

**Comment by pboling** [comment]
@Spone Sorry, I should have called it out more clearly.  You need to be on the branch `view_component`.  Cloning a repo to a specific branch is an uncommon pattern, so I should have made that clear.

`git clone -b view_component https://github.com/pboling/sr_mini.git` # <= checks out the `view_component` branch after cloning!

As you can see from the screenshot in OP the backtrace is from withing the view_component source... so yes it is loaded!

**Comment by pboling** [comment]
I have forked the repo, and am taking a stab at fixing this myself.  It has been a while since I've worked with engines, but I do not see any `require "view_component/base"` anywhere in the code.  Perhaps autoloading is expected to find it...

**Comment by pboling** [comment]
Oh, yep there it is:
```
module ViewComponent
  extend ActiveSupport::Autoload

  autoload :Base
```

So, somehow this `autoload` isn't working with a barebones Rails app, current version, or perhaps the file with the autoload statements isn't being loaded.  Investigating.

**Comment by pboling** [comment]
It is the second one.  The file with the autoload statements is itself not being loaded.

**Comment by pboling** [comment]
It appears from the backtrace that railties' `rails/command/behavior.rb:44` jumps right into view component's generator without loading any of the gem first...
```
$ bin/rails generate component Thing name
[WARNING] Could not load generator "rails/generators/component/component_generator". Error: uninitialized constant ViewComponent::Base
Did you mean?  Base64.
/Users/pboling/src/uds/view_component/lib/rails/generators/component/component_generator.rb:16:in `<class:ComponentGenerator>'
/Users/pboling/src/uds/view_component/lib/rails/generators/component/component_generator.rb:7:in `<module:Generators>'
/Users/pboling/src/uds/view_component/lib/rails/generators/component/component_generator.rb:6:in `<module:Rails>'
/Users/pboling/src/uds/view_component/lib/rails/generators/component/component_generator.rb:5:in `<top (required)>'
/Users/pboling/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/command/behavior.rb:44:in `block (2 levels) in lookup'
/Users/pboling/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/command/behavior.rb:40:in `each'
/Users/pboling/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/command/behavior.rb:40:in `block in lookup'
/Users/pboling/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/command/behavior.rb:39:in `each'
/Users/pboling/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/command/behavior.rb:39:in `lookup'
/Users/pboling/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/generators.rb:257:in `find_by_namespace'
/Users/pboling/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/generators.rb:273:in `invoke'
/Users/pboling/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/commands/generate/generate_command.rb:26:in `perform'
/Users/pboling/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
/Users/pboling/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
/Users/pboling/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
/Users/pboling/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/command/base.rb:69:in `perform'
/Users/pboling/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/command.rb:48:in `invoke'
/Users/pboling/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/commands.rb:18:in `<top (required)>'
```

**Comment by pboling** [comment]
OK, I have it working now, in my example app.  The issue was I had not setup bootsnap, and had not run `Bundler.require`...

I created this example app in an attempt to replicate the error I am seeing in my live production app.  I did replicate the error, exactly, but my production app does have bootsnap setup, and it running `Bundler.require`... so now I am stumped.

**Comment by pboling** [comment]
OK, figured it out!  When `view_component` is added as a run-time dependency of a gem which is then included in a Rails app the gem must do `require "view_component"` explicitly.

Even though the `view_component` gem is installed with `bundle install` when it is a dependency of a gem, it is not loaded by `Bundler.require`, as gem's runtime dependencies are not automatically loaded.  Gems have to load everything explicitly.  I knew this, and it is correct behavior, but I've just moved back into working on an app that has been split into parts as internal (same file tree) gem-engines, and this setup obfuscates the fact that you still have to treat them as gems.

**Comment by Spone** [comment]
Thanks a lot for taking the time to investigate this @pboling, and for posting the results here! I may be useful to others :)
