### ISSUE TITLE
Vale linter exceptions

### ISSUE THREAD

**Issue by boardfish** [github/view_component#1213]
Noticed that in `CONTRIBUTING.md`, this phrase appears:

> 1. Add an entry to the top of `docs/CHANGELOG.md` for your changes, no matter how small **they're**. We want to recognise your contribution!

Was pretty amusing to see, but it might also be a touch confusing for folks whose first language isn't English. Is there a way to add an exception to Vale for this and any other instances where Vale may have mistakenly enforced the wrong syntax?

It might also just be easier to change the phrasing to:

> 1. Add an entry to the top of `docs/CHANGELOG.md` for your changes. No matter how small they may be, we want to recognise your contribution!

**Comment by Spone** [comment]
In case we want to update the [rule](https://github.com/github/view_component/blob/main/.github/styles/Microsoft/Contractions.yml#L22), we can use a regex with a negative lookahead, to ensure the matching `they are` is not at the end of a sentence.

```diff
- they are: they're
+ 'they are(?!\.)': they're
```

**Comment by boardfish** [comment]
I can do so - I trust regex is supported in keys?

**Comment by boardfish** [comment]
Made the change to the rule upstream. I'll reflect it within this repo too.
