### ISSUE TITLE
Add --sidecar as config option

### ISSUE THREAD

**Issue by t2** [github/view_component#1216]
Hello,

The `--sidecar` flag is very helpful for organizing our View Components. I would like to make this option a config variable so that we can make it a standard in our codebase without having to remember the `--sidebar`. How does this sound for a feature enhancement?

`config.view_component.sidecar_enabled = true`

**Comment by joelhawksley** [comment]
@t2 I generally think that all generator options should allow for defaults to be set like that 👍🏻 

@Spone generally reviews generator-related things so perhaps he can chime in here?

**Comment by g13ydson** [comment]
I created this PR #1218  that possibly solves this issue

**Comment by t2** [comment]
@g13ydson you're right, this is what I was aiming for. Any movement on that merge?

**Comment by Spone** [comment]
Let's keep the issue open until we merge the PR.
