### ISSUE TITLE
[Doc]Add namespace generator example

### ISSUE THREAD

**Issue by kenzo-tanaka** [github/view_component#1220]
Hi👋
First of all thank you for an awesome gem!

## Feature request
I thought it would be helpful for users to if there was an example of a command to create a component under a namespace in the [Generators page](https://viewcomponent.org/guide/generators.html) of the documentation.

Like this:

```
bin/rails generate component admin/Example title content
```

Please close if you think that doesn't need to explain🙏

### Motivation

Improving documentation.

**Comment by Spone** [comment]
Hi @kenzo-tanaka thanks for the suggestion! What do you think of #1226?

**Comment by kenzo-tanaka** [comment]
Hi @Spone !
Thanks! It's perfect😊
