### ISSUE TITLE
CI tests are failing on test runs in Rails 6.1.3.1 & Ruby 3

### ISSUE THREAD

**Issue by edwinthinks** [github/view_component#1223]
### Steps to reproduce
1. Run the CI suite on any changes after the release of Ruby 3.1.0
2. You should see failures on matrix build `test(6.1.3.1, 3)` due to this error when trying to run the tests`/home/runner/work/view_component/view_component/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `require': cannot load such file -- net/smtp (LoadError)`

This is related to the issue described on the stakeoverflow post - https://stackoverflow.com/questions/70500220/rails-7-ruby-3-1-loaderror-cannot-load-such-file-net-smtp

This might get fixed when https://github.com/mikel/mail/pull/1439 is merged in. But I'am not 100% sure.

### Expected behavior
The test suite should run without running into a dependency error as shown above. Moreover, I would expect `test(6.1.3.1, 3)` to be testing against ruby `3` not `3.1.0`

### Actual behavior
Tests fail to run on `test(6.1.3.1, 3)` 

### System configuration
**Rails version**:
Rails 6.1.3.1

**Ruby version**:
3.1.0

**Gem version**:
main

**Comment by edwinthinks** [comment]
Adding these gems specifically in the Gemfile seems to bypass this issue as described in https://github.com/mikel/mail/pull/1439#issuecomment-1002792758

Adding gems like this seems to me not a great long-term solution for this problem imo.

**Comment by cpjmcquillan** [comment]
I think this might be to do with the GitHub Actions runner and how `yaml` parses strings/floats/integers.

I think `3.0` gets parsed as `3` so it uses `3.1`. Changing the ruby versions to be defined by strings should fix this, _I think_.

**Comment by g13ydson** [comment]
I'm working on an update #1218  and had to set the Ruby version to 3.0.3.  Maybe it will solve when it merges
