### ISSUE TITLE
ViewComponent::Preview.all returns empty under certain circumstances

### ISSUE THREAD

**Issue by muriloime** [github/view_component#1252]
Hi, I'm  using lookbook and it often breaks because `ViewComponent::Preview.all` returns `[]` after a component.rb file changes. In order to fix it it  is necessary to avoid using descendent_tracker (i.e. remove the if from [this line](https://github.com/github/view_component/blob/8e027ee6e2d8bf47233be165bd02ee1d48b3575e/lib/view_component/preview.rb#L33) ). 

Do you guys think it is too expensive to run load_previews on every request to all ? because if it is not I can make a PR with this change. Otherwise I cannot help since the issue seems to be with `ActiveSupport::DescendantTracker`
 
### Steps to reproduce
Change .rb file when using lookbook

### Expected behavior
`ViewComponent::Preview.all` to return correct value. 

### Actual behavior
`ViewComponent::Preview.all` return `[]` 

### System configuration
**Rails version**:
7.0.1

**Ruby version**:
3.0.1

**Gem version**:
2.47, 2.48

**Comment by boardfish** [comment]
Hey @muriloime, thanks for raising this with us! I'm afraid I don't have a lot of context around the implications of that change, but I can offer you some steps to see for yourself whether it would be too expensive. If you clone this repository and use `script/replicate-bug`, you'll be able to make changes to your local copy of ViewComponent, install Lookbook into the generated Rails app, and see if it makes a difference. I'll try the same, but I haven't yet used Lookbook. Hope that's helpful to you!

**Comment by muriloime** [comment]
Hi @allmarkedup , yes, I see it inside lookbook indeed, and I am still seeing problems with this too. I will open an issue inside lookbook then. @boardfish should I close it here? 

thanks
