### ISSUE TITLE
Builds failing on `main`: translations missing in `TranslatableTest` on Ruby 3

### ISSUE THREAD

**Issue by boardfish** [github/view_component#1264]
Appears to have started from [this build](https://github.com/github/view_component/runs/5051327997?check_suite_focus=true) and is [still present](https://github.com/github/view_component/runs/5114074589?check_suite_focus=true).

This only seems to be happening on Ruby 3.

I'm going to have a look into this, but if anyone's got any findings of their own to get `main` green again, they're very welcome.

**Comment by Spone** [comment]
FYI: I also spent some time on this earlier this month, without finding a solution :-/

**Comment by boardfish** [comment]
It seems to have something to do with [this commit](https://github.com/ruby-i18n/i18n/commit/cbca32e3fa0f94306c079ab61df4436aab05a2bd) to `i18n`. What's happening is that whenever `store_translations` is getting called, it's getting called with `skip_symbolize_keys: true`. So I'm a step closer to understanding this - I still need to figure out what's responsible for those options getting passed. @elia, would you happen to know anything else about this?
