### ISSUE TITLE
Predicate methods for slots

### ISSUE THREAD

**Issue by Spone** [github/view_component#1275]
## Feature request

I would like to suggest adding predicate methods for slots.

For instance:

```rb
class BlogComponent < ViewComponent::Base
  renders_one :header
  renders_many :posts
end
```

```erb
<%# blog_component.html.erb %>
<% if header? %>
  <h1><%= header %></h1>
<% end %>

<% if posts? %>
  <ol>
    <% posts.each do |post| %>
      <li><%= post %></li>
    <% end %>
  </ol>
<% end %>
```

They could also be used in `#render?`:

```rb
class BlogComponent < ViewComponent::Base
  renders_one :header
  renders_many :posts

  def render?
    header? || posts?
  end
end
```

### Motivation

Most of the time, when slots are optional, I find myself testing their presence with `#present?` because I want to render a wrapper element conditionally. I think we could add some syntactic sugar for this, similar to the `#{attribute}?` method [provided by ActiveRecord](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/attribute_methods/query.rb).

**Comment by BlakeWilliams** [comment]
I'm a fan of this idea! Would you like to take this on and open a PR for this feature?

**Comment by Spone** [comment]
Yes I will!

**Comment by Spone** [comment]
Here is the draft PR: https://github.com/github/view_component/pull/1281, please let me know what you think!
