### ISSUE TITLE
Namespaced components not working as expected

### ISSUE THREAD

**Issue by AlecRust** [github/view_component#1283]
### Background

We've been using ViewComponent since early days and it's been great. Since we have so many components, each with three files (`.rb`, `.html.erb` and `.css`) each component resides in its own folder to help organisation.

Also full disclosure, we don't use the `Component` suffix i.e. we use `Alert.new` to save typing.

We now want to create two _types_ of view components, matching what you do at GitHub i.e. as [documented here](https://viewcomponent.org/viewcomponents-in-practice.html#the-two-types-of-viewcomponents-we-write).

**In order to create the mentioned "App-specific ViewComponents" we need namespaced components. But the [documented generator](https://viewcomponent.org/guide/generators.html#generating-namespaced-components) doesn't produce a renderable component.**

This looks to be due to our folder structure of having each component in a folder (which is quite nice). **Is there a way for namespaced components to work in harmony with our normal components, keeping the same folder structure?**

I've detailed the steps below with a repo, many thanks for your time!

### Steps to reproduce
1. Create new Rails app
2. Add a couple view components using folder structure `app/components/component_name/component_name.rb`
  In order for this to work the following must be added to `config/application.rb`:

    ```ruby
    config.autoload_paths += Dir[config.root.join('app/components/*')]
    ```
3. Run [namespaced component generator](https://viewcomponent.org/guide/generators.html#generating-namespaced-components) i.e. `bin/rails generate component Sections::Example title content`
2. Restart the server and try to render the component in a view i.e. `<%= render Sections::ExampleComponent.new %>`
3. Receive error `uninitialized constant #<Class:0x0000000122a13c68>::Sections`

Here's a repo reproducing the issue: https://github.com/AlecRust/namespaced-components-issue

### Expected behavior
I expected to be able to create namespaced components, despite each of our existing components residing in a folder. I assume since the namespaced components generator creates a folder (unlike the standard generator) this is what's causing the issue.

### Actual behavior
Namespaced components don't seem to work. Normal components seem fine.

### System configuration
**Rails version**: Tested on 6.1 and 7.0

**Ruby version**: Tested on 2.7 and 3.1

**Gem version**: 2.49.0

### Related issues

- https://github.com/github/view_component/issues/401
- https://github.com/github/view_component/issues/670

**Comment by boardfish** [comment]
Hi @AlecRust! Thanks for opening this issue.

I find this use case interesting - it makes sense that the Ruby file should be at the same level of all sidecar assets. I do wonder if this should be considered as a feature request.

However, I feel like without coercing Zeitwerk in some way, this could be quite a difficult thing to achieve. `autoload_paths` only adds to the list of directories from which components are loaded - without changes to Zeitwerk's configuration, they won't be autoloader to your liking. Zeitwerk, by default, loads classes like this:


```
app/components/component_name/component_name.rb
```

gets translated to:

```ruby
ComponentName::ComponentName
```

based on the file path. So `app/components/component_name/component_name.rb` should contain the constant `ComponentName::ComponentName` in order for it to be successfully loaded.

I've previously tampered with Zeitwerk's loading strategy using an initializer that calls this:

```ruby
# frozen_string_literal: true

Rails.autoloaders.each do |autoloader|
  autoloader.inflector.inflect(
    'commands' => 'Command'
  )
end
```

This allowed for `app/commands/thing_command.rb` to point to `Command::ThingCommand` without the need for a parent `command` directory to define the namespace. You may be able to use this to reach the solution you'd like.

**Comment by AlecRust** [comment]
Thanks for your reply @boardfish I wasn't aware of the default Zeitwerk behaviour here.

I agree this could be treated as a feature request.

Until then it sounds like simplest solution to start using namespaced components is to match the docs by having all component files together in one folder. This will be a large folder but at least the files will still be grouped together.

**Comment by camertron** [comment]
Hey @AlecRust, it sounds like this behavior is to be expected based on how Zeitwerk functions. Please don't hesitate to reopen if I've missed something :)
