### ISSUE TITLE
Stop war in Ukraine

### ISSUE THREAD

**Issue by alexcode-lab** [github/view_component#1305]
While Ukraine is under missile attacks GitHub could be used by Russians to develop apps and platforms aiming to destabilize Ukrainian web resources.  

Please, prevent these actions and don't stay on the same side with invaders! All information about war can be found at:  https://war.ukraine.ua/   

We urge you to close GitHub for Russia and its developers! We value your support and we are in need for your actions!

**Comment by boardfish** [comment]
Not speaking on behalf of GitHub itself here, but they've released a [blog post](https://github.blog/2022-03-02-our-response-to-the-war-in-ukraine/) explaining their stance. Others across GitHub's public repos have summarized this to you. 

While my thoughts are with you in this difficult time, I'll be closing this issue as it isn't directly linked to the ViewComponent project, and I'd advise against opening similar issues of this kind in public GitHub repositories.
