### ISSUE TITLE
Remove fallback support for old render syntax

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#131]
We have two cases where we support old syntax in `actionview-component`:

https://github.com/github/actionview-component/blob/1164a2e7eba2de8e0808be27a77c0495fad23d26/lib/action_view/component/monkey_patch.rb#L10

https://github.com/github/actionview-component/blob/master/lib/action_view/component/test_helpers.rb#L20

Let's remove these cases and the associated tests, merging right before we cut `v2.0.0`.

**Comment by inatomitk** [comment]
I'd like to take this issue.
