### ISSUE TITLE
Inherited component renders parent template in 2.51.0

### ISSUE THREAD

**Issue by davidrapson** [github/view_component#1315]
When rendering components which inherit from another component there is an issue rendering the expected template in the latest view component versions. Which template the component renders varies based on the Rails environment. Reproduced using view_component 2.51.0.

My best guess is that this may be a side-effect of https://github.com/github/view_component/pull/1302 as that's the only change I can see that affects template rendering between 2.50.0 and 2.51.0.

Please let me know if I can provide any more specific examples 🙏 

### Steps to reproduce

Created a reduced test case following the excellent instructions here: https://github.com/davidrapson/view_component-bug-replica

**In development mode**:

When in development mode the template rendered varies between page loads.

1. Go to the homepage
2. On first load you should see "Base component template"
3. On reloading the page you should see "Inherited component template"

**In test mode**:

When in test mode the parent template is always rendered.

1. Go to the homepage
2. You should see "Base component template" rather than the expected "Inherited component template"
3. On subsequent loads the component will still read "Base component template"

**In production mode**

When in production mode the component seems to render the expected template.

1. Go to the homepage
2. You should see "Inherited component template" as expected
3. On subsequent loads the component should still read "Inherited component template"

Reduced test case here https://github.com/davidrapson/view_component-bug-replica have also replicated whilst working on https://github.com/citizensadvice/design-system/tree/main/demo if it's helpful to provide instructions to replicate there too.

### Expected behavior

The template associated with the child component is rendered.

### Actual behavior

In development mode the parent template is rendered on first load and on subsequent loads the expected inherited template is rendered. In non-development modes only template of the parent component is rendered.

### System configuration
**Rails version**: 6.1.5
**Ruby version**: 3.0.3 (reproduced using 2.7.4 too)
**Gem version**: 2.51.0

**Comment by davidrapson** [comment]
Let me try running the test case in production to confirm.

Would be up for raising a PR with a failing test if I can get one working. Interestingly I tried bumping the version here https://github.com/citizensadvice/design-system/actions/runs/2016124844 and it passed all our rspec tests for our components. So far only been able to replicate when running in a full app context. Will keep digging though.

**Comment by BlakeWilliams** [comment]
@davidrapson thanks! The [`with_new_cache`](https://github.com/github/view_component/blob/25f37ca454eb9aba539b3b35f41c883c96be448f/test/test_helper.rb#L89-L101) test helper will likely be helpful here so other test runs/pre-compilation won't interfere with the test.

**Comment by davidrapson** [comment]
Cheers. Interestingly when the app is in production mode the reduced test case renders as expected using https://github.com/davidrapson/view_component-bug-replica

<img width="858" alt="image" src="https://user-images.githubusercontent.com/123386/159321566-09a3a107-f42c-469e-b1b2-9021f0e6b79d.png">

Will update the steps to reproduce to reflect that.

**Comment by davidrapson** [comment]
Added a failing tests over in https://github.com/davidrapson/view_component-bug-replica/blob/main/test/components/example_component_test.rb which can be seen failing here: https://github.com/davidrapson/view_component-bug-replica/runs/5631634613?check_suite_focus=true

Will have a go tomorrow at adding a failing test to the `view_component` gem itself.

**Comment by davidrapson** [comment]
OK! I _think_ I've managed to narrow this down to eager loading. At least managed to produce a few more examples.

- Added a version of the component test in a fork https://github.com/davidrapson/view_component/commit/207de9616125713d3ddd078ff91f47807d51167d
- Confirmed that setting `config.eager_load` to `false` reproduces the error https://github.com/davidrapson/view_component/commit/b132fbada21dfec24ed28c0a659a908ac1298457
- Made a corresponding branch on my example app which does the opposite and flips eager loading on in https://github.com/davidrapson/view_component-bug-replica/commit/8e2972190faaaa9d344cad92a50ed405d4bcb687
- Which then makes the original test pass https://github.com/davidrapson/view_component-bug-replica/actions/runs/2018349457

I'm now at the boundaries of my understanding of ruby and rails. I don't understand enough about eager loading to know why that would cause the issue, but at least reasonably confident it's a reproducible symptom (if not the actual cause).

Let me know if I can do anything else to help narrow things down. Definitely in wild-guessing territory now though to hopefully the above ☝️ gives you enough to go on for now.

**Comment by cbeer** [comment]
Thanks for digging into this issue -- we're impacted by this bug too. I believe the "compiled" version of `#render_template_for` is getting inherited by subclasses that are loaded after the parent class is rendered. eager loading ensures all the classes are loaded before any of them render (so they get the original definition of `render_template_for`).

**Comment by davidrapson** [comment]
Thanks, that makes some sense. Also spotting this bit of code https://github.com/github/view_component/blob/main/lib/view_component/engine.rb#L85-L87 helped me understand why the behaviour is different between environments.

@camertron Don't suppose you could shed some light on what's going on here?

**Comment by camertron** [comment]
Hey @davidrapson, thanks for bringing this up! It does indeed look like the problem is related to inheritance and lazy loading. I'm going to try and work up a fix today, but if I can't stand up a PR by EOD I'll revert the change.
