### ISSUE TITLE
i18n does not support scope attribute

### ISSUE THREAD

**Issue by tmaier** [github/view_component#1334]
### Steps to reproduce

```erb
<%= f.hint :notes, t('.main.info.notes') %>
```

and 

```erb
<%= f.hint :notes, t(:notes, scope: '.main.info') %>
```

### Expected behavior
Both should look up the same i18n key from the sidecar yml file

### Actual behavior

The one with the `scope` attribute does not look at the sidecar yml fle

### System configuration
**Rails version**: `rails (7.0.2.3)`

**Ruby version**: `ruby 2.7.6p219`

**Gem version**: `view_component (2.52.0)`

**Comment by boardfish** [comment]
Hi @tmaier! We've previously done some work in this area to improve i18n support, but there may still be a gap here. We'd appreciate it if you could contribute a failing test or a set of gists that can be added to the bug replication environment (`script/replicate-bug`). That way, we can see if this is a repeatable issue and start to fix it.

In the meantime, using string interpolation might get you what you need, but I can appreciate that if you're using `scope` you'll want this to work as you expect.

**Comment by joelhawksley** [comment]
@elia might you be able to chime in here?

**Comment by elia** [comment]
@joelhawksley #1335 should solve the issue
