### ISSUE TITLE
ViewComponent Happy Hour @ RailsConf

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#1342]
👋🏻  I'll be hosting a happy hour at RailsConf this year for the ViewComponent project. I'd love to see you there! 

Join us for drinks & snacks. We'll have stickers for all and a special something for project contributors!

Time: Tue, May 17, 2022, 5:00 PM – 8:00 PM PDT (come on over after the keynote)
Location: Lil Spirit (At Spirit of '77), 500 Northeast Martin Luther King Junior Boulevard, Portland, OR 97232

Space is limited. Email joelhawksley@github.com to RSVP.

**Comment by joelhawksley** [comment]
I've opened registration to the public, sign up here: https://www.eventbrite.com/e/viewcomponent-happy-hour-tickets-304168585427

**Comment by jonathanloos** [comment]
Joined the waitlist! @joelhawksley what do you think the likelihood of a couple spots opening up is?

**Comment by jonathanloos** [comment]
Joined the waitlist! @joelhawksley what do you think the likelihood of a couple spots opening up is?
