### ISSUE TITLE
ViewComponent not working with some Tailwind CSS classes

### ISSUE THREAD

**Issue by haxlerose** [github/view_component#1344]
I've got a Rails app using Turbo, esbuild and Tailwind CSS.  I've started to change some of my Rails partials that are rendered in views the usual way with `<%= render 'example_partial' %>` to ViewComponents being rendered with `<%= render ExamplePartial.new %>`.  All the Tailwind classes and responsive utility classes work normally when rendered the usual Rails way, but when I render them with ViewComponents, some of the classes and utilities don't work.

If I inspect the elements using the Chrome dev tools, I see the classes present in the `class=""` attribute, but in the styles area of dev tools, they're not listed.  For instance, I'm rendering a form in one ViewComponent like this:
```
# app/components/example_component.rb
class ExampleComponent < ViewComponent::Base
  def initialize(resource:)
    @resource = resource
  end
end
```
with a partial that looks something like this:
```
# app/components/example_component.html.erb
<%= form_with url: resource_path, target: '_top', class: 'mb-2 md:mb-0' do |f| %>
  <%= f.hidden_field :resource_id, value: @resource.id %>
  <%= f.submit 'Submit', class: "w-full md:w-fit" %>
<% end %>
```
I render it in a view file like this: `<%= render ExampleComponent.new(resource: @resource) %>`  In this instance, the component is working as expected with the tailwind `md:` responsive utility correctly changing the bottom margin to 0 when the screen width is medium or wider.  But if I go in and edit the partial and change the `md:mb-0` to `md:mb-10` (or any other value), it no longer recognizes the new `md:mb-10` class in the browser and it only uses the `mb-2` class no matter what the width of the screen is.

I have also had examples where a normal tailwind class like `border-4` doesn't work at all when rendered in a ViewComponent.  And in this particular element, if I change it to `border-2`, it starts working.  Both of those classes are default Tailwind classes.  I even have a customized `border-3` class that I've added and that works fine.  It's bizarre behavior.

### System configuration
**Rails version**: 7.0.2.3

**Ruby version**: 3.1.2

**Gem version**: 2.52.0

**Comment by haxlerose** [comment]
Well, I just figured it out thanks to a reddit post.  I'll leave this here for anyone who has the same issue.  In Tailwind's config file `tailwind.config.js`, the ./app/components directory needs to be added to the directories array under `content:`  Once I added it, everything started working properly.

**Comment by joelhawksley** [comment]
Thanks for documenting your resolution @haxlerose!
