### ISSUE TITLE
Capybara save_and_open_page method

### ISSUE THREAD

**Issue by WaKeMaTTa** [github/view_component#1386]
## Feature request

I would like to be able to use `save_and_open_page` capybara method.

### Motivation

[Method info `save_and_open_page`](https://www.rubydoc.info/gems/capybara/Capybara%2FSession:save_and_open_page)

**Comment by boardfish** [comment]
Hey @WaKeMaTTa! I take it you've attempted to use this method already? What currently happens when you attempt to use it;?

**Comment by adem-wecasa** [comment]
Hello @boardfish 

This is what I get:
```
NameError:
       undefined local variable or method `save_and_open_page'
```

**Comment by boardfish** [comment]
Looks like [that method's provided by `Capybara::Session`](https://github.com/teamcapybara/capybara/blob/51bca8300136ba2dcf45e92883a07845105f2b3a/lib/capybara/session.rb#L729-L731). I've just had a quick look inside Capybara and I was hoping this method might be accessible by chaining together `page.native.session.save_and_open_page`, but it doesn't seem to be the case.

**Comment by joelhawksley** [comment]
I believe this isn't working because there is no Capybara::Session present, as ViewComponent unit tests do not run in a browser.

**Comment by WaKeMaTTa** [comment]
> tests do not run in a browser

Ah! of course :facepalm:

**Comment by unikitty37** [comment]
Is there a way to get component tests to run in a browser — short of setting up full e2e tests to do that? (Ideally, just adding `js: true` to the `it` or `describe` would enable that…)

I need to test that a button component emits a specific custom event when the button is clicked.

**Comment by joelhawksley** [comment]
@unikitty37 see https://viewcomponent.org/guide/testing.html#testing-components-with-behaviors ❤️
