### ISSUE TITLE
Helpers proxy broken in 2.57.0

### ISSUE THREAD

**Issue by Bramjetten** [github/view_component#1390]
I believe the change in #1385 caused the helpers proxy to fail.

### Steps to reproduce
Use the helpers method in a ViewComponent

### Expected behavior
It should use the controller's original view context

### Actual behavior
It uses the view component's resulting in undefined methods.

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3.1.1

**Gem version**: 2.57.0

**Comment by bobmaerten** [comment]
Same problem here.

**Comment by BlakeWilliams** [comment]
Hi, thanks for the report!

Can you provide more details about the issue? Is this happening for all components, controller rendered components, or any other specific circumstances?

If possible, if you can provide a failing test that would also help us resolve the issue much more quickly.

**Comment by Bramjetten** [comment]
Looked a bit further and it looks like this only happens when using `.with_collection` in nested components. I've replicated the bug here:
https://github.com/Bramjetten/view_component-bug-replica

**Comment by borama** [comment]
Hello, we hit the same issue when using the helpers proxy in a child component:

1. we have a helper function defined in a standard helper module under `app/helpers`
2. we have a base component class:

       class ApplicationComponent < ViewComponent::Base
         ...
       end

3. we have a "detail" component, deriving from the base component; when we call a helper function from 1. here, we get a method not found error:

       class Details::Admin::DetailComponent < ApplicationComponent
         def some_method
           helper.some_helper(...)  # leads to undefined method `some_helper for #<Details::Admin::DetailComponent: ...
         end
       end 
      
We solved for now by directly including the helper module in the base component.

**Comment by camertron** [comment]
Thanks everyone, we've identified the issue. Should have a fix out by tomorrow (PT) 😄

**Comment by camertron** [comment]
Released in v2.57.1.
