### ISSUE TITLE
[Feature Proposal] Make component rendering DRY

### ISSUE THREAD

**Issue by rcdvl** [github/view_component#1405]
First of all, thank you for such an amazing library!

While developing a side project of mine, I started to feel like doing `<%= render(ComponentClass.new(params: ...)) %>` was way too verbose and repetitive.
Looking at how React does things, I had this idea "what if we could simply call `<%= component_class(params: ...) %>`? I was about to start trying to code this for my project-only, but It feels like this could be helpful for others.

Do you think having an additional API like this would be helpful in the library?

**Comment by boardfish** [comment]
Hey @rcdvl! This is a good suggestion, and various folks in the community share your sentiment. #1293 has some example code you might want to drop in to generate those helpers if you wish to use them. I'll be closing this issue in favor of that discussion.
