### ISSUE TITLE
Fix incompatibility with `rails` `main`

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#1430]
### Steps to reproduce

Run the ViewComponent test suite against `rails` `main`.

### Expected behavior

The build passes.

### Actual behavior

The build fails: https://github.com/github/view_component/runs/7417840434?check_suite_focus=true

**Comment by joelhawksley** [comment]
Note: we shipped a stopgap for this issue in https://github.com/github/view_component/issues/1430 cc @BlakeWilliams

**Comment by Spone** [comment]
> Note: we shipped a stopgap for this issue in https://github.com/github/view_component/issues/1430 cc @BlakeWilliams 

I think you meant #1429 ✌️
