### ISSUE TITLE
Polymorphic slots missing predicate method

### ISSUE THREAD

**Issue by TastyPi** [github/view_component#1436]
### Steps to reproduce

1. Create a component with a polymorphic slot
2. Try to use the predicate method for the slot
3. See that the predicate is undefined

e.g.

```ruby
class MyComponent < ViewComponent::Base
  renders_one icon, types: {
    svg: SvgComponent,
    font: IconFontComponent
  }

  def before_render
    svg("default.svg") unless icon?
  end
end
```

### Expected behavior

In the example `icon?` should be defined

### Actual behavior

`icon?` is not defined

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

**Gem version**: 2.59.0

**Comment by Spone** [comment]
Good catch! I totally forgot about polymorphic slots when implementing predicate methods...

Would you like to contribute a failing test or a fix?

**Comment by TastyPi** [comment]
I'm pretty sure this would be the fix, though I haven't figured out the right way to test it yet https://github.com/github/view_component/compare/main...TastyPi:view_component:graham/view-component-predicate

**Comment by Spone** [comment]
Can you open a PR with this fix? I'll help with the tests!

**Comment by TastyPi** [comment]
@Spone created #1437, thanks for the help!
