### ISSUE TITLE
Not updating turbo frames on POST when rendering from controllers

### ISSUE THREAD

**Issue by MatheusPoliCamilo** [github/view_component#1440]
### Description

When rendering a `ViewComponent` from the controllers, it isn't updating the turbo frames tags specifically on POST. Using Rails partials it works fine. Using a Rails partial with a `ViewComponent` inside works too.

### Steps to reproduce

I made an example in this repository: https://github.com/MatheusPoliCamilo/view_component_1440

Basically a request to this `ExampleController#create` will updates a turbo frame (if the partial renders a turbo frame tag with the expected ID):
```ruby
class ExampleController < ApplicationController
  def create
    render partial: "example"
  end
end
```

But the same isn't occurring with the `ViewComponent`, this code doesn't update a turbo frame (considering that it will render a turbo frame tag with the expected ID):

```ruby
class ExampleController < ApplicationController
  def create
    render ExampleViewComponent.new
  end
end
```

### Expected behavior

Expected to the rendered `ViewComponent` by Controller updates the turbo frame when finishes the POST request, like when using Rails partials.

### Actual behavior

The rendered `ViewComponent` by Controller isn't updating the turbo frame tag.

### Workaround

Specify the `content_type: "text/html"` on the Controller render, since the response comes with the type `"text/vnd.turbo-stream.html"`.

```ruby
class ExampleController < ApplicationController
  def create
    render ExampleViewComponent.new, content_type: "text/html"
  end
end
```

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**Gem version**: 2.61.1

**Turbo rails version**: 1.1.1

**Comment by MatheusPoliCamilo** [comment]
@joelhawksley I've updated the docs, could you take a look in #1422?

**Comment by lazylester** [comment]
@MatheusPoliCamilo are you using haml for your views? I was facing the same issue you reported, and came across this: https://github.com/hotwired/turbo-rails/issues/287#issuecomment-1105729895. It seems that rendering haml files doesn't trigger the appropriate content_type header. Specifying the content_header in the controller is a workaround. It seems to me like a change to haml code is indicated. Or you can change your filenames to filename.html.haml iso filename.haml
