### ISSUE TITLE
view_component + turbo + active_record callbacks can lead to a deadlock

### ISSUE THREAD

**Issue by shepmaster** [github/view_component#1447]
### Steps to reproduce

This is a tough one to reproduce as it deals with multithreading and occurs in a private application that I will need to spend a chunk of time to obfuscate / minimize. I can do that if useful, but I figured I'd open the issue to start discussion.

The general setup:

1. A Rails application 
1. A multithreaded web server 
1. Perform **parallel** web requests
1. One web request modifies data inside of an Active Record transaction
    - There is an `after_commit` callback that performs a websocket broadcast
    - The broadcast uses view_components to generate HTML
1. Another web request uses view_components to generate HTML  
    - It gathers data from Active Record

### Expected behavior

No deadlock occurs.

### Actual behavior

A deadlock occurs. 

### Notes / debugging

<details>
<summary>This stacktrace shows one thread acquires the Active Record connection lock, then attempts to get the view_component compiler lock</summary>

```
.../ruby-3.0.4/gems/rspec-core-3.11.0/exe/rspec:4:in `<top (required)>'
.../project/spec/features/my_work_spec.rb:163:in `block (3 levels) in <top (required)>'
.../ruby-3.0.4/gems/factory_bot-6.2.0/lib/factory_bot/evaluation.rb:18:in `create'
.../ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:302:in `save!'
.../ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
.../ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
.../ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
.../ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:155:in `commit_records'
.../ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:321:in `committed!'
.../ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:824:in `_run_commit_callbacks'
.../project/app/models/task.rb:46:in `block in <class:Task>'
.../ruby-3.0.4/gems/turbo-rails-1.1.1/app/models/concerns/turbo/broadcastable.rb:138:in `broadcast_update_to'
.../ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_controller/renderer.rb:100:in `render'
.../project/app/views/my_work/tasks/_updated_task.html.slim:5:in `_app_views_my_work_tasks__updated_task_html_slim___4242759950573012154_88260'
.../ruby-3.0.4/gems/view_component-2.62.0/lib/view_component/base.rb:129:in `render_in'
.../ruby-3.0.4/gems/view_component-2.62.0/lib/view_component/compiler.rb:126:in `render_template_for'
.../ruby-3.0.4/gems/view_component-2.62.0/lib/view_component/compiler.rb:95:in `with_lock'
.../ruby-3.0.4/gems/view_component-2.62.0/lib/view_component/compiler.rb:95:in `synchronize'
```

</details>

<details>
<summary>This stacktrace shows one thread acquires the view_component compiler lock, then attempts to get the Active Record connection lock</summary>

```
.../ruby-3.0.4/gems/puma-5.6.4/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
.../ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
.../project/app/views/my_work/overdue_tasks/index.html.slim:2:in `block in _app_views_my_work_overdue_tasks_index_html_slim___704223861362102887_91000'
.../ruby-3.0.4/gems/view_component-2.62.0/lib/view_component/base.rb:129:in `render_in'
.../ruby-3.0.4/gems/view_component-2.62.0/lib/view_component/compiler.rb:126:in `render_template_for'
.../ruby-3.0.4/gems/view_component-2.62.0/lib/view_component/compiler.rb:95:in `with_lock'
.../ruby-3.0.4/gems/view_component-2.62.0/lib/view_component/compiler.rb:95:in `synchronize'
.../ruby-3.0.4/gems/view_component-2.62.0/lib/view_component/compiler.rb:128:in `block in render_template_for'
.../project/app/components/my_work_task_section_component.html.slim:6:in `call'
.../ruby-3.0.4/gems/view_component-2.62.0/lib/view_component/base.rb:129:in `render_in'
.../ruby-3.0.4/gems/view_component-2.62.0/lib/view_component/compiler.rb:126:in `render_template_for'
.../ruby-3.0.4/gems/view_component-2.62.0/lib/view_component/compiler.rb:95:in `with_lock'
.../ruby-3.0.4/gems/view_component-2.62.0/lib/view_component/compiler.rb:95:in `synchronize'
.../ruby-3.0.4/gems/view_component-2.62.0/lib/view_component/compiler.rb:128:in `block in render_template_for'
.../project/app/components/my_work/task_component.html.slim:18:in `call'
.../ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/querying.rb:47:in `find_by_sql'
.../ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/query_cache.rb:103:in `select_all'
.../ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:736:in `prepare_statement'
.../ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
```

</details>

(These abbreviated stacktraces show the general problem; I'd be happy to share the full versions without any removed frames if useful).

I see that the monitor synchronization is optional (via #1177) so I hacked the view_component source to disable the lock even in test mode. I was then able to run our tests 20 times without a deadlock. Without that, our tests deadlock fairly reliably.

### System configuration
**Rails version**: 6.1.4

**Puma version**: 5.6.4

**turbo-rails version**: 1.1.1

**Ruby version**: ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [arm64-darwin21]

**view_component version**: 2.62.0

**Comment by BlakeWilliams** [comment]
I wonder if we need to make the locking a bit more advanced, using something like a [ReadWriteLock](http://ruby-concurrency.github.io/concurrent-ruby/master/Concurrent/ReadWriteLock.html).

Would that solve the issue here, assuming the problem is that both threads are trying to access the same lock in the `#call` method, leading to a deadlock? The `ReadWriteLock` should enable us to call `#call` concurrently, only blocking during compiles, instead of blocking for entire renders. 

That sounds like more correct behavior, too.

**Comment by shepmaster** [comment]
I'll have to poke around the code a bit more to see what pain would be involved in switching from the `Monitor` to a `ReadWriteLock`. I'd also have to read about how `ReadWriteLock` is implemented with regards to fairness — if a read lock waits in a queue behind a write lock attempt, I think the same problem would occur.

My random idea was to make `Compiler` instances thread-local — each thread would compile everything once in dev / test, but wouldn't need to interact across threads at all.

**Comment by BlakeWilliams** [comment]
@shepmaster I think that could work too!

I took poked around a bit and ended up reproducing *a* deadlock with https://github.com/github/view_component/pull/1448 the `ReadWriteLock` fixed it. I think that may be close to your scenario, but feel free to give that branch a try and see if it resolves your issues in CI to validate it.

**Comment by shepmaster** [comment]
> My random idea was to make `Compiler` instances thread-local

My local changes are:

```diff
diff --git a/lib/view_component/base.rb b/lib/view_component/base.rb
index 665a93d..420410f 100644
--- a/lib/view_component/base.rb
+++ b/lib/view_component/base.rb
@@ -525,7 +525,7 @@ module ViewComponent
 
       # @private
       def compiler
-        @__vc_compiler ||= Compiler.new(self)
+        Thread.current.fetch(:@__vc_compiler) { Compiler.new(self) }
       end
 
       # we'll eventually want to update this to support other types
```

This also prevents the deadlock.

**Comment by camertron** [comment]
It seems like the thing to do here is to only acquire the lock if templates need to be compiled, and if the lock isn't acquirable, block until it is. In other words, I don't think there's any reason to lock on read. We could do something like:

```ruby
def compile(raise_errors: false, force: false)
  if __vc_compiler_lock.mon_locked?
    Timeout.timeout(1) do
      while __vc_compiler_lock.mon_locked?
        sleep 0.1
      end
    end

    return
  end

  with_lock do
    # compile templates and define methods
  end
end
```

**Comment by camertron** [comment]
@shepmaster won't a thread-local compiler potentially compile templates and define methods on a VC class more than once?

**Comment by camertron** [comment]
@BlakeWilliams right, but as long as we block until the compilation is done, there shouldn't be a problem?

**Comment by shepmaster** [comment]
I do agree that changing the concurrency story (such as by splitting reader / writer) could lead to increasing the performance, but I'm not sure that is a concern as this only applies to development and test. However, if you feel comfortable making those changes, it seems like an OK way forward. I'll test with your PR in a second.

> won't a thread-local compiler potentially compile templates and define methods on a VC class more than once?

I don't claim to be conversant in the VC code base enough to know that for sure, but I'd expect that the `CompileCache` methods are already attempting to prevent that. In a degenerative case, I could see multiple threads racing to compile the same VC class at startup / after a change, but the behavior should be idempotent so at worst it would be a small amount of extra work. That work would be done in multiple threads, while the current behavior would have it block in multiple threads, so I don't think you'd notice any performance differences.

**Comment by shepmaster** [comment]
> I don't claim to be conversant in the VC code base

Since y'all are here, what _exactly_ is the shared resource that is intended to be protected by `__vc_compiler_lock`?

**Comment by BlakeWilliams** [comment]
> Since y'all are here, what _exactly_ is the shared resource that is intended to be protected by `__vc_compiler_lock`?

The `render_template_for` method, which is defined/undefined on the component class (effectively a singleton resource) https://github.com/github/view_component/blob/ab6fc4e06be41aa89ffd50e9ba93cfc025063b2a/lib/view_component/compiler.rb#L135-L146

I'm writing up something a bit longer, but I think the thread-local compiler approach would still run into issues where one thread undefines the method while another thread is attempting to use it to render.

**Comment by shepmaster** [comment]
> which is defined/undefined on the component class

Why does the monitor live in a `Compiler` instance instead of on the component class? That is, would something like this work?

```ruby
component_class.with_lock do
  component_class.class_eval <<-RUBY, __FILE__, __LINE__ + 1
```

Or, if it needed to be somewhere central, what about a per-class monitor in a map of some kind? e.g.

```ruby
CompilerCache[component_class].with_lock do
  component_class.class_eval <<-RUBY, __FILE__, __LINE__ + 1
```

**Comment by BlakeWilliams** [comment]
The compiler used to live in the base class, but was extracted to help readability and understandability of the code, since the base class does a lot.

As-is, I think the existing code is roughly equivalent to your examples, but just lives in a separate class since there should be only one compiler per-component as defined in the base class:

https://github.com/github/view_component/blob/ab6fc4e06be41aa89ffd50e9ba93cfc025063b2a/lib/view_component/base.rb#L527-L529

**Comment by BlakeWilliams** [comment]
Here's why I think we need a read lock:

Imagine you have a component, `MyComponent` that is already compiled in a `development` environment. We're running Puma with 2 workers, so we effectively have 2 threads that can run concurrently:

Thread 1:
* `render MyComponent` is called, and [`#compile`](https://github.com/github/view_component/blob/ab6fc4e06be41aa89ffd50e9ba93cfc025063b2a/lib/view_component/base.rb#L89) will [return early because it's already compiled](https://github.com/github/view_component/blob/ab6fc4e06be41aa89ffd50e9ba93cfc025063b2a/lib/view_component/compiler.rb#L33)
* Jump to thread 2...

Thread 2:
* You hit cmd+s on a `my_component.html.erb`, the compile cache is invalidated
* We [don't early exit](https://github.com/github/view_component/blob/ab6fc4e06be41aa89ffd50e9ba93cfc025063b2a/lib/view_component/compiler.rb#L33) because the compile cache says we aren't compiled
* The template is compiled, then we [undefined the method](https://github.com/github/view_component/blob/ab6fc4e06be41aa89ffd50e9ba93cfc025063b2a/lib/view_component/compiler.rb#L74)
* Back over Thread 1:

Thread 1:
* We got past `before_render` and `render?`, and now we're ready to call the user's template code! We go to call [`render_template_for`](https://github.com/github/view_component/blob/ab6fc4e06be41aa89ffd50e9ba93cfc025063b2a/lib/view_component/base.rb#L129) but it doesn't exist! Boom, `NoMethodError`
* Back to thread 2

Thread 2:

* We've [re-added the `render_template_for` method](https://github.com/github/view_component/blob/ab6fc4e06be41aa89ffd50e9ba93cfc025063b2a/lib/view_component/compiler.rb#L79-L81) but it's too late, we've already caused thread 1 to error.

This is definitely somewhat contrived, but it's a situation that was relatively common for folks to hit in the CI suites according to [this issue](https://github.com/github/view_component/issues/869).

**Comment by shepmaster** [comment]
Your sequence diagram makes sense to me, thanks. I was going to ask if you could "atomically" redefine the method(s), but I see the comment about that:

https://github.com/github/view_component/blob/ab6fc4e06be41aa89ffd50e9ba93cfc025063b2a/lib/view_component/compiler.rb#L69-L70

> a situation that was relatively common for folks to hit in the CI suites

And that's where our deadlock is occurring. Over the years, my gut has told me that CI suites operate faster / at different rates than humans and tend to tickle these things out

**Comment by shepmaster** [comment]
> I'll test with your PR in a second.

I was able to run 400 tests without a deadlock occurring, so that PR (at `ab6fc4e06be41aa89ffd50e9ba93cfc025063b2a`) seems like it addresses our problem as well.

**Comment by BlakeWilliams** [comment]
> Your sequence diagram makes sense to me, thanks. I was going to ask if you could "atomically" redefine the method(s), but I see the comment about that:

Yep, that's a great observation. We introduced a good amount of complexity to avoid a Ruby warning. 😄 

If would be interesting if Ruby could provide a way to redefine a method without the warning, or pass a flag that's like "yep, definitely going to redefine this so don't warn please".

**Comment by BlakeWilliams** [comment]
Maybe https://www.rubydoc.info/gems/activesupport/Module:silence_redefinition_of_method is relevant here? 🤔

**Comment by camertron** [comment]
@BlakeWilliams ah ok I'm convinced! Nice explanation 😄

**Comment by shepmaster** [comment]
I just wanted to say thank you. I rather dreaded opening this issue, expecting to be told that I was Doing It Wrong or that ultimately Rails needed to be changed, not VC. Instead, I had the opportunity to have solid technical discussions and my issue was resolved in less than 24 hours. It has been a pleasure!
