### ISSUE TITLE
Components without the `Component` suffix

### ISSUE THREAD

**Issue by thutterer** [github/view_component#1456]
I'm wondering, can we have components without that `Component` suffix? There is this line in the docs:

https://github.com/github/view_component/blob/aab5a4664755c0c5ec65a5c511dfbbec9d8eee91/docs/guide/getting-started.md?plain=1#L13

And all examples follow this rule, but is it a requirement?

A quick test where I renamed a working `Foo::BarComponent` to `Foo::Bar` seems to work just fine.
And I saw this is already done to some extent in Primer, too: https://github.com/primer/view_components/issues/676

**Comment by joelhawksley** [comment]
@thutterer it is not a requirement, but is still what I'd consider convention, hence it being specified under Conventions in the docs. I'd be happy to consider a PR to change the wording if you'd like to suggest a diff ❤️

**Comment by thutterer** [comment]
Thank you @joelhawksley for the quick reply ⚡ 
Sure, I can make a PR for this in the next couple of days.

**Comment by koenhandekyn** [comment]
input from a user: I share the primer opinion to drop the component suffix for reduced verbosity, one reason is that components are mostly namespaced already in our case.

- [ ] generators should be configurable to add or not add the component suffix

**Comment by Spone** [comment]
> generators should be configurable to add or not add the component suffix

I'd say that in this case, where you chose to diverge from the convention, you can implement your own custom generator. The [contrib](https://github.com/palkan/view_component-contrib) gem can be a good starting point to generate a custom generator.

**Comment by boardfish** [comment]
This seems similar to #670, and #1005 which followed it. @koenhandekyn @thutterer These might be helpful in understanding how we came to this decision in the past.

**Comment by thutterer** [comment]
Thank you @boardfish, reading these issues was very insightful.

@joelhawksley I couldn't decide where to best add this information in the docs. I considered linking to this issue here in the "Conventions" section, but that might be bit too distracting for someone who is just getting started.

I'm closing this issue, as I'm sure the conventions section will see some edits anyway when https://github.com/github/view_component/issues/618 moves forward :)

Thanks everyone! :wave:
