### ISSUE TITLE
config.view_component.generate_stimulus_controller vs config.view_component.generate.stimulus_controller 

### ISSUE THREAD

**Issue by koenhandekyn** [github/view_component#1458]
the API documentation mentions `config.view_component.generate.stimulus_controller = true` while the current correct syntax seems to be with an underscore, i.e. ``config.view_component.generate.stimulus_controller = true`

**Comment by koenhandekyn** [comment]
relates to https://github.com/github/view_component/issues/1362

**Comment by Spone** [comment]
This will be solved by #1291
