### ISSUE TITLE
ActionView::Component::Base#format shadows Kernel#format

### ISSUE THREAD

**Issue by jcoyne** [github/view_component#156]
This makes it confusing if you try to use Kernel#format

```
     Failure/Error: format('%.3f', process.elapsed.to_f)

     ArgumentError:

       wrong number of arguments (given 2, expected 0)

     # ./app/components/workflow_process_row.rb:20:in `elapsed'

```

Of course you can work around by explicitly using `Kernel.format(...)`

**Comment by joelhawksley** [comment]
@jcoyne interesting. This definitely isn't desired behavior. Any ideas for how we might get around this?

**Comment by jcoyne** [comment]
@joelhawksley one could check the arity of the method and delegate to Kernel if it's 2.

**Comment by joelhawksley** [comment]
Hmm. I wonder if there might be a more general-purpose solution. Perhaps we should look into removing the need to define `format` at all?

**Comment by javierav** [comment]
Any update on this issue? Today I ran into this problem!

**Comment by BlakeWilliams** [comment]
This doesn't solve the underlying problem, but I believe you can call `Kernel.format` directly. e.g. `Kernel.format "%d", 3`
