### ISSUE TITLE
Previews of components in modules

### ISSUE THREAD

**Issue by bartekadams** [github/view_component#203]
Hello, I am trying to preview components which are in modules.

When I try to write it like this all my components under rails/components disappear.
```ruby
module Foo
  class BarPreview < ActionView::Component::Preview
    def default
      render Bar
    end
  end
end
```
To make preview list work again I must not only remove this code, but also restart server (puma-dev).

However, code written like this is valid and works right.

```ruby
class Foo::BarPreview < ActionView::Component::Preview
  def default
    render Bar
  end
end
```

Is it a bug or I am doing something wrong?

### System configuration
**Rails version**: 5.2.4.1
**Ruby version**: 2.6.3
**gem version**: 1.8.1

**Comment by joelhawksley** [comment]
@juanmanuelramallo might you look into this?

**Comment by juanmanuelramallo** [comment]
Hey @bartekadams, can you try upscoping the parent class with double colons? Something like:
```ruby
module Foo
  class BarPreview < ::ActionView::Component::Preview
    def default
      render Bar
    end
  end
end
```

**Comment by juanmanuelramallo** [comment]
> but also restart server (puma-dev)

This might be a sign of something else, like auto loading is not happening correctly for these preview classes. We might want to look into that.

**Comment by bartekadams** [comment]
@juanmanuelramallo Sorry for responding so late. Putting double colons before as you wrote works.

Unexpectedly for me when I was recreating version that didn't work earlier is appears to work now 😮

**Comment by juanmanuelramallo** [comment]
Should we close this issue @joelhawksley ? I think it's been solved already

**Comment by joelhawksley** [comment]
Looks good to me! Thanks for the help @juanmanuelramallo ❤️
