### ISSUE TITLE
Support Ruby 2.4 in CI

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#209]
https://github.com/github/actionview-component/pull/207 removed support for Ruby 2.4 as it was breaking CI: https://github.com/github/actionview-component/runs/444076324.

It would be nice to re-introduce this test coverage.

**Comment by andrewmcodes** [comment]
@joelhawksley I’ll open a PR for this today or tomorrow

**Comment by rmacklin** [comment]
Is this still worth doing? We're only 12 days from the official EOL date for ruby 2.4:

![image](https://user-images.githubusercontent.com/1863540/77103033-06ba9e00-69d7-11ea-9314-6d7395be677d.png)

https://www.ruby-lang.org/en/downloads/branches/

**Comment by joelhawksley** [comment]
@rmacklin if @andrewmcodes has a simple enough solution, I'm cool with adding support. I'd love to be compatible with as many folks' apps as possible 😄

**Comment by rmacklin** [comment]
Fair enough. If any new changes break CI on ruby 2.4 again, though, I think it'd be worth considering dropping support.

(Folks should take the time to update to a supported version of ruby so they can continue to receive security updates. To that end I personally think gem maintainers should be comfortable investing their time supporting only the officially supported versions of ruby.)

**Comment by joelhawksley** [comment]
@rmacklin I agree 100%. There's a reason we don't have 2.4 support right now 😄
