### ISSUE TITLE
Add testing support / examples for passing ERB to blocks

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#215]
I'd love to be able to write a unit test like:

```ruby
def test_renders_content_from_block
  result = render_inline(WrapperComponent.new) do
    <%= 1+2 %>
  end

  assert_html_matches result.css("span").to_html, "<span>3</span>"
end
```

Right now, we have to test this kind of block in an integration test, which isn't ideal.

**Comment by jonspalmer** [comment]
seconded that this would be great. I'm sure is possible and there must be prior art. I briefly scanned the Rails codebase for something similar and didn't find it obviously but I bet its there.
