### ISSUE TITLE
Accessing session scope?

### ISSUE THREAD

**Issue by ultrawebmarketing** [github/view_component#226]
I really can't wait until they enable discussions in this repo.

This is just a question. Is there a preferred way of accessing and setting session information in components? Reason being is that while porting over some partials, we had some logic in the partial for keeping tracking of rendering that we would keep in the session of the user. This made it very easy to reuse the partials in other areas of the site. When accessing the session from a component, it will throw an error. Any ideas or is this something that components shouldn't do?

**Comment by joelhawksley** [comment]
@ultrawebmarketing for our internal components, we generally try to avoid having components use state that is not explicitly passed into them. Doing so makes them easier to unit test and to reuse in different views / outside the request path.

You may be able to get the behavior you want using the `helpers.` escape hatch, which allows you to make a method call in the containing view context.

But I'm not sure if this helps or not, as I'm having a hard time imaging the code you're describing. Perhaps you could provide and example?

**Comment by ultrawebmarketing** [comment]
An example... We have a component that displays a set of tabs. This component can be used in multiple areas of the site. Now what we want to do is save which tab is active so that if the user comes back to that page, the tab that was active, is active again and not the default tab, thus we store the active tab in a session. Yeah, we probably could do this stuff in the controller and pass the active_tab as a parameter to the component, it just makes using the easier when you don't have to think about that :)

**Comment by joelhawksley** [comment]
@ultrawebmarketing you're correct that you could pass that in from the controller. What if you instead had it at the callsite?

Something like:

`render(MyTabNav.new(current_tab: session[:current_tab])`

That way, you are reducing your coupling to the potential values of `session[:current_tab]`, not all of `session`.

**Comment by ultrawebmarketing** [comment]
while that will work for retrieving, it's the setting which is the main part. for instance, in the partial i have:

```
session['active_tabs'] ||= {}
session['active_tabs'][ params[:customer_id] ] = ''
if params[:active_tab].present?
  session['active_tabs'][ params[:customer_id] ] = params[:active_tab]
end
active_tab = session['active_tabs'][ params[:customer_id] ]
```

so now I can not only get the active_tab but also set it without having any external code.

**Comment by joelhawksley** [comment]
@ultrawebmarketing I see. That's generally the kind of logic we'd put in a controller.

But for the sake of migrating, you should be able to use `helpers.session` and `helpers.params` to make this work. It will just be tricky to unit test.

**Comment by joelhawksley** [comment]
Closing.
