### ISSUE TITLE
Regression in 1.14.1

### ISSUE THREAD

**Issue by jcoyne** [github/view_component#254]
When I upgraded from 1.12.0 to 1.14.1 and ran my tests I got the following error:

```
LoadError:

  cannot load such file -- action_view/component/test_helpers
```

As this wasn't a major version upgrade, shouldn't that file remain where it was to provide backward compatibility?

**Comment by joelhawksley** [comment]
Oh, darn! You're right, we missed this one. I'll get to this soon.

**Comment by jcoyne** [comment]
Also:
```
NameError:

  uninitialized constant ActionView::Component::TestHelpers
```

**Comment by joelhawksley** [comment]
@jcoyne can you give https://github.com/github/view_component/releases/tag/v1.15.0 a try and let us know if this fixes your issue?
