### ISSUE TITLE
Refactor the preview templates to be located in `app/views` folder

### ISSUE THREAD

**Issue by juanmanuelramallo** [github/view_component#297]
### Feature request
Following the discussion started in https://github.com/github/view_component/issues/289#issuecomment-612612056 we should make use of the `app/views` folder for our preview templates. 

Also we might not need to namespace the previews controller with `Rails`.

### Motivation
Just to improve code quality and maintainability in the gem

**Comment by juanmanuelramallo** [comment]
@jonspalmer is there something I missed here?

**Comment by jonspalmer** [comment]
Looks right to me.
