### ISSUE TITLE
Access collection counters

### ISSUE THREAD

**Issue by franks921** [github/view_component#301]
Hi

### Feature request

Be able to access collection counters in the component template linked to `collection_parameter_name`. The desired outcome would be to use `user_counter` in the template if a collection is passed in.

### Motivation

This will closely align to Rails' own `render collection:` functionality.

----

If anyone has any workaround other than looping over the collection, rendering the component in the loop and passing an index to the component (my current work around), it would be greatly appreciated.

Thank you in advance :)

**Comment by jonspalmer** [comment]
Could you provide an example use case of how you're like the API to work in practice?

**Comment by franks921** [comment]
Sure thing @jonspalmer

### Usage

```.slim
= render Molecules::UserProfileComponent.with_collection(@facade.users)
```

### Component setup

```.rb
# app/components/molecules/user_profile_component.rb

class Molecules::UserProfileComponent < ApplicationComponent

  attr_reader \
    :html,
    :user

  def initialize(user:, html: {})
    @user = user
    @html = html
  end

  def status
     # some logic around different user statuses
  end

end
```
It's at this point it could be useful having access to a `{collection | user}_counter` and / or `collection_size` method. I've added an arbitrary example with the `if` statement in the template.

```.slim
// app/components/molecules/user_profile_component.html.slim

.m-userProfile*html
  = render Atoms::AvatarComponent.new(\
    user:  user,
    html:  { class: 'm-userProfile__avatar' })

  - if collection_size > 0
    .m-userProfile__meta User ##{collection_counter}

  .m-userProfile__name
    = user.full_name(true)

  - if status.present?
    .m-userProfile__status
      = status
```

I am also looking at some solutions of sending this information to the component class from `ViewComponent::Collection` so I am open to some suggestions on how the project might want to approach this so I can also look at contributing to a solution.

**Comment by joelhawksley** [comment]
@tclem I'd love to hear your thoughts here ❤️

**Comment by tclem** [comment]
Seems reasonable and useful.

I think partial rendering of collections supports this with a _partial_name_`_iteration` object that's available to each template. It also provides helpers like `first?` and `last?` in addition to `index` and `size`. Might be worth double checking that and sticking to what Rails is doing now. We've already got `with_collection_parameter` so the view component author would have control over the name.

``` ruby
# app/components/molecules/user_profile_component.rb
class Molecules::UserProfileComponent < ApplicationComponent
  with_collection_parameter :user

  def initialize(user:)
    @user = user
  end
end
```

``` erb
<div>User <%= user_iteration.index %></div>
<div><%= user_iteration.size %></div>
<div><%= user_iteration.first? %></div>
<div><%= user_iteration.last? %></div>
```

**Comment by franks921** [comment]
Hi @tclem, that is it exactly. 💯

**Comment by joelhawksley** [comment]
@franks921 I'm 👍 to @tclem 's solution. I eagerly await your PR ❤️

**Comment by franks921** [comment]
Thanks @joelhawksley and @tclem. I've already forked and brought the library into my current project and will be doing this in realtime on a feature I am building.

I will be in touch after my deadline 👍

**Comment by franks921** [comment]
Hi @joelhawksley and @tclem 

Before I create a PR and write some tests, I wanted to run a solution past both of you. This turned out to be a lot simpler than I first thought, using `ActionView::PartialIteration` already built into Rails and here it is: https://gist.github.com/franks921/ddf94371bec83d6736d2c7df9d2bef73

My changes are in the `initialize` and `render_in` methods.

I'm also willing to extract the `PartialIteration` class out of Rails and create a `ViewComponent::PartialIteration` class in the gem.

**Comment by franks921** [comment]
Hi again @joelhawksley and @tclem

I went ahead and opened a PR #306. I figured it might be easier to have discussions around the actual code.
