### ISSUE TITLE
[Design Discussion] Organizing Sidecar assets

### ISSUE THREAD

**Issue by jonspalmer** [github/view_component#331]
# Introduction

There has been a lot of discussion on the right way to organize sidecar assets and ruby classes for ViewComponents: https://github.com/github/actionview-component/issues/15#issuecomment-565834219, #67, #168, #283.

We don't have a clean solution yet but we have some ideas

# What do we know?

1. ViewComponents are more than just a subclass of ViewComponent::Base and a view file. It's clear that the community has spoken for a need for sidecar javascript assets - Stimulus controllers, css, i18n yml, and also other Ruby files like Stimulus Reflex.
1. The current directory structure is flat and leads to very fat directories 
1. Namespaces help but don't solve the complete problem - they just subdivide it.
1. Ruby autoloader rules impose restrictions on how we organize things.

# The Problem today

Suppose we have four components: `AlertComponent`, `ButtonComponent`, `FormComponent` and `Form:TextFieldComponent` (note the Ruby namespace on that later - it's going to matter).  Today the directory structure would look like this:

```
app/components

├── alert.css
├── alert.html.erb
├── alert_component.rb.          => AlertComponent
├── alert_controller.js
├── application_component.rb     => ApplicationComponent
├── button.css
├── button.html.erb
├── button_component.rb.         => ButtonComponent
├── button_controller.js  
├── form
│   ├── text_field.css
│   ├── text_field.html.erb
│   ├── text_field_component.rb  => Form::TextFieldComponent
│   └── text_field_controller.js
├── form.css
├── form.html.erb
├── form_component.rb            => Form::FormComponent
└── form_controller.js
```

We can see app/components is already a 'fat' directory and we're only four components in.

# What would the ideal solution look like?

In an ideal world the solution would look much like organizing front end assets where we group each component and its sidecar file in their own directory:

```
app/components
├── alert
│   ├── alert.css
│   ├── alert.html.erb
│   ├── alert_component.rb
│   └── alert_controller.js
├── application_component.rb
├── button
│   ├── button.css
│   ├── button.html.erb
│   ├── button_component.rb
│   └── button_controller.js
└── form
    ├── form.css
    ├── form.html.erb
    ├── form_component.rb
    ├── form_controller.js
    └── text_field
        ├── text_field.css
        ├── text_field.html.erb
        ├── text_field_component.rb
        └── text_field_controller.js
```

# Solutions

## 1. Use Autoloader 

At first glance we can use the auto loader to tell Rails to find our components inside directories (much like Rails eager loads ruby classes in all sub-directories of `app`

```
Rails.application.config.paths.add "app/components", eager_load: true, glob: "*"
```

This works **_great_** except for namespaces. `AlertComponent`, `ButtonComponent`, `FormComponent` work exactly the way we work but `TextFieldComponent` won't get loaded at all.

### Also add namespaces to the autoloader - nearly works 😄  😞 

We can add the namespaced components to the autoloader

```
Rails.application.config.paths.add "app/components", eager_load: true, glob: "*"
Rails.application.config.paths.add "app/components/form", eager_load: true, glob: "*"
```

Now Rails will load the `TextFieldComponent` However it will lose it's 'Form' names space so it will be `TextFieldComponent` not `Form::TextFieldComponent`

There are other combinations of autoloader configuration, particularly with Zeitwerk in Rails 6 that allow us some flexibility. For a detailed discussion see https://github.com/fxn/zeitwerk/issues/111. However, those solutions require very careful inclusion and exclusion of directories from the autoloader. It's not clear that we could automate the process to detect namespaces etc. 

**Pros**: 
 * Gives exactly the directory structure we want

**Cons**: 
 * Complicated autoloader configuration
 * Non-standard Ruby/Rails file layout (will IDEs get this right?)
 * Hard to automate
 * Probably needs manual configuration when introducing new namespaces/components 

## 2. Sidecar assets in a component directory

Leave the Ruby code as is but put the sidecar assets in a component specific directory.

```
app/components
├── alert
│   ├── alert.css
│   ├── alert.html.erb
│   └── alert_controller.js
├── alert_component.rb
├── application_component.rb
├── button
│   ├── button.css
│   ├── button.html.erb
│   └── button_controller.js
├── button_component.rb
...
```

The code we'd need here would be to change the component view resolution paths to look in the appropriate sub directory. js, css likely just work - would need to check the details of parent-child Stimulus controllers etc.

**Pros**:
 * Standard Rails autoloading
 * Gets the sidecar files 'close' to the components

**Cons**:
 * Component Ruby files outside of "their" directory
 * Complicates the component view loading logic - perhaps per component
 * Doesn't solve for Ruby sidecar files like StimulusReflex

## 3. Sidecar assets in one assets directory

Leave the Ruby code as is but put the sidecar assets in an assets directory with sub directories that match the components directories.

```
app/components
├── alert_component.rb
├── application_component.rb
├── button_component.rb
├── form
│   └── text_field_component.rb 
├── form_component.rb
└──assets
    ├── alert
    │   ├── alert.css
    │   ├── alert.html.erb
    │   └── alert_controller.js
    ├── button
    │   ├── button.css
    │   ├── button.html.erb
    │   └── button_controller.js
    └── form
        ├── form.css
        ├── form.html.erb
        ├── form_controller.js
        └── text_field
            ├── text_field.css
            ├── text_field.html.erb
            └── text_field_controller.js

...
```

The code we'd need here would be a single change the component view resolution paths to look for views in the assets directory. js, css likely just work.

**Pros**:
 * Standard Rails autoloading
 * Single point change in ViewComponent for view resolution
 * Similar to Rails patterns for controller/views (though you can argue this is a Con too 😉)

**Cons**:
 * Views and assets are much further away from their components
 * Complicates the component view loading logic 
 * Doesn't solve for Ruby sidecar files like StimulusReflex

## Proposal

I'd lean towards a configuration option to enable 2 unless the actual implementation is sufficiently complicated that 3 looks more appropriate.

I'd love for 1 to work after a lot of experimentation I can't see a clean way to bundle it as part of the gem that covers all reasonable use cases without a lot of manual configuration.

**Comment by jonspalmer** [comment]
ping @jaredcwhite, @rosendi, @nicolas-brousse, @joelhawksley, @joelmoss

Would love to hear your comments and thoughts given you've been deep in the prior conversations and likely have real world experience and thoughts of the pros & cons.

**Comment by joelmoss** [comment]
Solution 2 is pretty much exactly what I've been using for over a year now in a current production app, and it works nicely. Never had any issues, and it's clear where everything is.

I'm not actually using ViewComponent, but looking to integrate it, so I obviously want to keep the structure I already have.

One difference between this and my current setup, is the naming of the assets. You propose naming these identical to the component name, but I use `index`. eg. `app/components/button/index.html.erb` and `app/components/button/index.css`.

Index is obviously a well known convention, and avoids duplicating the name everywhere. I also find it easier to identify other files that may exist in the same directory, such as those which are imported (JS), or other related files.

**Comment by nicolas-brousse** [comment]
Hi @jonspalmer

Solution 2 sounds the better for me, with the current state of this gem and Rails autoloading.  
Also, it struture is simple enough if we need to migrate from 2 to 1. If we found a way to achive it in the future.

## Solutions
### 1. Use Autoloader

After having working on this several hours too, I confirm that it's not clean enough as solution to be considered. At least for now.

### 2. Sidecar assets in a component directory

The last time I've worked on structuring components with `view_component`, I've considered this structure too. Sounds as a good compromise IMO.

**About cons**:

> - Component Ruby files outside of "their" directory

I guess it's a small cons.

> - Complicates the component view loading logic - perhaps per component

Does it complicate it that much?

> - Doesn't solve for Ruby sidecar files like StimulusReflex

I think I've missed some conversation about this. What is expected with StimulusReflex?

### 3. Sidecar assets in one assets directory


**About cons**:

> - Views and assets are much further away from their components

When we work in controllers and views, I think we are not often working on both files at the same time. But for the components it may be the case for components, since in components we work in a smaller piece.

> - Complicates the component view loading logic

Same question that for solution 2.

> - Doesn't solve for Ruby sidecar files like StimulusReflex

Same question that for solution 2.
