### ISSUE TITLE
View component is significantly slower than partials

### ISSUE THREAD

**Issue by bunnymatic** [github/view_component#345]
`ViewComponent` is slow - roughly 3x slower than using plain rails partials (see spot benchmarking below).   In a recent project I worked on, which heavily leveraged `ViewComponents`, we're finding that the app is very slow.  We've been looking at other optimizations but the template rendering seems to be where most of the time is spent (on pages that have many components) and we'd love to not have to replace `ViewComponents` with something else if we don't have to.

### Steps to reproduce

I built a little Rails app to test this in isolation.  It includes 4 pages each which render a very simple chunk of html that includes the filename of the template.  These pages take a `count` parameter so you can easily try rendering lots of partials (not unlike what I've seen in the aforementioned project).  The 4 rendering methods are:
* `ViewComponent`
* `Rcode5::Component` - this is a hand rolled equivalent to `ViewComponent` which was mostly an exercise to see how simple one could make a component system.
* standard Rails partials
* standard Rails partials leveraging the `collection:` parameter.

To see the speed difference between these methods:
* clone the app https://github.com/bunnymatic/rails-playtime/ and use branch `chores/view-component-benchmarking` (or PR https://github.com/bunnymatic/rails-playtime/pull/8)
* `bin/setup`
* `bundle exec rails s`
* open http://localhost:3000?count=100
* click through the nav and notice the timing (from `rack_mini_profiler`) in the top left corner on each page.
* you should see that the timing compared for these methods is roughly 70:35:25:2.5 (in the same order as the list above) meaning `ViewComponent` renders 2x slower than my home grown version, ~3x slower than simple partials, and ~30x slower than when you render partials and leverage the `:collection` param.

### Expected behavior

ViewComponent should be at least as fast as my dumb homegrown version or at least closer to the rendering speed of Rails partials.

### Actual behavior

I ran the app locally (MacBookPro 2015 2.5 GHz i7 16GB) and pull the following from my Rails development logs.

Using a simple partial in a loop
```
Started GET "/partials?count=400" for ::1
Completed 200 OK in 225ms (Views: 224.0ms | ActiveRecord: 0.0ms)
Completed 200 OK in 233ms (Views: 232.8ms | ActiveRecord: 0.0ms)
Completed 200 OK in 222ms (Views: 221.9ms | ActiveRecord: 0.0ms)
```

Using `render partial:` with `collection:`
```
Started GET "/partials_collection?count=400"
Completed 200 OK in 27ms (Views: 26.4ms | ActiveRecord: 0.0ms)
Completed 200 OK in 38ms (Views: 37.8ms | ActiveRecord: 0.0ms)
Completed 200 OK in 26ms (Views: 25.3ms | ActiveRecord: 0.0ms)
```

Using a simple `ViewComponent`
```
Started GET "/view_components?count=400"
Completed 200 OK in 698ms (Views: 697.7ms | ActiveRecord: 0.0ms)
Completed 200 OK in 734ms (Views: 732.8ms | ActiveRecord: 0.0ms)
Completed 200 OK in 723ms (Views: 722.8ms | ActiveRecord: 0.0ms)
```

Using a homegrown `ViewComponent`-like system (`Rcode5::Component` - just built into this app for comparison/testing/learning):
```
Started GET "/?count=400"
Completed 200 OK in 374ms (Views: 372.9ms | ActiveRecord: 0.0ms)
Completed 200 OK in 479ms (Views: 478.6ms | ActiveRecord: 0.0ms)
Completed 200 OK in 375ms (Views: 374.3ms | ActiveRecord: 0.0ms)
```

### System configuration
**Rails Version**: 5.2.4.2 (and I've seen similar performance on Rails 6.0.x)

**Ruby version**: 2.6.6

**Gem version**: 3.0.3

**Comment by simonrand** [comment]
Hey @bunnymatic so this peaked my interest as we're using ViewComponent _because_ of its speed..

First thing I'd say is that running these comparisons in the Rails `development` environment is not will not give an accurate reflection of things here - specifically because of this line:https://github.com/github/view_component/blob/8fb33025793fd51890098913ed794d3f0d2734ee/lib/view_component/base.rb#L193

By default in`config/environments/development.rb` Rails sets `config.cache_classes = false`, which results in `ActionView::Base.cache_template_loading` being `false`, and because ViewComponents are Ruby classes, this means that in development any component is being recompiled on _every_ use - so in your example where count = 400, it's essentially be instantiated from scratch 400 times..

Out of interest I pulled down your repo, and just set `config.cache_classes = true` (no other changes) in `development.rb`, restarted the app and got these results on the first 5 loads of `/view_components?count=400`:

```
Started GET "/view_components?count=400"
# first time use of the component pre-compiles the template for future use
Completed 200 OK in 231ms (Views: 230.1ms | ActiveRecord: 0.0ms) 
Completed 200 OK in 11ms (Views: 10.5ms | ActiveRecord: 0.0ms)
Completed 200 OK in 9ms (Views: 8.3ms | ActiveRecord: 0.0ms)
Completed 200 OK in 8ms (Views: 7.2ms | ActiveRecord: 0.0ms)
Completed 200 OK in 7ms (Views: 7.1ms | ActiveRecord: 0.0ms)
```

You might also look into using the (relatively new) collection rendering option https://github.com/github/view_component#rendering-collections which can help make rendering collections a bit cleaner

**Comment by joelhawksley** [comment]
@bunnymatic thank you for taking the time to file this issue and to build this benchmark! 

This is a great starting point for us to look into some performance optimizations. 

One thing I'd be curious about here is whether this benchmark was run in production or development mode. ViewComponent has a significant amount of optimization that only run in production mode.

I see @simonrand has beat me to responding here ❤️ 

This all being said, I think we need to have an automated benchmark in this project to make sure new changes do not negatively affect performance. Would you be up for coming up with a CI benchmark for the project?

**Comment by jonspalmer** [comment]
@bunnymatic I second what @joelhawksley said. It's great to have some focus on benchmarks and performance. 

A word of caution on performance in general. I tend to get a bit uneasy when we think about performance in too narrow a way. For example, there are real world examples where we would render 100s of things with partials or view components. If you compare just the rendering then you might see large differences "approach X n times slower than approach Y". However, often missed in that analysis is that reading and organizing the data for those 100s of things typically dominates the performance by an order of magnitude or two. That is "if reading 100 records from the database takes 500ms how much does it matter the rendering them takes 5ms vs 50ms?"

All that said we want ViewComponents to be fast and stay fast as we add features to it so I'm excited to see us move this forward.

**Comment by jonspalmer** [comment]
Oh man had no intention of closing this. Hit the wrong button without enough ☕ in my system.

**Comment by bunnymatic** [comment]
@jonspalmer I realize these examples are super narrow.  On some level, I was trying to make it super narrow by looking at things without a database or anything else just to look at rendering speed.  It was a starting point.  

It had not occurred to me how different the cache story is different in development/production.  Though I knew that in my head, I think I didn't realize it'd be so significant.

It's great to see that my supposition is off.   I guess we need to go back to the app and try to tune things because we have a few pages which seem to spend nearly 90% of their time rendering.   And because we are using ViewComponent heavily, we thought that might be it.  We'll do some more benchmarking (and in prod as much as possible) and hopefully we can find the issue.

Thanks for the responses @simonrand @joelhawksley @jonspalmer

**Comment by Dru-dot** [comment]
> `ViewComponent` is slow - roughly 3x slower than using plain rails partials (see spot benchmarking below). In a recent project I worked on, which heavily leveraged `ViewComponents`, we're finding that the app is very slow. We've been looking at other optimizations but the template rendering seems to be where most of the time is spent (on pages that have many components) and we'd love to not have to replace `ViewComponents` with something else if we don't have to.
> 
> ### Steps to reproduce
> I built a little Rails app to test this in isolation. It includes 4 pages each which render a very simple chunk of html that includes the filename of the template. These pages take a `count` parameter so you can easily try rendering lots of partials (not unlike what I've seen in the aforementioned project). The 4 rendering methods are:
> 
> * `ViewComponent`
> * `Rcode5::Component` - this is a hand rolled equivalent to `ViewComponent` which was mostly an exercise to see how simple one could make a component system.
> * standard Rails partials
> * standard Rails partials leveraging the `collection:` parameter.
> 
> To see the speed difference between these methods:
> 
> * clone the app https://github.com/bunnymatic/rails-playtime/ and use branch `chores/view-component-benchmarking` (or PR [bunnymatic/rails-playtime#8](https://github.com/bunnymatic/rails-playtime/pull/8))
> * `bin/setup`
> * `bundle exec rails s`
> * open http://localhost:3000?count=100
> * click through the nav and notice the timing (from `rack_mini_profiler`) in the top left corner on each page.
> * you should see that the timing compared for these methods is roughly 70:35:25:2.5 (in the same order as the list above) meaning `ViewComponent` renders 2x slower than my home grown version, ~3x slower than simple partials, and ~30x slower than when you render partials and leverage the `:collection` param.
> 
> ### Expected behavior
> ViewComponent should be at least as fast as my dumb homegrown version or at least closer to the rendering speed of Rails partials.
> 
> ### Actual behavior
> I ran the app locally (MacBookPro 2015 2.5 GHz i7 16GB) and pull the following from my Rails development logs.
> 
> Using a simple partial in a loop
> 
> ```
> Started GET "/partials?count=400" for ::1
> Completed 200 OK in 225ms (Views: 224.0ms | ActiveRecord: 0.0ms)
> Completed 200 OK in 233ms (Views: 232.8ms | ActiveRecord: 0.0ms)
> Completed 200 OK in 222ms (Views: 221.9ms | ActiveRecord: 0.0ms)
> ```
> 
> Using `render partial:` with `collection:`
> 
> ```
> Started GET "/partials_collection?count=400"
> Completed 200 OK in 27ms (Views: 26.4ms | ActiveRecord: 0.0ms)
> Completed 200 OK in 38ms (Views: 37.8ms | ActiveRecord: 0.0ms)
> Completed 200 OK in 26ms (Views: 25.3ms | ActiveRecord: 0.0ms)
> ```
> 
> Using a simple `ViewComponent`
> 
> ```
> Started GET "/view_components?count=400"
> Completed 200 OK in 698ms (Views: 697.7ms | ActiveRecord: 0.0ms)
> Completed 200 OK in 734ms (Views: 732.8ms | ActiveRecord: 0.0ms)
> Completed 200 OK in 723ms (Views: 722.8ms | ActiveRecord: 0.0ms)
> ```
> 
> Using a homegrown `ViewComponent`-like system (`Rcode5::Component` - just built into this app for comparison/testing/learning):
> 
> ```
> Started GET "/?count=400"
> Completed 200 OK in 374ms (Views: 372.9ms | ActiveRecord: 0.0ms)
> Completed 200 OK in 479ms (Views: 478.6ms | ActiveRecord: 0.0ms)
> Completed 200 OK in 375ms (Views: 374.3ms | ActiveRecord: 0.0ms)
> ```
> 
> ### System configuration
> **Rails Version**: 5.2.4.2 (and I've seen similar performance on Rails 6.0.x)
> 
> **Ruby version**: 2.6.6
> 
> **Gem version**: 3.0.3

**Comment by fsateler** [comment]
Hi,

I'd like to request this issue be reopened. 

@simonrand is correct that on production this particular problem is not relevant due to cache_classes. However, I'd like to contrast ViewComponent behavior with that of ActionView.

ViewComponent will on development *never* cache templates, and thus they are always recompiled. If a given component is rendered in a loop (imagine a component that is rendered on a table), the recompile time starts to add up.

OTOH, ActionView caches, but when `ActionView::Resolver.caching?` is false, it registers a callback to clear the cache on each request:

https://github.com/rails/rails/blob/3cd1b19ff2e49642191c598d620b87ffe5ec6cda/actionview/lib/action_view/railtie.rb#L96-L99


Thus, the optimal solution would be to do something similar: invalidate the cache on each request.

I think something like:

```ruby
module ViewComponent::TemplateCache
  mattr_reader :cache, instance_reader: false, instance_accessor: false do
    Set.new
  end
  module_function

  def register(clazz)
    cache << clazz
  end

  def invalidate!
    cache.each do |clazz|
      cache.compiled = false # The compiled= writer needs creating in Base
    end
    cache.clear!
  end
end
```

And then registering a callback on the executor that calls `TemplateCache.invalidate!`

**Comment by joelhawksley** [comment]
@fsateler fantastic! Would you be willing to kick off a PR to implement that behavior?

**Comment by pboling** [comment]
Is there any reason this hasn't been merged?
