### ISSUE TITLE
Helpers and view_context are nil

### ISSUE THREAD

**Issue by mickenorlen** [github/view_component#346]
Helpers and view_context are nil in `user_component.rb`. Am I doing something wrong?

### Steps to reproduce

I'm following docs: https://github.com/github/view_component#using-helpers

```RUBY
class UserComponent < ViewComponent::Base
  def initialize
    puts 'USERCOMP'
    puts helpers
    puts @view_context
    puts @helpers
  end
end

```

`application.html.erb`
```RUBY
<%= UserComponent.new %>
```

### Expected behavior
Output view context

### Actual behavior
`logs`
```RUBY
"USERCOMP"
nil
nil
nil
```

### System configuration
**Rails version**:
6.0.3

**Ruby version**:
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]

**Gem version**:
2.5.1

**Comment by joelhawksley** [comment]
@mickenorlen thank you for filing this issue!

First, an explanation:

When passing a component instance to `render`, Rails calls `render_in` on the instance, passing in the view context, which on our case happens in `Base`:

https://github.com/github/view_component/blob/master/lib/view_component/base.rb#L43

We then use that view context to set the `view_context` and `helpers` accessors. 

In other words, those properties are coupled to the rendering, not instantiation of components, so they are not available on component instances.

What were you hoping to accomplish by accessing these properties on a component instance?

**Comment by mickenorlen** [comment]
Thanks for a quick reply (even in the weekend! Hope you get some good rest too :))

Ok that makes sense, I guess i just got confused :) In the end everything is working when called from render!
