### ISSUE TITLE
Incorrect rendering when content is yielded from a partial

### ISSUE THREAD

**Issue by mattr** [github/view_component#362]
### Steps to reproduce

View component content is wrapped in a partial. A sample use case is to provide common wrapping for e.g. a panel.

[Sample rails app](https://github.com/mattr/view_components_test)

### Expected behavior

Component content is rendered within the context of the partial.

Given:
```erb
# app/views/shared/_yielded.html.erb
<div class="my-partial">
  <%= yield %>
</div>

# app/views/my_component.html.erb
<%= render "shared/yielded" do %>
  <%= "My Content" %>
<% end %>
```
It should render:
```html
<div class="my-partial">
My Content
</div>
```
Given:
```erb
<%= render "shared/yielded" do %>
<% "My Content" %>
<% end %>
```
It should render:
```html
<div class="my-partial">
</div>
```

### Actual behavior

Given:
```erb
<%= render "shared/yielded" do %>
  <%= "My Content" %>
<% end %>
```
It renders:
```html
My Content
<div class="my-partial">
</div>
```
Given
```erb
<%= render "shared/yielded" do %>
<% "My content" %>
<% end %>
```
It renders:
```html
<div class="my-partial">
My content
</div>
```
Component content is only rendered in context when using an ERb eval block (`<% %>`). Using render blocks or straight HTML causes the component content to be rendered _before_ the partial.

### System configuration
**Rails version**: 6.0.3.1

**Ruby version**: 2.6.3

**Gem version**: 2.7.0 (also 2.5.1)

**Comment by joelhawksley** [comment]
@BlakeWilliams might this issue be at all related to https://github.com/github/view_component/pull/240?
