### ISSUE TITLE
uninitialized constant #<Class:0x00007ff2ec2db270>::DisplayDateComponent

### ISSUE THREAD

**Issue by almokhtarbr** [github/view_component#368]
### Steps to reproduce

gem "view_component"

config/application.rb
require "view_component/engine"

Implementation
A ViewComponent is a Ruby file and corresponding template file with the same base name:

```app/components/display_date_component.rb:

class DisplayDateComponent < ViewComponent::Base
  def initialize(date:)
    @date  = date
  end
end

app/components/display_date_component.html.erb:

<div class="date">
  Today's date is <%= @date %>
</div>

Rendered in a view as:

<%= render(DisplayDateComponent.new(date: Date.today)) %>

Returning:

```
NameError in Home#index
Showing /.../app/views/home/index.html.erb where line 3 raised:

uninitialized constant #<Class:0x00007ff2ec2db270>::DisplayDateComponent
```
### Expected behavior
<!-- Tell us what should happen -->

rendering the component

### Actual behavior
<!-- Tell us what happens instead -->
```
NameError in Home#index
Showing /.../app/views/home/display_date_component where line 3 raised:

uninitialized constant #<Class:0x00007ff2ec2db270>::DisplayDateComponent
```

### System configuration
**Rails version**:
Rails 6.0.3.1
**Ruby version**:
ruby 2.6.5
**Gem version**:
3.1.4

**Comment by joelhawksley** [comment]
@almokhtar thank you for the bug report! At first glance, I can't see anything obviously wrong with what you have. You do have the gem version in your report listed as 3.1.4, which is beyond what we have released (we're on 2.7.0). 

Might you be able to clarify what version you're using and perhaps provide a more thorough stack trace for the error?

**Comment by almokhtarbr** [comment]
@joelhawksley Sorry It Was My Mistake (in Configuration), Thank you.

**Comment by askdesigners** [comment]
@almokhtarbr could you write what you did to solve it? I have the same issue, and now I know it's fixable, but not now to fix it :)

**Comment by askdesigners** [comment]
Thanks!
