### ISSUE TITLE
Testing with render_inline fails when render_monkey_patch_enabled is set to false

### ISSUE THREAD

**Issue by czj** [github/view_component#396]
We are running Rails < 6.1 and wanted to use the `render_component` syntax for clarity, but also speed and search-and-replace-ability in our codebase.

### Steps to reproduce

- Create a Rails 6.0.3.2 application
- Define that you don't want the `render` method monkey-patch

```ruby
Rails.application.config.view_component.render_monkey_patch_enabled = true
```

- Create a component like this one:

```ruby
# frozen_string_literal: true

module Eshop
  class ShowroomClosureAlertComponent < ApplicationComponent
    def initialize(showroom_closed:)
      @showroom_closed = showroom_closed
    end
  end
end
```

```erb
<% if showroom_closed %>
  <div class="alert alert-info text-center">
    Something in French from our website.
  </div>
<% end %>
```

- Create associated test like this one:

```ruby
require "test_helper"

module Ecommerce
  class ShowroomClosureAlertComponentTest < ViewComponent::TestCase
    test "component renders something useful" do
      node = render_inline ShowroomClosureAlertComponent.new(showroom_closed: false)
      assert_empty node.inner_html
    end
  end
end
```

### Expected behavior

The method `render_inline`is supposed to use `render_component` because we have disabled `render` monkey-patch.

### Actual behavior

The tests raise an exception because `render_inline` tries to use `render` :

```
ArgumentError: '#<Ecommerce::ShowroomClosureAlertComponent:0x00000001236774a0 @showroom_closed=true>' is not an ActiveModel-compatible object. It must implement :to_partial_path.
```

### System configuration

- Rails 6.0.3.2
- Ruby 2.6.6
- Gem 3.1.4
- Bundler 2.1.4

**Comment by czj** [comment]
To me it looks like a fix would require the test helper https://github.com/github/view_component/blob/master/lib/view_component/test_helpers.rb to define `render_inline` differently if the monkey patch is not applied.

### Actual

```ruby
    def render_inline(component, **args, &block)
      @rendered_component = controller.view_context.render(component, args, &block)

      Nokogiri::HTML.fragment(@rendered_component)
    end
```

### Without the monkey patch

```ruby
def render_inline(component, **args, &block)
  @rendered_component = controller.view_context.render_component(component, args, &block)

  Nokogiri::HTML.fragment(@rendered_component)
end
```

**Comment by joelhawksley** [comment]
@czj that looks great to me! Mind opening a PR?

**Comment by czj** [comment]
Do you mind if I use directly `render_component` in the `render_inline` helper ? Because we are testing the component in isolation, it assume would not break anything and the test helper's code would remain very simple.
