### ISSUE TITLE
Default directory structure

### ISSUE THREAD

**Issue by Soleone** [github/view_component#401]
## Feature request

- By default put all files belonging to a component into the same directory
- There should be no file leaking out of that directory
- Ensure load path is set up (or instructions easily available) to load files recursively from subdirectories
- Get rid of the `_component` suffix, it seems verbose when it should be clear from the app/components context that we're dealing with component files here.

![image](https://user-images.githubusercontent.com/2923/87278623-eeedb500-c4b2-11ea-8ffb-9a10e1257457.png)

### Motivation

I was struggling setting up a sensible directory structure using ViewComponent and Stimulus. I am a big fan of putting each and every file belonging to a component into a folder.

Be default currently ViewComponent seems to prefer to put files across multiple components into the same high level app/components folder. I would prefer a more opinionated approach instead of giving too much freedom requiring customization.

I was very close to setting up a way where even the Stimulus' controller js files are living in the same subdirectory, but eventually I had to give up because I couldn't figure out from any instructions how to recursively load across sub-directories without having to manually specify each component folder name manually.

I tried this:

```
const application = Application.start()
const context = require.context("controllers", true, /.js$/)
const context_components = require.context("../../components/", true, /(.*)\/.+\.js$/)
application.load(
  definitionsFromContext(context).concat(
    definitionsFromContext(context_components)
  )
)
```

But I had to change this line:

```
const context_components = require.context("../../components/", true, /(.*)\/.+\.js$/)
```

to actually refer to my component subfolder or it wouldn't work, like this:

```
const context_components = require.context("../../components/ticker", true, /(.*)\/.+\.js$/)
```

I assume there is some basic javascript here that I am missing to make this work for many subfolders at once without having to add each new component folder explicitly, but even with that solution added to the Readme, I feel like forcing by default to store _all_ components files into its own folder makes things more manageable and intuitive.

**Comment by joelhawksley** [comment]
@Soleone thanks for taking the time to file this request! While this is a topic that has been discussed before, I'm not convinced that what we have established as a convention for organizing components is the best solution. 

However, it's proven difficult to stray too far from what we have now due to how Ruby/Rails expect constants to be defined based on the directory structure. In keeping with the library's [design philosophy](https://github.com/github/view_component#design-philosophy), we've ended up with what we have now. I'm always open to new approaches and ideas, and would love to see a PR that opens up the possibility of supporting what you're trying to do.

**Comment by jonspalmer** [comment]
@Soleone did you see the Sidecar directory option https://github.com/github/view_component#sidecar-directory? It's not quite what you describe but does at least get the js, css assets into their own folder. As @joelhawksley mentioned going further than this has proved tricky due to Ruby/Rails expectations/conventions.

**Comment by Soleone** [comment]
Thanks for getting back so quickly, much appreciated! I definitely agree with that design philosophy.

> However, it's proven difficult to stray too far from what we have now due to how Ruby/Rails expect constants to be defined based on the directory structure.

> going further than this has proved tricky due to Ruby/Rails expectations/conventions.

1. Could you be so kind to clarify in an example what exactly the underlying issue here is? Is it because of Zeitwerk autoloading? 

2. Could the naming structure used in [this article](https://fugu.dev/2020-04-15-working-with-view-component-and-stimulus-part-1/) be a potential approach?

> did you see the Sidecar directory option https://github.com/github/view_component#sidecar-directory?

Yes, I set that up and it worked for the view template and css, but I could not get it to work for the Stimulus.js controller, not sure what configuration is necessary exactly there to support multiple subfolders in app/components.

At the very least I would like to see view template, css and js files being encapsulated in a directory, adding the .rb file as well makes sense too though, one whole directory that includes everything. Like a gem. I am imagining on a scale of 50 components this makes it look cleaner.

So priority for me right now is to at least get proper Stimulus.js instructions on how to put the js controller file into the subdirectory which the rb file added as well as a bonus objective.

Overall I feel like there should be one organizational method picked as a convention eventually and not give people too much freedom on how to organize their file structure, that is how I interpret the Rails way. But I understand we might not be fully there yet and still in an exploratory phase.

**Comment by Soleone** [comment]
So this file structure is the best (most encapsulated) structure I was able to achieve right now. Currently only  tested with a single component, not 2+ yet:

![image](https://user-images.githubusercontent.com/2923/87489205-6c7b0780-c610-11ea-8020-6f043a28594b.png)


**app\javascript\packs\application.js**
```
// ...

import { Application } from "stimulus"
import { definitionsFromContext } from "stimulus/webpack-helpers"

function importAll(r) {
  r.keys().forEach(r)
}

importAll(require.context("../../components", true, /\.css$/))

const application = Application.start()
const componentContext = require.context("../../components/block", true, /\.js$/);
application.load(definitionsFromContext(componentContext));
```

**app\components\block\component.rb**
```
module Block
  class Component < ViewComponent::Base
    attr_reader :text

    def initialize(text:)
      @text = text
    end
  end
end
```

**app\views\home\show.html.erb**
```
<%= render Block::Component.new(text: "Inside") %>
```

### Disadvantages

1. Somehow have to specify the whole component directory for loading the javascript files via ` require.context("../../components/block", true, /\.js$/)`, I don't quite understand why simply `"../../components"` would not work there.

2. The Ruby class has to be called `Component`, once you have a few `Component` classes in your project, as opposed to `BlockComponent` or `Block` it might get a bit confusing because you always need to be wary of the module / subdirectory name.

3. The view has to be called `component.html.erb`. `block.html.erb` would be more intuitive probably.

4. The CSS file can be called anything right now, not sure if there is a conflict once there are 2+ components in the project. But it would probably be most intuitive to name it exactly the same as the ruby file and view. But again, `component.css` instead of `block.css` does not seem optimal.

The problem for points 2 - 4 is the Ruby file name which needs to match the directory structure. It's just that e.g. `Block::Block` or `Block::BlockComponent` is maybe a bit too verbose, but that would allow the filenames of css and javascript and view to make more sense.

**Comment by jesster2k10** [comment]
Hey there, I was thinking a file structure like this might make the most sense. It's basically what the [Komponent](https://github.com/komposable/komponent) library does and it keeps things nice and neat (in my opinion).

![Screenshot 2020-07-29 at 13 47 30](https://user-images.githubusercontent.com/6454286/88801757-0d85c880-d1a2-11ea-9141-19996d8bf190.png)

This probably won't work, I just re-arranged things until I found what made the most sense IMO. The `_component` prefix is unnecessary within the context of the folder and having things all in one place makes murch more sense (organisationally).

**Comment by jesster2k10** [comment]
Update: so by renaming the template file to `button_component.html.erb` I was able to get the single component rendered.
I created a little helper file as well to make rendering the components more "magical".

I'm using atomic design, so I have my files split up into atoms, molecules, organisms etc.
My helper file looks a little bit like this:

```ruby
module ComponentHelper
  def component(path, *args, **kwargs)
    name = path
      .to_s
      .split('/')
      .last

    class_name = path.to_s.classify
    name = "#{name}Component".classify
    class_name = "#{class_name}::#{name}"
    component_class = class_name.constantize

    render component_class.new(*args, **kwargs)
  end

  def atom(path)
    component "atoms/#{path}"
  end
end
```

and you can use it like so to render out the button

```ruby
<%= atom :button, title: "Hello" %>
```

**Comment by kimadactyl** [comment]
I'm just doing a refactoring into ViewComponent and have to agree with this issue - for me I want everything relating to the component in one directory, its a bit weird to have stuff in different places. I think the OP is the best solution for me.

Is this something currently possible?

**Comment by joelhawksley** [comment]
@kimadactyl yes, you can make a separate namespace for each component, such as `My::Component` or `MyComponent::Component` which will allow you to store all files for a single component in its own directory.
