### ISSUE TITLE
ViewComponent as replacement of ActionView

### ISSUE THREAD

**Issue by mollerhoj** [github/view_component#410]
## Feature request

Let's improve functionality for skipping ActionView (classic `app/views` rendering) entirely. This includes:
- https://github.com/github/view_component/issues/391 (`render` in controller should respect layout)
- Allowing using a different name than "Component" (As it is a strange name for objects that represent entire views)
- Perhaps supporting placing Components directly in the `views/` folder, e.g. (`app/views/users/show.rb`)

Essentially, this would move rails rendering closer to the `View` module in Phoenix https://hexdocs.pm/phoenix/Phoenix.View.html

### Motivation

Allowing users to bypass ActionView altogether and use ViewComponents directly yields the following benefits:
- Developers only need to consider 1 rendering option.
- All views gains the testing and maintainability benefits provided by ViewComponents.

**Comment by joelhawksley** [comment]
@mollerhoj thanks for filing this issue!

> Allowing using a different name than "Component"

While it's been _convention_ to have ViewComponents end in `Component`, it's not a requirement! Feel free to name them however you like 😄 

> Perhaps supporting placing Components directly in the views/ folder 

I'd love to see an exploration of this agains Rails master. We tried this approach when we were first building the library and I think we ended up running into some issues, but I honestly forget what they were. As ViewComponent is not part of Rails itself, I'm generally hesitant to make use of the `views` folder.
