### ISSUE TITLE
Alias []= to with

### ISSUE THREAD

**Issue by joshmn** [github/view_component#413]
Hi Joel and contributors, thanks for this. Fun watching the evolution since the Railsconf talk.
 
## Feature request

```
module ViewComponent
  class Base < ActionView::Base
    alias :[]= :with
  end
end
```

### Motivation

I'm finding myself using a lot of nesting like so:

```
<%= render(PageComponent.new) do |page_component| %>
  <% page_component.with(:header, "Pets") %>
  <% page_component.with(:body) do  %>
    <%= render(CardComponent.new) do |card_component| %>
      <% card_component.with(:header, "New pet") %>
      <% card_component.with(:body) do %>
        <%= render 'form' %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
```

When I was first writing these, I had some weird instinct to use `page_component[:header] = "Pets"` only to be hit with UndefinedMethod. 

```
<%= render(PageComponent.new) do |page_component| %>
  <% page_component[:header] = "Pets" %>
  <% page_component.with(:body) do  %>
    <%= render(CardComponent.new) do |card_component| %>
      <% card_component[:header] = "New pet" %>
      <% card_component.with(:body) do %>
        <%= render 'form' %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
```

So in true Ruby fashion I aliased `with` to `[]=`.

Can make a PR if this looks good. I understand if we want to keep the API more focused, though.

**Comment by joelhawksley** [comment]
@joshmn I'd love to hear more about what you were thinking here ❤️

**Comment by joshmn** [comment]
@joelhawksley I just made an oopsie edit :) 

I didn't think it through (early morning codeday here without coffee = less than stellar thinking) but my idea was to cut down on the terseness of `with` when passing `value`. 

Obviously, passing a block to `[]` looks unnatural so I quickly erased that idea from my brain. :)

**Comment by joelhawksley** [comment]
@joshmn thanks for the follow up!

We're definitely thinking about the we use as part of introducing [Slots](https://github.com/github/view_component#slots-experimental), the successor to content areas. Perhaps you could give them a shot and let us know what you think?

**Comment by joshmn** [comment]
Will do! :) Thanks Joel :)

**Comment by Artnoc1** [comment]
> Hi Joel and contributors, thanks for this. Fun watching the evolution since the Railsconf talk.
> ## Feature request
> 
> ```
> module ViewComponent
>   class Base < ActionView::Base
>     alias :[]= :with
>   end
> end
> ```
> 
> ### Motivation
> 
> I'm finding myself using a lot of nesting like so:
> 
> ```
> <%= render(PageComponent.new) do |page_component| %>
>   <% page_component.with(:header, "Pets") %>
>   <% page_component.with(:body) do  %>
>     <%= render(CardComponent.new) do |card_component| %>
>       <% card_component.with(:header, "New pet") %>
>       <% card_component.with(:body) do %>
>         <%= render 'form' %>
>       <% end %>
>     <% end %>
>   <% end %>
> <% end %>
> ```
> 
> When I was first writing these, I had some weird instinct to use `page_component[:header] = "Pets"` only to be hit with UndefinedMethod.
> 
> ```
> <%= render(PageComponent.new) do |page_component| %>
>   <% page_component[:header] = "Pets" %>
>   <% page_component.with(:body) do  %>
>     <%= render(CardComponent.new) do |card_component| %>
>       <% card_component[:header] = "New pet" %>
>       <% card_component.with(:body) do %>
>         <%= render 'form' %>
>       <% end %>
>     <% end %>
>   <% end %>
> <% end %>
> ```
> 
> So in true Ruby fashion I aliased `with` to `[]=`.
> 
> Can make a PR if this looks good. I understand if we want to keep the API more focused, though.
