### ISSUE TITLE
Sidecar directory/view dont render css/js files

### ISSUE THREAD

**Issue by thadeu** [github/view_component#425]
### Steps to reproduce
I have an structure similar this.

<img width="371" alt="Screen Shot 2020-07-28 at 14 49 07" src="https://user-images.githubusercontent.com/77889/88702331-8ec95680-d0e1-11ea-9c9e-9951ade3de68.png">

### Expected behavior
I expected render all files this component, JS/CSS/HAML

### Actual behavior
But, assets do not render, only `.haml`

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.6

**Gem version**: 1.7.3

**Comment by jaredcwhite** [comment]
@thadeu Are you importing the component assets using Webpacker? There's a setup step that's required to get it to work. (And you'll beed to import the CSS file within the JS file so it's added to the dependency graph.)

https://github.com/github/view_component#sidecar-assets-experimental

**Comment by thadeu** [comment]
@jaredcwhite Yes, I'm importing assets using webpacker as well. But CSS files dont compile, even if that import inside the JS file

**Comment by Lomig** [comment]
Same problem here.
Did you find any proper solution?

**Comment by Lomig** [comment]
> @jaredcwhite Yes, I'm importing assets using webpacker as well. But CSS files dont compile, even if that import inside the JS file

Heya https://github.com/thadeu
Same problem here. Did you find any proper solution?
