### ISSUE TITLE
Haml error: ActionView::Template::Error (undefined method `capture_haml' ...)

### ISSUE THREAD

**Issue by spdawson** [github/view_component#426]
### Steps to reproduce

Minimal reproduction [repository](https://github.com/spdawson/view_component_haml_error)

### Expected behavior

Component should render without incident, when using Haml template.

### Actual behavior

Error is raised:

```
ActionView::Template::Error (undefined method `capture_haml' for #<#<Class:0x00007fc4fcb73338>:0x00007fc4fcaca440>
Did you mean?  capture_with_haml):
```

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: 2.7.1

**Gem version**: 2.18.0

**Comment by joelhawksley** [comment]
@spdawson thank you for the report! We definitely want to make sure `haml` works with ViewComponent. Would you be willing to write a PR with a test case for this issue?

**Comment by spdawson** [comment]
@joelhawksley I've added a test case in #428

**Comment by joelhawksley** [comment]
Thanks @spdawson! Would you be up for pairing with me on this one? Send me an email: joelhawksley@github.com

**Comment by dmarcoux** [comment]
I would be willing to help if it's needed. I plan to use view components with Haml at work. If Haml doesn't work with view components right now, it's a blocker. Let me know how I can help.

**Comment by joelhawksley** [comment]
@dmarcoux send me your pairing availability for the next week to joelhawksley@github.com ❤️

**Comment by dmarcoux** [comment]
> @dmarcoux send me your pairing availability for the next week to [joelhawksley@github.com](mailto:joelhawksley@github.com) heart

Done :slightly_smiling_face:

**Comment by manuelpuyol** [comment]
hey @spdawson @dmarcoux 
I was taking a look at this issue and the [repository provided](https://github.com/spdawson/view_component_haml_error), I noticed it is using `helpers.link_to`.
As https://github.com/github/view_component/pull/428#discussion_r468713628 explained, `helpers.` is unnecessary in this situation and removing it solved the issue (at least in the provided repo)

Could you confirm that removing `helpers.` fixes the issue? Also, is there any specific reason as why you are using `helpers.`?

**Comment by spdawson** [comment]
> Could you confirm that removing `helpers.` fixes the issue? Also, is there any specific reason as why you are using `helpers.`?

Yes, removing the `helpers.` scope _does_ resolve this issue for me; thanks @dmarcoux!

**Comment by morgler** [comment]
I do get this error even without any `helpers` in my templates. My component however renders a rails form and another component within it.

default.html.erb (preview template):
```
<%= form_with model: @gig do |f| %>
  <%= render Places::EditComponent.new(form: f, attr_name: :venue) %>
<% end %>
```

edit_component.html.haml (the component itself):
```
= @form.fields_for @attr_name do |pf|
  %div{class: errors.present? ? 'has-error' : ''}
    = render Places::MapComponent.new(place: place, style: @style, fireEvent: @fireEvent)
```

The error message points to the `@form.fields_for` line.
