### ISSUE TITLE
Make previews controller extensible 

### ISSUE THREAD

**Issue by juanmanuelramallo** [github/view_component#434]
## Feature request

Make the previews controller to be extensible by allowing users to add authentication, authorization, before actions, or anything that the end user would need to meet their needs. 

### Motivation
It all started in discussion #412 
@jonspalmer came up with a good suggestion, which is to copy Devise's "parent class" feature. It will enable devs to set up a parent class if needed. 

https://github.com/github/view_component/discussions/412#discussioncomment-41084

**Comment by swanson** [comment]
:wave: Going to take a stab at this.
