### ISSUE TITLE
Add Rubocop rules for conventions

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#477]
## Feature request
Add Rubocop rules for the conventions [specified in the README](https://github.com/github/view_component#conventions).

### Motivation
Having Rubocop rules for ViewComponent conventions will help users of the gem implement components using recommended best practices.

**Comment by lfalcao** [comment]
@joelhawksley as the project uses `rubocop-github` we only need to see .rubocop.yml to discover which files/cops are being used. Adding all rules into README, will only mess it and it's one more place for taking care.

Maybe related: https://github.com/github/view_component/pull/964

**Comment by joelhawksley** [comment]
I think we can close this 👍🏻

**Comment by andyw8** [comment]
This is an old discussion, but for the benefit of anyone who stumbles across it: https://github.com/andyw8/rubocop-view_component
