### ISSUE TITLE
Slots should allow single splat parameters

### ISSUE THREAD

**Issue by khiga8** [github/view_component#494]
## Feature request
Currently slots only allow keyword/double splat parameters to be set. It would be nice if they also allowed non-keyword parameters.

### Motivation

I am envisioning a dropdown menu component with a few different toggle options. The `ButtonToggle` will render an existing button component (with some additional data attributes set). It would be nice if I can match the parameters of this slot with the button component. 
 
```.rb
class ButtonComponent < ApplicationComponent

   def initialize(*traits, **html_attributes)

```

```.rb
class DropdownMenuComponent < ApplicationComponent

  include ViewComponent::Slotable
  ...

  class BaseToggle < ViewComponent::Slot
    ...
  end

  class ButtonToggle < BaseToggle
    # It would be nice if I can match this with the button component and use *traits
    def initialize(traits: [], **html_attributes) 
     ...
    end
  end

```

**Comment by BlakeWilliams** [comment]
👋 @khiga8 thanks for the feedback! I think this is a good thing to support. We're currently working on the next iteration of slots in this discussion: #454. Would you mind adding this feedback over there?

**Comment by khiga8** [comment]
> 👋 @khiga8 thanks for the feedback! I think this is a good thing to support. We're currently working on the next iteration of slots in this discussion: #454. Would you mind adding this feedback over there?

Sure, will do :-)
