### ISSUE TITLE
Breakpoint+css shorthand combos aren't easily translated into SystemArguments

### ISSUE THREAD

**Issue by brphelps** [github/view_component#520]
https://primer.style/view-components/system-arguments#responsive-values 
is missing some common combination arguments that are in use in primer CSS, I'm not sure if there is a logical translation or mapping for them, but looking at what's in primer CSS style today:

`{prefix}-sm-{size}`
`{prefix}-md-{size}`
`{prefix}-lg-{size}`
`{prefix}-xl-{size}`

Basically, I think it's a shorthand mechanic to combine breakpoints conditionally with styles, and there's been at least one PR where flattening classes into System Arguments was deterred because it was missing.

### Expected behavior
Ideally the design language for system arguments would support a logical mapping from the two / three part styles, or support them as is -- I'm not really sure how that should be done, but having a known path from the three part css class names to System Args would be great (Maybe even worth documenting since they are 'related').

### Actual behavior
Actual behavior is that I would either turn some of the styles into system arguments and leave others in HTML ( :frankenstein: ), or just avoid moving things into system args for places that use these combined styles.

**Comment by BlakeWilliams** [comment]
closed by https://github.com/primer/view_components/pull/130
