### ISSUE TITLE
Run primer view components tests as part of CI

### ISSUE THREAD

**Issue by BlakeWilliams** [github/view_component#525]
This will help us gain more confidence that changes we make don't cause regressions.

**Comment by jonspalmer** [comment]
I'm not sure I get the motivation behind this. If Primer has tests that break because of code in this repo, not due to code in Primer VC then it says our test suite isn't complete enough and we should cover the gaps. On the other hand it would be hugely confusing if Primer VC code changes cause failures in this repo due entirely to changes in Primer VC code.

**Comment by patchwork-her** [comment]
Ok... So what is your most recent ideas and feelings upon this now? I'm up in the air on this since your initial response is yay and nay

**Comment by joelhawksley** [comment]
@jonspalmer I hope this is only a stopgap to help us identify weaknesses in the ViewComponent test suite. Due to the direction of the dependency, I think It's unlikely that a change to PVC would break the ViewComponent suite.

**Comment by BlakeWilliams** [comment]
> I'm not sure I get the motivation behind this. If Primer has tests that break because of code in this repo, not due to code in Primer VC then it says our test suite isn't complete enough and we should cover the gaps. 

I agree, I don't think primer view component tests are a replacement for test coverage in the library, but can provide a signal that we need to add more/better coverage in certain areas. We currently have 100% test coverage, but we've run into this issue where primer view components has broken a time or two because of changes to the library..

**Comment by jonspalmer** [comment]
> I think It's unlikely that a change to PVC would break the ViewComponent suite.

Architecturally that's true but suppose main branch of PVC has failing tests or its CI infrastructure breaks etc. ViewComponents suite will be failing until it's fixed. I get its all a close nit set of Github folks driving both projects but...
