### ISSUE TITLE
Rails generators configuration option for Sidecar

### ISSUE THREAD

**Issue by nakwa** [github/view_component#531]
## Feature request
It'd be nice to have a way to permanently configure view_component generators to work with the `sidecar` option
As per discussion https://github.com/github/view_component/discussions/528

### Motivation
Avoid passing the `--sidecar` option each time `rails g component` is typed and executed. 

### Implementation 
Add an option for `Rails.application.config.generators` to be defined in `config/initializers/generators.rb`

**Comment by joelhawksley** [comment]
@nakwa sorry for the delay! 

I think the closest existing solution we have to a similar problem is the `mattr_accessor` for configuring the monkey patch: https://github.com/github/view_component/blob/master/lib/view_component/base.rb#L182. 

That would allow us to do something like `config.view_component.generate_with_sidecar = true`.

**Comment by lfalcao** [comment]
Anything missing here? https://github.com/github/view_component/pull/587

**Comment by Spone** [comment]
This has been fixed by https://github.com/github/view_component/pull/1218

See https://viewcomponent.org/api.html#sidecar
