### ISSUE TITLE
Call before_render on component slots

### ISSUE THREAD

**Issue by nicolas-brousse** [github/view_component#535]
## Feature request
Having `#before_render` method available in `ViewComponent::Slot`

### Motivation

In some of our components slots we use validation and we can't use `#before_render` like for components. For now we overwrite some code like following.

```rb
class ApplicationComponent < ViewComponent::Base
  def before_render
    super

    slots.each do |_, slot_params|
      Array(instance_variable_get(slot_params[:instance_variable_name]) || []).each do |slot_instance|
        slot_instance.send(:before_render) if slot_instance.respond_to?(:before_render)
      end
    end
  end
end

module ViewComponent
  class Slot
    attr_accessor :content

    def before_render; end
  end
end
```

**Comment by joelhawksley** [comment]
@nicolas-brousse I think this makes sense. Want to get a PR going?

**Comment by nicolas-brousse** [comment]
I'll try to have a look on it

**Comment by nicolas-brousse** [comment]
@manuelpuyol Thank you for your message!

I tried the new API on a new component, but didn't update our existing components yet. I'll have a look 🙌

**Comment by manuelpuyol** [comment]
great! let me know if you need any help :)

**Comment by manuelpuyol** [comment]
@nicolas-brousse I'm closing the issue but feel free to comment if you have any questions during your component migration

**Comment by nicolas-brousse** [comment]
@manuelpuyol I just finished the conversion. I didn't used new api very well the first time so my validations wasn't called on slot components.

But since I finally understand how it must be used, then I confirm this work now without any code that overwrite `view_component` \o/

Thanks
