### ISSUE TITLE
stack level too deep

### ISSUE THREAD

**Issue by mbajur** [github/view_component#561]
I've just tried to upgrade from actionview-component (1.7.0) to view_component (both most recent released version and from git master) and opening any route results in stack level too deep error.

### Actual behaviour:

![image](https://user-images.githubusercontent.com/581569/102754797-c75a1d00-436d-11eb-880e-e48168e98863.png)

(screenshot taken on 2.6.1 cause browser hanged totally on 2.5.3)

### System configuration
**Rails version**: 5.2.4.4

**Ruby version**: 2.5.3 and 2.6.1

**Gem version**: 2.23.2

**Comment by joelhawksley** [comment]
@mbajur thank you for the bug report! Might you be able to incrementally upgrade to see which version change caused this error? Going from `1.7.0` to `2.23.2` is a pretty big jump.

**Comment by mbajur** [comment]
@joelhawksley the earliest `view_component` gem version i'm able to install from rubygems is 1.16.0 and it fails in the exact same way.

**Comment by joelhawksley** [comment]
@mbajur are you using the following line in your gemfile?

`gem "view_component", require: "view_component/engine"`

**Comment by mbajur** [comment]
that's correct

**Comment by rmacklin** [comment]
The stacktrace you shared seems to indicate a conflict between view_component's render monkey patch and another gem that's also monkey patching render (it looks like this one: https://github.com/JangoSteve/remotipart/blob/v1.4.2/lib/remotipart/render_overrides.rb#L16). Can you confirm whether or not you were also using that gem when things were working with `actionview-component`?

**Comment by mbajur** [comment]
Yes, i can confirm that. The only thing i did between working and broken state was replacing old actionview component Gemfile line with the new view_component one.

The bad part is that's an old production legacy app with tons of gems like that remotipart one and i can't really drop this dependency.

**Comment by rmacklin** [comment]
In that case, it might be that the order in which the monkey patches are loaded has changed (when using `actionview-component`, that monkey patch was probably loaded before `remotipart`'s, whereas `view_component`'s monkey patch is probably loaded after it). The most robust solution might be to disable `view_component`'s monkey patch: https://github.com/github/view_component/issues/332#issuecomment-705356441 and using `render_component` to render components.

Another thing you could try that might get your app back to loading the monkey patches in the previous order is changing:
`gem 'remotipart'` to `gem 'remotipart', require: false` in your `Gemfile` and then adding an explicit
`require 'remotipart'` in your `config/application.rb`.

**Comment by joelhawksley** [comment]
I believe @rmacklin has the right hunch here.

@mbajur one possible workaround would be to turn off the ViewComponent monkey patch (see https://viewcomponent.org/#disabling-the-render-monkey-patch-rails--61) and use `#render_component` instead. We added that configuration option just for this case.

**Comment by mbajur** [comment]
Thank you so much guys! I just tested that and it works like a breeze 🎉

**Comment by jesster2k10** [comment]
> I believe @rmacklin has the right hunch here.
> 
> @mbajur one possible workaround would be to turn off the ViewComponent monkey patch (see https://viewcomponent.org/#disabling-the-render-monkey-patch-rails--61) and use `#render_component` instead. We added that configuration option just for this case.

Hey, that link no longer works. Is there an updated one?

**Comment by rmacklin** [comment]
It looks like that section has been moved to the "Compatibility" page:
https://viewcomponent.org/compatibility.html#disabling-the-render-monkey-patch-rails--61

**Comment by jesster2k10** [comment]
I'm having this same issue using:

- view_component (2.30.0)
- rails 6.0.3

<img width="1178" alt="Screenshot 2021-04-09 at 22 45 48" src="https://user-images.githubusercontent.com/6454286/114243958-7d7d5d00-9985-11eb-988b-22f3535498c0.png">

<img width="1183" alt="Screenshot 2021-04-09 at 22 45 53" src="https://user-images.githubusercontent.com/6454286/114243962-7eae8a00-9985-11eb-82df-6f277c703259.png">

<img width="1180" alt="Screenshot 2021-04-09 at 22 45 41" src="https://user-images.githubusercontent.com/6454286/114243952-7b1b0300-9985-11eb-91ac-28edb5e9f6ee.png">

I tried using the `render_component` over the `render` as mentioned above, but that was to no avail.
The issue seems to be that these two functions get called recursively–`get_slot` and `renders_one` but I'm not sure why.

My setup is just the basic example of a "pass through slot"

PanelComponent.rb

```ruby
# typed: strict

class PanelComponent < ApplicationComponent
  renders_one :content
  renders_one :header
  
  sig { params(title: String, show_logo: T::Boolean, options: T.untyped).void }
  def initialize(title: "", show_logo: true, **options)
    @title = title
    @show_logo = show_logo
    @options = options
  end

end
```

panel_component.html.erb

```erb
<div class="mx-auto max-w-sm p-4 w-11/12 md:w-full shadow-xl bg-white rounded-md">
<%= content %>
</div>
```

new.html.erb

```erb
<%= render_component Panel.new do |p| %>
  <%= p.content do %>
  <div>This should hopefully show up!</div>
  <% end %>
<% end %>
```

The stack depth too deep issue is risen every time I try to reference a slot defined on the class body, with the `renders_one` property (have yet to try renders_many) regardless of how it is defined (using a block, or with a component etc).

**Comment by BlakeWilliams** [comment]
@jesster2k10 My guess is that it's due to having a slot named `:content`. I think it may be conflicting with the `content` method defined on components by default.

Can you try renaming that slot? If that works let me know, since we should raise if a slot is named `:content`.

**Comment by jesster2k10** [comment]
@BlakeWilliams Yes! That was the issue. Renaming it and it worked perfectly. I think if there's a conflict it might make sense to raise an error or at lease point out in the docs, that naming a slot `:content` might cause a conflict

**Comment by BlakeWilliams** [comment]
@jesster2k10 Glad that was it! I agree about raising if there's a conflict. Any interest in opening a PR to add that behavior?

**Comment by BlakeWilliams** [comment]
Opened a PR to address that specific issue here: https://github.com/github/view_component/pull/858
