### ISSUE TITLE
UnitialzedConstant error if you set both `config.view_component.preview_controller` and `config.view_component.preview_route`

### ISSUE THREAD

**Issue by gkemmey** [github/view_component#566]
### Steps to reproduce

Technically, you also need `config.eager_load = false` and `ActionView::Base.cache_template_loading = false`, but those are the Rails defaults in development.

So if I set both `preview_controller` and `preview_route` and navigate to `http://localhost:3000/rails/view_components/example_component/default`, I get this error:

```
Puma caught this error: uninitialized constant ViewComponent::Engine::CompileCache
Did you mean?  ViewComponent::Compiler (NameError)
```

Repo: https://github.com/gkemmey/view_component_bug_repro. (You gotta run `rails server` with `BREAK_IT=true` to opt-in to the offending configuration [here](https://github.com/gkemmey/view_component_bug_repro/blob/main/config/environments/development.rb#L77-L80).)

### Expected behavior

Show the previews.

### Actual behavior

Raises an error.

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.7.1

**Gem version**: 2.24.0

---

### Why's it happen?

I think because once we set both the config options, we no longer load `ViewComponent::Base` -- which normally happens on [one of these lines](https://github.com/github/view_component/blob/v2.24.0/lib/view_component/engine.rb#L16-L17) -- before this line of code runs: https://github.com/github/view_component/blob/v2.24.0/lib/view_component/engine.rb#L102

### Fixing it (maybe)

For me, adding `require "view_component/compile_cache"` in `engine.rb` after [this line](https://github.com/github/view_component/blob/v2.24.0/lib/view_component/engine.rb#L4) seems to fix it. But not sure that's the right place to add it. Could also add it to `autoload`, but seemed this repo didn't for private / internal stuffs?

Right now, `base.rb` [manually loads it](https://github.com/github/view_component/blob/v2.24.0/lib/view_component/base.rb#L6).

---

> If possible, please provide a PR with a failing test for bugs instead of filing an issue.

It wasn't obvious to me how to write such a test since I think it would depend on not eager loading and setting those config options in `test.rb`. For what it's worth, these changes produce a failing test (but also break others):

```rb
# test/config/environments/test.rb

config.view_component.preview_controller = "ViewComponentsController"
config.view_component.preview_route = "/rails/view_components"
config.eager_load = false
```

```rb
# test/view_component/integration_test

class IntegrationTest < ActionDispatch::IntegrationTest
  def test_do_em_both_together
    ActionView::Base.cache_template_loading = false
    
    with_preview_controller("MyPreviewController") do
      get "/rails/view_components"
      assert_equal response.body, "Custom controller"
    end
  end
end
```

Then run it on its own with: `bundle exec ruby -I test -I lib test/view_component/integration_test.rb -n test_do_em_both_together`.

**Comment by joelhawksley** [comment]
@gkemmey thank you so much for the detailed bug report and example repo! I think your suggested solution is more or less correct. Would you be up for a pairing session to fix this together? Feel free to email me: joelhawksley@github.com

**Comment by gkemmey** [comment]
Sure thing. Thanks for the gem! Yeah, I'm up for pairing anytime --
whenever works for you.

**Comment by allmarkedup** [comment]
If anyone is also running into this issue and needs a quick fix, explicitly adding `require "view_component/compile_cache"` into the top of your `config/application.rb` file worked for me.

**Comment by grekko** [comment]
Hey @gkemmey @joelhawksley thanks for the explanation, I experienced this behaviour now, too. Did you by any chance got the time to work on a fix, which does not require users to load the compile cache by hand, e.g. in `config/application.rb`?

**Comment by joelhawksley** [comment]
@grekko I've not made any progress here. I'd be open to your suggestions ❤️

**Comment by grekko** [comment]
> @grekko I've not made any progress here. I'd be open to your suggestions ❤️

I'd go with what @gkemmey already proposed:

> Could also add it to autoload, but seemed this repo didn't for private / internal stuffs?

Declaring `CompileCache` to be an autoloadable const seems reasonable.

I created a PR https://github.com/github/view_component/pull/1123 which fixed the broken behaviour in the [bug repo](https://github.com/gkemmey/view_component_bug_repro) provided by @gkemmey
