### ISSUE TITLE
render_many doesn't work right with Slim

### ISSUE THREAD

**Issue by dkniffin** [github/view_component#571]
### Steps to reproduce

```
# app/components/foo_component.rb
class FooComponent < ViewComponent::Base
  include ViewComponent::SlotableV2

  renders_many :bars, BarComponent
end
```
```
# app/components/foo_component.html.slim
- bars.each do |bar|
    = bar
```
```
# app/components/foo_component.html.slim
class BarComponent < ViewComponent::Base
end
```
```
# app/components/foo_component.html.slim
= content
```
```
# app/views/whatever.html.slim
= render FooComponent.new do |c|
  - c.bar do
    p Something with HTML formatting
```

### Expected behavior
When the HTML is rendered, the text "Something with HTML formatting" should be formatted correctly.

### Actual behavior
The HTML is escaped and rendered in the page so the end-user sees the HTML tags instead of the formatting.

### System configuration
**Rails version**:
6.0.3.4

**Ruby version**:
2.7.2p137

**Gem version**:
2.24.0

**Comment by joelhawksley** [comment]
@dkniffin thank you for the bug report! Would you be willing to open a PR with a failing test?

**Comment by dkniffin** [comment]
@joelhawksley Yeah, I can try and do that tomorrow

**Comment by dkniffin** [comment]
@manuelpuyol I think I tried that and it didn't work, but it's been a few weeks now. I started on a failing test but haven't gotten around to finishing it.

**Comment by manuelpuyol** [comment]
@dkniffin @joelhawksley I think I've found the issue!

Looking at the render stacktrace here:

```
 "/Users/manuelpuyol/github/view_component/lib/view_component/slot_v2.rb:26:in `to_s'",
 "/Library/Ruby/Gems/2.6.0/gems/temple-0.8.2/lib/temple/utils.rb:38:in `escape_html'",
 "/Library/Ruby/Gems/2.6.0/gems/temple-0.8.2/lib/temple/utils.rb:21:in `escape_html_safe'",
 "/Users/manuelpuyol/github/view_component/test/app/components/slim_renders_many_component.html.slim:3:in `block in call'",
 "/Users/manuelpuyol/github/view_component/test/app/components/slim_renders_many_component.html.slim:1:in `each'",
 "/Users/manuelpuyol/github/view_component/test/app/components/slim_renders_many_component.html.slim:1:in `call'",
 "(eval):3:in `render_template_for'",
 "/Users/manuelpuyol/github/view_component/lib/view_component/base.rb:79:in `render_in'",
```

When rendering the component, we have to go through `temple` to render the slim template. There, we have this check:

```rb
html.html_safe? ? html : escape_html(html)
```

Since `ViewComponent::SlotV2` is _technically_ html unsafe, `temple` is escaping the rendered component and causing the issue.
To verify this, I tried adding

```rb
def html_safe?
  true
end
```

to `ViewComponent::SlotV2` and the component rendered correctly

**Comment by dkniffin** [comment]
Nice! I see you also created a failing test for this 🎉 

Is defining `html_safe?` like that the right solution? 🤔

**Comment by manuelpuyol** [comment]
I'm not sure, that looks kinda dangerous to me since it will always assume that all of the content is safe, but that may not be the case if we are rendering inputs from users

**Comment by BlakeWilliams** [comment]
I agree that I don't think we want to assume safety. I think we could set an `@html_safe` ivar on `SlotV2` that's references the `html_safe?` value of the string returned from `to_s`.

**Comment by manuelpuyol** [comment]
problem is that `html_safe?` always returns false unless you explicitly call `.html_safe` on the object/string

**Comment by BlakeWilliams** [comment]
I was kind of imagining something like this, which would be almost like delegating `html_safe?` to the underlying template.

```ruby
class SlotV2
  def html_safe?
    @html_safe if defined?(@html_safe)
  end

  def to_s
    # some existing code
    content = capture do
      # more existing code
    end

    @html_safe = content.html_safe
    content
  end
end
```

Could something like that work?

**Comment by manuelpuyol** [comment]
I can see that working, will test it out in my PR

**Comment by manuelpuyol** [comment]
Well, actually checking the stack I commented before, `to_s` is called **after** the safety check 😬 
maybe we could have `def html_safe?` already capture the content and check safety and `to_s` use the previously calculated content. wdyt?

**Comment by BlakeWilliams** [comment]
> Well, actually checking the stack I commented before, `to_s` is called **after** the safety check 😬
> maybe we could have `def html_safe?` already capture the content and check safety and `to_s` use the previously calculated content. wdyt?

😭 that's unfortunate. I think that could work, but we'd probably want to run the performance benchmarks afterwards to ensure we aren't introducing any performance regressions.

**Comment by manuelpuyol** [comment]
I have this draft going with the fix https://github.com/github/view_component/pull/594
would you mind helping me with the performance benchmarks?

**Comment by BlakeWilliams** [comment]
sure thing!

The benchmarks have rake tasks here, https://github.com/github/view_component/blob/main/Rakefile#L13-L18

so you should be able to run `bin/rake benchmark` and `bin/rake slotable_benchmark` to see the results that you can compare against `main`.
