### ISSUE TITLE
SlotableV2 docs example for Delegate Slots throws errors

### ISSUE THREAD

**Issue by phacks** [github/view_component#622]
The example code given in https://viewcomponent.org/#delegate-slots appears not to be working out of the box and raises two different errors:

- `missing keyword: :title`
- `Could not find a template file or inline render method for BlogComponent::HeaderComponent`

### Steps to reproduce

Here’s a simplified version of the example code focusing only on `HeaderComponent`:

`# blog_component.rb`

```ruby
class BlogComponent < ViewComponent::Base
  include ViewComponent::SlotableV2

  # Since `HeaderComponent` is nested inside of this component, we have to
  # reference it as a string instead of a class name.
  renders_one :header, "HeaderComponent"

  class HeaderComponent < ViewComponent::Base
    attr_reader :title

    def initialize(title:)
      @title = title
    end
  end
end
```

`# blog_component.html.erb`

```ruby
<div>
  <h1><%= header %></h1> <!-- render the header component -->
</div>
```

`# index.html.erb `

```ruby
<%= render BlogComponent.new do |c| %>
  <% c.header do %>
    <%= link_to "My Site", root_path %>
  <% end %>
<% end %>
```

### Expected behavior

The example code in the docs should not raise errors.

### Actual behavior

Running the above snippets first raises a `missing keyword: :title` title, which can be solved with the following change:

```diff
<%= render BlogComponent.new do |c| %>
-  <% c.header do %>
+  <% c.header(title: "My Title") do %>
    <%= link_to "My Site", root_path %>
  <% end %>
<% end %>
```

First error is gone, but we now get to another one: `Could not find a template file or inline render method for BlogComponent::HeaderComponent`

I was able to work around _that one_ with the following change:

```diff
class BlogComponent < ViewComponent::Base
  include ViewComponent::SlotableV2

  # Since `HeaderComponent` is nested inside of this component, we have to
  # reference it as a string instead of a class name.
  renders_one :header, "HeaderComponent"

  class HeaderComponent < ViewComponent::Base
    attr_reader :title

    def initialize(title:)
      @title = title
    end
+ 
+  def call
+    content
+  end
  end
end
```

### System configuration
**Rails version**: `6.0.3.4`

**Ruby version**: `2.7.2`

**Gem version**: `2.25.1`

### Suggestions

For the first error, I’m happy to create a docs PR to update that example to remove that error and actually use the parameter we pass to the component, e.g.:

```ruby
class BlogComponent < ViewComponent::Base
  include ViewComponent::SlotableV2

  # Since `HeaderComponent` is nested inside of this component, we have to
  # reference it as a string instead of a class name.
  renders_one :header, "HeaderComponent"

  class HeaderComponent < ViewComponent::Base
    attr_reader :classes

    def initialize(classes:)
      @classes = classes
    end
  end
end
```

```ruby
<div>
  <h1 "<%= @classes %>"><%= header %></h1> <!-- render the header component -->
</div>
```

For the second error, I’m not sure if the addition of

```ruby
def call
  content
end
```

would be considered good practice or an antipattern. Would appreciate your opinions on this, and I’d be happy to add that to the PR.

**Comment by BlakeWilliams** [comment]
Thanks for the report! A PR to fix up the docs would be great. ❤️ 

For the second error, I think doing something like the following may make sense::

```ruby
def call
  content_tag :header, content
end
```

**Comment by phacks** [comment]
@BlakeWilliams PR’s up at #624!
