### ISSUE TITLE
Add a `--stimulus` flag to generate a Stimulus controller for the component

### ISSUE THREAD

**Issue by Spone** [github/view_component#627]
## Feature request

As documentation mentions how to use Stimulus (see #481 and #485), I figured we could go a step further by adding [Stimulus](https://stimulus.hotwire.dev) support to the component generator.

Similar to `--inline` or `--sidecar`, it would be nice to allow a `--stimulus flag` when working with Stimulus:

```
bin/rails generate component Example --stimulus                 
Running via Spring preloader in process 15839
      create  app/components/example_component.rb
      invoke  test_unit
      create    test/components/example_component_test.rb
      invoke  slim
      create    app/components/example_component.html.slim
      create    app/components/example_component_controller.js
```

The content of the generated file (`app/components/example_component_controller.js`) could be:

```js
import { Controller } from "stimulus";

export default class extends Controller {
  connect() {
    console.log("Hello, Stimulus!", this.element);
  }
}
```

It would also be great if the generated template could include the correct `data-controller` attribute (the `parameterize`d name of the component, using `--` as a separator is the component is namespaced).

### Motivation

When adding a Stimulus controller to a component, you have to create the controller JS file and them add some boilerplate in it, then you have to add the `data-controller` attribute to the component root. This feature would make it faster by automating these two steps.

**Comment by joelhawksley** [comment]
@Spone let's do it! Would you like to take this on?
