### ISSUE TITLE
Add a config entry to specify where `bin/rails generate component` should create spec file

### ISSUE THREAD

**Issue by phacks** [github/view_component#632]
## Feature request

It would be great to have a new config entry to specify the path and suffix which the command will use to create specs, e.g.

```ruby
config.view_component.test_path = "#{Rails.root}/spec/components"
config.view_component.test_file_suffix = "spec"
```

Which would yield the following result on running the command:

```
bin/rails generate component Example title content
      invoke  test_unit
      create  spec/components/example_component_spec.rb
```

### Motivation

I use the `bin/rails generate component` command to create new components, but have to manually move the generated spec file from `test/components` to `spec/components` as we’re using Rspec, and rename it to match other spec files. Adding a config entry would avoid that.

Happy to work on a PR for that! I would just want to make sure first if we want to go with my config suggestion above or go with something like `config.view_components.test_framework == 'rspec'` that would apply the relevant defaults.

**Comment by joelhawksley** [comment]
@phacks thanks for filing this request! @Spone has been looking into improving our generators, perhaps he might have some feedback here?

**Comment by Spone** [comment]
Hi @phacks! I haven't tried the Rspec integration myself but I see that the generator should put the file at the right place by default: https://github.com/github/view_component/blob/36b6e369130e7b5063e4750539b807bc7a73d37a/lib/rails/generators/rspec/component_generator.rb#L9

Maybe @rdavid1099 or @dylnclrk, who contributed the Rspec generator (#120) can help?

**Comment by phacks** [comment]
Oh wow, TIL! Thanks @Spone 😄 

Should I add a bit to the docs to make people aware of that option? e.g.

```diff
+ ViewComponent includes template generators for test_unit and Rspec test frameworks and will default to the test framework specified in `config.generators.test_framework`.

+ To generate specs for Rspec, pass the --test_framework option:

+ ```
+ bin/rails generate component Example title content --test_framework rspec
+ ```
```

**Comment by Spone** [comment]
Do you use the `rspec-rails` gem? It defines the `test_framework` option to `:rspec` ([see here](https://github.com/rspec/rspec-rails/blob/53604f4f98d54c95fa88bb1e972229c29e9353f9/lib/rspec-rails.rb#L20)) so you don't have to set it yourself every time you run the generator.

Alternatively, you can add this to `config/application.rb`:

```rb
config.generators do |g|
  g.test_framework :rspec
end
```

([source](https://guides.rubyonrails.org/generators.html#customizing-your-workflow))

**Comment by phacks** [comment]
You are _absolutely_ correct (and I learned yet another thing today).

Re-running my scenario, I appear to have completely missed my original point: the generated test file _does_ have the right path and name, it’s the _preview_ file that does not. I’m sorry about the whole mix-up here, and I appreciate your patience.

I have the following config set:

```
# Specify the previews path
config.view_component.preview_paths << "#{Rails.root}/spec/components/previews"
```

yet the generated preview ends up in `test/components/previews`:

```
rails generate component Example --preview
      create  app/components/example_component.rb
      invoke  rspec
      create    spec/components/example_component_spec.rb
      invoke  preview
      create    test/components/previews/example_component_preview.rb
      invoke  haml
      create    app/components/example_component.html.haml
```

I’d be happy to close this issue and open another one with the correct feature request, or edit the title and first post of that one. I’d also be interested in drafting a PR to have the generated preview land in `preview_paths` if that config’s set—I think it would be a small change here:

https://github.com/github/view_component/blob/435151e05f10b10631306f2fabc462039408e31d/lib/rails/generators/preview/component_generator.rb#L10-L12

**Comment by Spone** [comment]
No worries :)

And you're lucky then, there is currently a PR in review that does exactly what you want: https://github.com/github/view_component/pull/631

Can I close this issue?

**Comment by phacks** [comment]
Happy days! Of course, go ahead. Thanks so much!
