### ISSUE TITLE
Problems rendering a component that has no template

### ISSUE THREAD

**Issue by afuno** [github/view_component#634]
I'm creating component wrappers for Vue JS components. Sometimes I don't need a template file. For example, it looks like this:

```ruby
module Ds
  class LogoComponent < ApplicationComponent
    def call
      content_tag 'vc-logo', nil
    end
  end
end
```

My rubocop notes `content_tag` and advises to use tag. That is, it should be like this:

```ruby
module Ds
  class LogoComponent < ApplicationComponent
    def call
      tag 'vc-logo'
    end
  end
end
```

And this component will work and render. But everything below this component, the "neighbors" of its parent, are no longer displayed. But with `content_tag` everything was normal.

Who is to blame and what is the matter? 🙂

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 2.7.2p137

**Gem version**: 2.25.1

**Comment by joelhawksley** [comment]
@afuno Thanks for the bug report! Would you be willing to file a PR with a failing test?

**Comment by afuno** [comment]
@joelhawksley Sorry, I would really like to help, but right now it is difficult for me to understand the process of writing tests for your library ☹️

**Comment by BlakeWilliams** [comment]
@afuno I looked at the docs for `tag` briefly, I think you may need to call a method on it?

e.g.

```ruby
tag.h1 'vc-logo'
```

**Comment by afuno** [comment]
@BlakeWilliams It won't help me generate this:

```html
<vc-logo></vc-logo>
```

**Comment by johannesengl** [comment]
Happy to give a hand on this one! 

Could the issue be related to that you are trying to not render a non-standard HTML tag? Curious if the issue persists if you would render a standard HTML tag. 
Also, you are saying the component itself is being rendered but the "neighbors" are not. Could you clarify this so I can try to reproduce your issue?

**Comment by afuno** [comment]
@johannesengl 

```ruby
tag.vc_logo
```

It works. Thank you.
