### ISSUE TITLE
SlotsV2 aren't rendered if no arguments are provided

### ISSUE THREAD

**Issue by manuelpuyol** [github/view_component#637]
https://github.com/github/view_component/pull/636

### Steps to reproduce
1. Create a Component using SlotsV2
1. Add a slot that can be fully rendered using its default arguments (such as an icon)
1. Call the component and do not provide arguments to the slot
1. Slot will not be rendered

### Expected behavior
Expected the slot to be rendered using its default arguments

### Actual behavior
Slots is not rendered

### System configuration
**Gem version**: master branch

**Comment by BlakeWilliams** [comment]
@manuelpuyol Do you feel like this is something we should still look at changing?

**Comment by manuelpuyol** [comment]
I think we can close this
