### ISSUE TITLE
Regression in v2.26.0 causing `undefined local variable or method `collection_parameter'` error

### ISSUE THREAD

**Issue by mejackreed** [github/view_component#642]
When using `with_collection_parameter`, errors are raised when rendering these view_components. I've traced this back to #638. When removing that change, everything seems to work fine.

### Steps to reproduce
A minimal sample application that reproduces the error is here: https://github.com/mejackreed/test-view-component-regression

And you can see a minimal view_component that causes the issue in https://github.com/mejackreed/test-view-component-regression/commit/2cedf0cc1d929c577e3bcb156580f94b2ed5b7f9

### Expected behavior
view_components should be able to render

### Actual behavior
errors are raised

```
undefined local variable or method `collection_parameter' for ProductComponent:Class
```

### System configuration
**Rails version**: v6.1.3

**Ruby version**: v2.7.2

**Gem version**: v2.26.0

**Comment by BlakeWilliams** [comment]
@mejackreed Thanks for the report! Would you mind opening an issue with a failing test? Sadly we didn't have test coverage for this scenario, and I can take a look sooner if I can pull in an already failing test.

**Comment by mejackreed** [comment]
Thanks @BlakeWilliams . I've looked into creating a failing test for this, but unfortunately it passes 😢 .

My guess here is that something in the test harness is calling `compile` at which point the error is no longer raised. 

https://github.com/github/view_component/compare/main...mejackreed:failing-test?expand=1

I don't have much experience with the `view_component` internals or how are the tests are setup. Any direction you could point me on this would be appreciated.

**Comment by joshleblanc** [comment]
This occurs when using `MyComponent#with_collection` as well

**Comment by BlakeWilliams** [comment]
@mejackreed Ah, I think I see what's going on. Since everything is precompiled before the tests run it will be hard to reproduce by defining a component before the test suite runs.

I think it may be necessary to define a component directly in the test. e.g.

```ruby
def test_collection_parameter_compile
  my_component_klass = Class.new(ViewComponent::Base)

  render_inline my_component_klass.new
end
```

**Comment by mejackreed** [comment]
Thanks for the pointer @BlakeWilliams . You can get a failing test now from here: https://github.com/github/view_component/commit/77411a045fc0f122ae9b44994df633b8391992a5

**Comment by jakemumu** [comment]
Seeing this as well : )

**Comment by BlakeWilliams** [comment]
Thanks again for the report!

`2.26.1` was just released which should have the fix for collections included.

**Comment by mejackreed** [comment]
Thanks so much @BlakeWilliams
