### ISSUE TITLE
Remove the Component suffix from components

### ISSUE THREAD

**Issue by BlakeWilliams** [github/view_component#670]
As we've written and used components the `Component` suffix has been questioned a few times. Looking at current uses of components, it looks like the namespaces used are unique even when the `Component` suffix is removed. I think this is due to following the naming convention of views, which is to use the plural paths in the namespace. e.g. `users/index.html.erb` -> `Users::IndexComponent`/`Users::Index`.

Lately I've been thinking about components as "models that return markup". Models don't have a suffix (and neither do views, although they are usually templates), so maybe components shouldn't either?

Here's the pro's and con's I can think of at the moment:

* **Pro**: Less boilerplate and better readability. No more `render Primer::LinkComponent.new`, we can now call `render Primer::Link.new`. Once you learn that components are objects that can be rendered, the `Component` suffix loses a lot of its value.
* **Pro**: Component names now completely align with the `views` naming conventions. This will make it easier to put components in the `views` directory if we go down that path.
* **Con**: It's no longer immediately clear that your class/object is a component.

**Comment by keithamus** [comment]
I'm 100% _for_ this idea. I think the `Con` is intrinsic to all software development: it's hard to know what type a "thing" is. The existing `Component` suffix is a bit like [Hungarian Notation](https://en.wikipedia.org/wiki/Hungarian_notation), I feel as there is a somewhat low enthusiasm for Hungarian Notation in general.

**Comment by jaredcwhite** [comment]
So instead of a `Post` model and a `PostComponent` view, what would be the recommended namespaced solution? `Posts::Item`? `Components::Post`? I think I'm on board with this idea but I'd want to name everything this way and not go piecemeal (aka some with `Component` suffix and some not).

**Comment by BlakeWilliams** [comment]
> So instead of a `Post` model and a `PostComponent` view, what would be the recommended namespaced solution? `Posts::Item`? `Components::Post`? I think I'm on board with this idea but I'd want to name everything this way and not go piecemeal (aka some with `Component` suffix and some not).

Great question! I agree we wouldn't want to have some components with the suffix, and some without.

If it's a component you're rendering from a controller, I really like `Posts::Index` or `Posts:Show`. If it's a generic post that you want to render on both the index and show pages, I like`Posts::Single`, but you could also follow Rails via `Posts::Post` (since that aligns with `app/views/post/_post.html.erb`). The latter would mean that you would need to access the `Post` model via `::Post`, but I think that's an acceptable trade-off.

**Comment by boardfish** [comment]
If you're using Atomic Design, putting your components under `A`tom, `M`olecule, and `O`rganism modules could be a good idea. Then you can tell that it's a component (due to the shorthand) and its level of responsibility (from what each module represents).

**Comment by boardfish** [comment]
I've just pushed up a [gem](https://github.com/boardfish/view_component-no_component) that ought to fix this issue. It replicates the standard generators, but doesn't generate files or classes with a `Component` suffix.

**Comment by joelhawksley** [comment]
Per https://github.com/github/view_component/pull/1005#issuecomment-885305710, I'm going to close this issue.

**Comment by boardfish** [comment]
#1194 reminded me of this issue - I've noticed that the `Component` suffix is hardcoded into a lot of templates, so if people wanted to adopt their own naming schemes, they'd currently have trouble. I'm not sure if this is something we want to deliberately advise against in the name of ensuring usage of ViewComponent is relatively consistent, but if not, is it worth making the pattern for component names configurable?

**Comment by Spone** [comment]
I would say that this significantly differs from the convention chosen by this gem, and as such, I think it's reasonable to let people implement it in their own generator if they want to (see [view_component-contrib](https://github.com/palkan/view_component-contrib#organizing-components-or-sidecar-pattern-extended) for instance).
