### ISSUE TITLE
Renaming default directory for components

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#863]
### Problem

- Existing Rails applications may already have an `app/components` directory.
- The term `component` is fairly generic and not necessarily view-related.

### Proposed solution

Move towards using `app/view_components` instead of `app/components`.

cc @palkan who suggested this idea to me during RailsConf ❤️

**Comment by BlakeWilliams** [comment]
What are your thoughts on putting components in `app/views` via adding it to the autoload path?

**Comment by Spone** [comment]
What about `app/views/components`? Similar to the common `app/views/shared`.

Also, if the main concern is that some apps may already have an `app/components` directory, what do you think about making the path configurable?

**Comment by joelhawksley** [comment]
@Spone I think making the directory configurable is the way to go, perhaps even instead of changing the default directory. What do you think @BlakeWilliams?

**Comment by BlakeWilliams** [comment]
I'm not opposed, but I am a little hesitant. I like the idea of defining a canonical component location in the spirit of "convention over configuration". 

Having a standard place for everything is one of the concepts that I love about Rails since I can immediately start contributing to applications since I know the structure/layout of the framework.

**Comment by Spone** [comment]
I agree that "convention over configuration" should stay the guiding principle.

But, in this specific case, we can draw a parallel with the existing Rails `javascript_path` setting.

> `config.javascript_path` sets the path where your app's JavaScript lives relative to the `app` directory. The default is `javascript`, used by webpacker.
> [source](https://guides.rubyonrails.org/configuring.html)

I would suggest:
- add a `config.view_component_path`
- keep `app/components` as the default (no change for most users)
