### ISSUE TITLE
View helpers using `content_tag` render duplicated content

### ISSUE THREAD

**Issue by guzart** [github/view_component#868]
I believe this issue is related to #240 

### Steps to reproduce

I think I bumped into #240  by using my own helpers that used `content_tag` internally. For example: 

```ruby
# app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def panel(&block)
    content_tag(:div, class: 'panel panel-default', &block)
  end
end
```

```erb
<!-- app/components/client_list_component.html.erb -->
<%= helpers.panel do %>
  The client list goes here
<% end %>
```

```ruby
# app/components/client_list_component.rb 
class ClientListComponent < ApplicationComponent
end
```

```erb
<!-- app/views/clients/index.html.erb -->
<%= render ClientListComponent.new %>
```

### Expected behavior

```html
<div class="panel panel-default">The client list goes here</div>
```

### Actual behavior

Output would have duplicated-ish content.

```html
The client list goes here
<div class="panel panel-default">The client list goes here</div>
```

### System configuration

**Rails version**: 6.1.3

**Ruby version**: 2.6.5

**Gem version**:  2.30

### Workaround

<details>
<summary>Full disclosure</summary>

![No Idea](https://media.giphy.com/media/SRx5tBBrTQOBi/giphy.gif)

</details>

I was able to work around it by changing the binding on the helper method to use the Component's view context with this piece of code:

```ruby
# app/components/application_component.rb
class ApplicationComponent < ViewComponent::Base
  def render_helper(name, &block)
    helpers.method(name).owner.instance_method(name).bind(helpers).call do
      with_output_buffer(nil, &block)
    end
  end
end
```

```erb
<!-- app/components/client_list_component.html.erb -->
<%= render_helper(:panel) do %>
  <%= render_helper(:panel_body) do %>
    Somehow it also works with nested helpers 🤷 
  <% end %>
<% end %>
```

**Output**
```html
<div class="panel panel-default">
    <div class="panel-body ">
      Somehow it also works with nested helpers 🤷 
    </div>
</div>
```

Though I am sure I am missing on a ton of edge cases and potential issues, I thought I'd share my hack @BlakeWilliams

**Comment by BlakeWilliams** [comment]
@guzart Thank you for the report!

It's unfortunate that `helpers` are impacted by this issue too, but it does make sense. One alternative work around could be to `include` the helper module which should define the method on the component itself. I think that would cause it to be evaluated in the context of the correct `@output_buffer`.

**Comment by guzart** [comment]
Oh, totally! Including the helper in the base ViewComponent is a much... MUCH simpler solution. Thanks!
