### ISSUE TITLE
Stimulus sidecar controller not working with values API

### ISSUE THREAD

**Issue by acetinick** [github/view_component#872]
### Steps to reproduce

have a sidecar stimulus 2 controller, that uses values API 

### Expected behavior
stimulus values API not compiling

### Actual behavior

<img width="1030" alt="Screenshot 2021-04-21 at 04 48 26" src="https://user-images.githubusercontent.com/571649/115485158-d1792300-a25c-11eb-9821-87299886426f.png">

application-28cc44ed3f79a9550d3c.js:9 Uncaught Error: Module parse failed: Unexpected token (6:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| export default class extends Controller {
>     static targets = ["input", "listA", "listB"]
| 
|     static values = {
    at Object../app/components/forms/listbox_component_controller.js (application-28cc44ed3f79a9550d3c.js:9)
    at __webpack_require__ (bootstrap:19)
    at webpackContext ((index):14)
    at definitionForModuleWithContextAndKey (index.js:9)

### System configuration
**Rails version**: 6.0,3,6

**Ruby version**: 2.66

**Gem version**: 2.29

**Comment by BlakeWilliams** [comment]
👋 From the looks of it, this looks like a webpacker/stimulus issue and isn't related to view component?

If that's the case, maybe this should be an issue in one of those repos instead?

**Comment by acetinick** [comment]
You assumed right)  Ended up being additional line that i needed to my webpacker.yml

  additional_paths: ["app/components"]
