### ISSUE TITLE
Duplicated content started to appear when using `<%=` to capture slots in v2.31

### ISSUE THREAD

**Issue by elia** [github/view_component#890]
[This change](https://github.com/github/view_component/commit/358fbe2ef60b1d2e2d7de308a58f718bade6dd5f#diff-f4d01a0600f7ce443a17504bbf4275827066c6a3430e92e0a440b3d344be8ab5L258-R258), introduced in v2.31, broke some of our components that were wrongly using `<%=` instead of `<%` to capture slot blocks.

Although it's not strictly a bug I think the documentation is not consistent/explicit in discouraging that, and a changelog entry would probably be useful as well. Or, if the change is not functional to any other feature, we can revert the change and reintroduce it in v2.32.

**Comment by manuelpuyol** [comment]
👋  that implementation is indeed needed for the `with_content` API. Is there a use-case for using `<%=` with slots?

**Comment by BlakeWilliams** [comment]
I think updating the documentation is a good idea. It looks like we recommend `<%=` in a few places when we shouldn't.
