### ISSUE TITLE
Embed contributing and changelog pages into docs

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#902]
### Problem

As a visitor to the docs site, I'm not able to easily find the change log and contribution guidelines.

### Proposed solution

Symlink both pages into the docs site so they are rendered at the bottom of the sidebar.

**Comment by dmarcoux** [comment]
I had a look and this was addressed in #972 when _CHANGELOG.md_ and _CONTRIBUTING.md_ were moved to the _docs_ directory.

They are both available in the sidebar of the docs website. See this screenshot from the sidebar:

![viewcomponent](https://user-images.githubusercontent.com/1102934/132546399-8d2e28f4-3e05-46a9-94ba-ad8f8433b513.png)

**Comment by joelhawksley** [comment]
@dmarcoux you're right! I should have closed this ❤️
