### ISSUE TITLE
Empty components/slots now raising whiny nil error in 2.32.0

### ISSUE THREAD

**Issue by agrobbin** [github/view_component#937]
### Steps to reproduce

If a component renders nothing, for whatever reason, the changes made in #921 result in an `ActionView::Template::Error` (well, technically a `NoMethodError`):

```
undefined method `+' for nil:NilClass
```

It looks like something similar was raised post-merge in https://github.com/github/view_component/pull/921#discussion_r638121759, but in our case, it's not just b/c we've overridden `call` to return `nil` (though we have in a couple instances!), but we also have a component with a slot that looks something like this:

```haml
= component.foo do
  - if something
    = something.interesting
```

### Expected behavior

This doesn't raise an error.

### Actual behavior

It raises an error starting in v2.32.0.

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.7.3

**Gem version**: 2.32.0

**Comment by filippoliverani** [comment]
I have a similar problem with components rendering numbers in `call`, what about doing an explicit cast to string here? https://github.com/github/view_component/blob/b436bd26989a82ced092f72e203e62dc9d8f1dbd/lib/view_component/base.rb#L94

**Comment by rainerborene** [comment]
+1 same here

**Comment by joelhawksley** [comment]
👍🏻 I think the string casting is the right way to go. Mind opening a PR with a failing test?

**Comment by agrobbin** [comment]
@joelhawksley done in #941! I included the fix in the PR as well, as it seemed straightforward enough.
