### ISSUE TITLE
Pass iterator to collection instead of count

### ISSUE THREAD

**Issue by willcosgrove** [github/view_component#939]
## Feature request
Currently when you render a component using the `with_collection` method, you can define a named parameter in the initializer for `#{collection_parameter}_counter` and receive the position counter of the component being rendered. This is tracked using `ActionView::PartialIterator` which provides a few other useful methods, like `first?` (which is knowable from the position count `count == 1`) and `last?` (which is _not_ knowable from the position count `count == ?`)

### Motivation

It can be helpful to modify how the template renders if it is the first or last element in the collection, but it's currently not possible to do that for the last element of a collection because it is not able to know that it is last. Since we already are using a `PartialIterator` to keep track of this, why not just pass the iterator to the components instead of the position count?

This would mimic the current capabilities of rendering a partial as a collection, which exposes the `PartialIterator` with the `#{partial_name}_iteration` local variable.

**Comment by joelhawksley** [comment]
@willcosgrove let's do it! Would you mind taking this on?

**Comment by willcosgrove** [comment]
I'd be happy to! I'll send over a PR later today

**Comment by willcosgrove** [comment]
@joelhawksley How do you want to handle backward compatibility?

We could:
* Expect to always allow both parameters to be used
* Allow both parameters for a time and add a warning when you use the `_counter` parameter
* Remove `_counter` parameter and replace it with `_iteration` parameter

**Comment by joelhawksley** [comment]
@willcosgrove isn't the `_counter` API also present in Rails? If so, I think we should allow both without any warning.
