### ISSUE TITLE
Add documentation for configuration options

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#953]
Per https://github.com/github/view_component/pull/952#discussion_r647465286, let's add a documentation section for configuration options to the API page, preferably generated via YARD.

cc @Spone

**Comment by joelhawksley** [comment]
@Spone I've assigned you, but feel free to take your name off this if you'd like ❤️

**Comment by Spone** [comment]
I think it maybe easier to write it manually like the Generators page (#952). I'm not sure how it could be generated via YARD.

**Comment by joelhawksley** [comment]
@Spone I _think_ we could extract the comments for the `mattr_accessors` that make up the configuration options via YARD 🤔
