### ISSUE TITLE
Rendering slots with variants - bug or feature? 🕵

### ISSUE THREAD

**Issue by boardfish** [github/view_component#954]
I wasn't really sure whether to file this under a feature request or bug report because it's somewhere between the two, but I've hit upon something interesting. I'm building a custom select component, and for that, I need to render a set of options twice - once as option tags, and once as whatever the custom select will contain. I'm doing so using a delegate slot on a parent Select component, and have the two different styles of SelectOption as variants. The default is for the custom select, but `call_option` will render the SelectOption as an option tag.

Inside the parent Select component, I figured out that I could do this:

```html.erb
<% options.each do |option| %>
  <%= render option.with_variant(:option) %>
<% end %>
<% options.each do |option| %>
  <%= option.with_variant(:default) %>
  <%= option %>
<% end %>
```
`with_variant` sets that variant as the one to use for the remainder of the render until it gets called with a different option. This functionality is pretty cool, but it has quirks:
- The former style (`render option.with_variant(:option)`) can only be used once. Doing this ignores the block passed to the slot:
```html.erb
<% options.each do |option| %>
  <%= render option.with_variant(:option) %>
<% end %>
<% options.each do |option| %>
  <%= render option.with_variant(:default) %>
<% end %>
```
- `<%= option.tap { |o| o.with_variant(:default) } %>` doesn't work, presumably because calling `option` evaluates to something different after `with_variant` has been called.

**Comment by joelhawksley** [comment]
@boardfish my gut says that this is an "off-menu" use of ViewComponent. I don't think we ever intended for `with_variant` to work for slots, and it might be worth making that more explicit by raising an exception if you do.

**Comment by boardfish** [comment]
That's certainly one route the project could take, but I see a lot of value in this as a potential feature. I'm sure there are other instances where we might want to reuse the same attributes to render a component more than once in a different style each time.

One thing I can think of would be a navbar — the same set of links could be rendered in twice with a different variant depending on whether that style of the navbar should be shown at mobile or desktop breakpoints. 

That having been said, I think the feature at hand here is rendering multiple component instances from the same data. Perhaps variants aren't the solution that's most in line with ViewComponent's guiding principles and there's another route we can take. Personally, I'm a pretty big fan of this as the solution to that problem and feel that it's quite an intuitive use of variants, but if there's a better approach we can take, I'm welcome to it.

It did cross my mind just now that a lambda slot could take an argument that decides which component it should return, like:

```ruby
renders_one :option, ->(variant:, **params) { variant == :option ? Option.new(**params) : CustomOption.new(**params) }
```

This might also work, but I prefer how slots with variants would read in the ideal case.

**Comment by joelhawksley** [comment]
@boardfish thanks for the explanation! I owe you more context on my thinking here:

ViewComponent variants are intended to match Rails' variants for traditional templates, the function of which I think https://reinteractive.com/posts/191-variants-with-ruby-on-rails describes my understanding well:

> Variants allow your app to easily serve different templates in different cases, for example, different templates for phones, tablets and desktops. In other words, variants allow you to arbitrarily respond with different templates within the same MIME type (e.g. HTML).

>To use Action Pack variants, you set the request.variant to a symbol for the name of the variant in a controller, probably in a before_action. You can then respond to each of those variants in your actions in the same way that you respond to different formats.

My impression has always been that variants are a per-request concept and not something that is meant to change within the context of rendering a single component as you've described. Perhaps @mrjonesbot can chime in here? (He's the one who introduced `with_variant`: https://github.com/github/view_component/pull/429

The lambda use case does seem like it would work, but I share your discomfort ❤️

**Comment by boardfish** [comment]
That makes sense. The way I see it, the request comes second — it feels to me as though the aim of `with_variant` is to change what is rendered, and it can be interpreted as more of a helpful feature than an explicit requirement that the default is based on the content of the request. I think it has a degree of separation from the concept of variants in Rails, which seem to go as far as the controller level when talking about how a variant might change things. The default value feels like a convenience to help ViewComponent play nicely with that idea, when in fact the idea of a variant could potentially be something more local to ViewComponent (perhaps under a different name).

I guess the easier question to ask is whether there's a recommended pattern for rendering a single component differently in various scenarios already, and whether that can extend to slots. But there's definitely an interesting discussion as to where variants fit around that.

**Comment by boardfish** [comment]
I've found another potential avenue. Something I've taken to doing is having two different components under the same namespace, so let's say a `Card::Expanded` and `Card::Mini`. They share attributes and slots by way of an included concern.

An easier (and safer) way to get to these without using `Card.const_get(style.to_s.camelcase(:upper))` would be nice, especially if it were to be compatible with Slots like this. Perhaps it's achievable by overriding an initializer like:

```ruby
def initialize(**params)
  # Don't actually use this, an unguarded `const_get` is trouble waiting to happen!
  const_get(params[:style]).new(**params)
end
```

Then there wouldn't even need to be a change to the Slots API and we'd just need to pass `style`.

I don't know how (or even if) this should be baked into ViewComponent, but I'm interested to hear your take on this.

**Comment by joelhawksley** [comment]
@boardfish I'd love to see a complete working example (perhaps in a demo repo?) of this set of components. Would you be able to provide one?

I'd also love to pair with you to see how you're working with ViewComponent. Send me an email: joelhawksley@github.com

**Comment by boardfish** [comment]
Yep, I've done so. I'll start on that demo repo.

**Comment by boardfish** [comment]
I think the place we got to in pair programming was that if a record can be displayed in two different ways, that should be two different components. So in the expanded/mini example above, it's more correct to say `Expanded` and `Mini` should be distinct and should be used directly where appropriate, rather than by passing a `style` option to something else.

However, the original purpose of this off-menu use of `with_variant` (which I admittedly lost sight of in this issue) was a way to render something in two different ways from the same parameters. 

I guess a way you could approach that right now would be to use lambda slots which use that same params hash, since IIRC those pass the block through to the component you return from the lambda. However, there's a minor inconvenience of having to call the slot twice when you use the component, e.g:

```html.erb
<%= render SomeComponent.new(option_params:  { name: 'Foo', value: 'foo' } do |c| %>
  <% c.native_option %> <%# would render Option.new(**{ name: 'Foo'... %>
  <% c.custom_option do |o| %>
    ...
  <% end %>
<% end %>
```

I feel like this approach might be the optimal solution for this issue, so I think I'll close on those grounds.

**Comment by boardfish** [comment]
To address the minor inconvenience of having to call a slot twice, it could be possible to define sub-components to handle this if the two elements are intended to be siblings in the DOM flow. But in the case of the Option example I have here, each of those slots renders into a different `div`. So I wonder if (but highly doubt) it's currently possible to do something like this:

```ruby
def option(&block)
  native_option(**params)
  custom_option(**params, &block)
end
```

```html.erb
<%= render SomeComponent.new do |c| %>
   <%= c.option(name: 'foo'...)
<% end %>
```

...and have it render both slots with the passed values.
