### ISSUE TITLE
Allow for accessing index number when using renders_many

### ISSUE THREAD

**Issue by dkniffin** [github/view_component#982]
## Feature request

I would like to be able to do something like this:
```slim
/ Usage (in slim)
= render ListComponent.new do |c|
  = c.list_item
    span Item A
  = c.list_item
    span Item B
  = c.list_item
    span Item C
```

```rb
class ListComponent < BaseComponent
  renders_many :list_items, ListItemComponent
end
```

```rb
class ListItemComponent < BaseComponent
  def item_number
    slot_index + 1
  end
end
```

`slot_index` is the new method I'm requesting, and it would be automatically set based on the position of that slot item in it's collection of slots. For example, calling that from within "Item A" in my example would return `0`, whereas calling it from within "Item B" would return `1`, etc.

### Motivation

The reason I'd like this feature is that I'm considering creating a component that creates a page layout, using Bootstrap's grid columns. I want to have `renders_many :columns`, but in order for that to work properly, the slot needs to know where it appears in the list of columns.

**Comment by joelhawksley** [comment]
@dkniffin oh, that's an interesting question! We solve this for rendering collections by using `ActionView::PartialIteration`. Perhaps we could do something similar here? 

I'd be happy to pair with you on getting a branch going for this: joelhawksley@github.com

**Comment by dkniffin** [comment]
@BigBigDoudou Thanks for the suggestion. I actually ended up finding another way to do this, that is covered by VC's specs [here](https://github.com/github/view_component/blob/4f9fb0f9074144291865b0189eea2d990bad8baf/test/sandbox/app/components/slots_v2_with_empty_lambda_component.rb#L5)

With the original example, this would be the result:

```slim
/ Usage (in slim)
= render ListComponent.new do |c|
  = c.list_item
    span Item A
  = c.list_item
    span Item B
  = c.list_item
    span Item C
```

```rb
class ListComponent < BaseComponent
  renders_many :list_items, ->(**args) {
    @column_count += 1
    ListItemComponent.new(**args.merge(index: @column_count - 1)
  }

  def initialize
    @column_count = 0
  end

end
```

```rb
class ListItemComponent < BaseComponent
  def initialize(index:)
    @index = index
  end

  def item_number
    @index + 1
  end
end
```

**Comment by Spone** [comment]
@dkniffin would you mind opening a PR to add this example to the docs? (probably [after this](https://viewcomponent.org/guide/slots.html#rendering-collections))
