### ISSUE TITLE
Add benchmark script

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#99]
It would be great to have some form of integration-level benchmark script that we can use to make sure changes to this library are not slowing things down.

I've used https://github.com/evanphx/benchmark-ips in the past, but am open to other options as well.

**Comment by rickychilcott** [comment]
The following might be examples of how to implement:

https://github.com/rom-rb/rom/blob/master/core/rakelib/benchmark.rake
https://github.com/rom-rb/rom/blob/master/core/benchmarks/basic_bench.rb
https://github.com/rom-rb/rom/blob/master/core/benchmarks/setup.rb

**Comment by juanmanuelramallo** [comment]
The tricky part here is that we need to boot a rails app to render the components and compare them with partials. Maybe then parse the logs to have the actual benchmark results. Will try to take a look at some point this week if no one else is on it
